### ISSUE TITLE
reloading an edit page changes the hidden input type of the form

### ISSUE THREAD

**Issue by schnika** [hotwired/turbo-rails#100]
Hello,

I am not sure what causes this. Maybe you can help me or point me into the direction where to debug it better. I activated turbo through the `turbo-rails` gem in our project and updated our javascript accordingly (use turbo:load where needed). Everything works fine as long as we don't refresh the browser window with (F5 or CTRL+R).

This is what the html of the form looks like when we navigate to it via turbo:

```
      <form action="/de/users/4" accept-charset="UTF-8" method="post">
          <input type="hidden" name="_method" value="patch">
          <input type="hidden" name="authenticity_token" value="nNJqcre0xFuHtcYgV4B3QpZ7WWJp3GBHIB77u/zEIrP6Y8BI6ySbkFah/zZyMYbyoJbONrVaSOwQyd5cRiH51w==">
          some form fields
      </form>  
```

But when I reload the form via the browser reload, F5 or a comparable action the form method changes to this:
```
      <form action="/de/users/4" accept-charset="UTF-8" method="post">
          <input type="hidden" name="_method" value="zacs80111Z93WjCRwU3+wsdvnqT19Osi9PN+U1BR6RMz9BqQY9YREicPbKlnWZ7oqQdvKTrVSkDEhQq8ywF9/A==">
          <input type="hidden" name="authenticity_token" value="nNJqcre0xFuHtcYgV4B3QpZ7WWJp3GBHIB77u/zEIrP6Y8BI6ySbkFah/zZyMYbyoJbONrVaSOwQyd5cRiH51w==">
          some form fields
      </form>  
```

The response from the server (when I look at the response within the network tab) looks like this:

```
<form action="/de/users/4" accept-charset="UTF-8" method="post">
  <input type="hidden" name="_method" value="patch" />
   <input type="hidden" name="authenticity_token" value="yhK+xEx30IIISmxWDLA7iJuNlSlkG4svyOa4RARUbqOsoxT+EOePSdleVUApAco4rWACfbido4T4MZ2jvrG1xw==" />
</form>
```
So server side everything is being returned correctly, but somehow elements within the form are getting replaced. 

From now on I can submit the form but it will perform a post request instead of a patch request and that won't work :).

We are using the `form_with ... remote:false` rails helper to build this form. 

When I deactivate `turbo-rails` in our pack everything works as expected.

Thanks for your help and have a great day.

Versions:

gem: 
turbo-rails 0.5.8
rails 6.0.3.4

package: 
"@hotwired/turbo-rails": "^7.0.0-beta.4"
"@rails/ujs": "^6.0.3"
"@rails/webpacker": "^5.2.1"

**Comment by jonathanhefner** [comment]
@schnika Are you using Firefox? If so, I think you may be experiencing [this Firefox bug](https://bugzilla.mozilla.org/show_bug.cgi?id=520561).

Related: rails/rails#40343.

**Comment by schnika** [comment]
@jonathanhefner wow. Thanks for the link. I can verify that this is not causing any issue in chrome and when I add autocomplete: :off to the form it works as expected. :+1: 
closed because it is not a turbo-rails issue.
