### ISSUE TITLE
Inconsistent local naming with namespace model

### ISSUE THREAD

**Issue by ryanwood** [hotwired/turbo-rails#103]
Given a normal model and a namespaced one:

```ruby
class Car < ActiveRecord::Base
end

@car = Car.first
@car.to_partial_path # => "cars/car"
@car.model_name.singular # => "car"
```

You can render the partial with `render @car` which will set `car` as a local variable. All expected.

With a namescaped model...

```ruby
class Space::Car < ActiveRecord::Base
end

@car = Space::Car.first
@car.to_partial_path # => "space/cars/car"
@car.model_name.singular # => "space_car"
```

When rendering in the view with the namespaced model using `render @car`, it will set `car` as a local variable as that is the name of the partial. However, when rendering via the `broadcastable` concern, it doesn't use the partial name to set the local variable name but [the singular version of the model name](https://github.com/hotwired/turbo-rails/blob/main/app/models/concerns/turbo/broadcastable.rb#L236). The only way to get this is work both ways is to manually override the `partial` and `locals` for each broadcast.

I'm not sure what the best path forward is but it seems that the naming of the local variable should be consistent whether rendering from a view or from a broadcast.

**Comment by seanpdoyle** [comment]
Is this similar to https://github.com/hotwired/turbo-rails/issues/102 and potentially resolved by https://github.com/hotwired/turbo-rails/issues/90?

**Comment by ryanwood** [comment]
Yes, that looks like the same issue and a proper fix. Guess I was a couple hours late to the party!

**Comment by ryanwood** [comment]
#90 did not end up fixing this issues. It's very similar but that one has to do with controller rendering and this one is focused on a broadcastable model. Working on a PR.
