### ISSUE TITLE
Issue with Turbo Frames and content_for

### ISSUE THREAD

**Issue by user073** [hotwired/turbo-rails#107]
turbo-rails: 7.0.0-beta.5

A frame is not replaced when the matching frame tag in the response is rendered in a [content_for](https://apidock.com/rails/ActionView/Helpers/CaptureHelper/content_for) block.

views/layouts/application.html.erb
```erb
...
<body>
  <p>Timestamp to show that only the frame is updated: <%= Time.current.to_i %></p>
  <% if content_for? :c %>
    <%= yield :c %>
  <% else %>
    <%= yield %>
  <% end %>
</body>
...
```

views/examples/a.html.erb
```erb
<%= turbo_frame_tag :example do %>
  <h1>A</h1>
  <%= render 'links' %>
<% end %>
```

views/examples/b.html.erb
```erb
<%= turbo_frame_tag :example do %>
  <h1>B</h1>
  <%= render 'links' %>
<% end %>
```

views/examples/c.html.erb
```erb
<% content_for :c do %>
  <%= turbo_frame_tag :example do %>
    <h1>C</h1>
    <%= render 'links' %>
  <% end %>
<% end %>
```

views/examples/_links.html.erb
```erb
<%= link_to 'a', a_path %>
<%= link_to 'b', b_path %>
<%= link_to 'c', c_path %>
```

controllers/examples_controller.rb
```rb
class ExamplesController < ApplicationController
  def a
  end

  def b
  end

  def c
  end
end
```

config/routes.rb
```rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'examples#a'
  get 'a', to: 'examples#a'
  get 'b', to: 'examples#b'
  get 'c', to: 'examples#c'
end
```

Please see this example repo: https://github.com/user073/turbo-frame-content-for-issue

Run `rails s` and visit localhost:3000. Click link "b". The frame is replaced. Click link "c". The frame is not replaced but it should be.

**Comment by en30** [comment]
The cause is rendering of layout rather than `content_for`
When `turbo-rails` get a request from a turbo-frame, it skips rendering of layout. 
https://github.com/hotwired/turbo-rails/blob/main/app/controllers/turbo/frames/frame_request.rb#L16
So response for `c` would be empty.

**Comment by user073** [comment]
OK.
