### ISSUE TITLE
Initializer crashes if asset pipeline is not used

### ISSUE THREAD

**Issue by Intrepidd** [hotwired/turbo-rails#11]
If the application does not use the asset pipeline, the app will crash because of the following initializer :

```
    initializer "turbo.assets" do
      Rails.application.config.assets.precompile += %w( turbo )
    end
```

> undefined method `assets' for #<Rails::Application::Configuration:0x00007fa70a4d6be8> (NoMethodError)

Happy to provide a pull request to fix this behaviour if you believe it should not crash in this case

Thanks for making this ! <3

**Comment by jasl** [comment]
a small fix would work

```ruby
if Rails.application.config.respond_to? :assets
  Rails.application.config.assets.precompile += %w( turbo )
end
```

any volunteer?

**Comment by Intrepidd** [comment]
I'll check how it's done in other rails engines and submit a PR
