### ISSUE TITLE
Overriding the broadcasting target for nested models

### ISSUE THREAD

**Issue by alexandreruban** [hotwired/turbo-rails#114]
Hello!

## Problem description

I encountered an issue today while learning Hotwire by working on a toy app with nested models. I am building a quote editor, where a quote has many line_item_dates and dates has many line_items. The models look like this:

```rb
# models/quote.rb

class Quote < ApplicationRecord
  has_many :line_item_dates, dependent: :destroy
  
  broadcasts_to ->(quote) { :quotes }, inserts_by: :prepend
end
```

```rb
# models/line_item_date.rb

class LineItemDate < ApplicationRecord
  belongs_to :quote
  has_many :line_items, dependent: :destroy
  
  validates :date, presence: true, uniqueness: { scope: :quote }
  
  broadcasts_to ->(line_item_date) { [line_item_date.quote, :line_item_dates] }, inserts_by: :prepend
end
```

```rb
class LineItem < ApplicationRecord
  belongs_to :line_item_date

  validates :name, presence: true
  validates :quantity, :price, presence: true, numericality: { only_integer: true }
  
  # This is where I have the problem, as there are multiple "line_items" targets on the page
  # I would like to "namespace" the "line_items" target by the dom_id of the line_item_date.
  # For example instead of having multiple "line_items" targets, I would like to have one 
  # "line_item_date_1_line_items"  target and one "line_item_date_2_line_items" target.
  broadcasts_to ->(item) { [item.line_item_date, :line_items] }
end
```

Here is a picture of my toy project to make it more clear (I can also share the code if you want). As you can see, there are two line_item_dates and two line_items. If I create a new line_item, for the second line_item_date, I want it to appear in the second line_item_date card. In other words, I want it to be appended to the turbo_frame with the target "line_item_date_2_line_item_dates"

<img width="1046" alt="Screenshot 2021-02-07 at 15 14 56" src="https://user-images.githubusercontent.com/33979976/107149144-4ecc1180-6957-11eb-95be-faf43886cd6f.png">

## Solution

It should be possible to "namespace" the targets to avoid having multiple targets of the same name on the same page. The class method `.broadcast_target_default` in Broadcastable is not specific enough to identify targets when there are multiple targets with the same name on the page (in the case of a quote editor for example).

I would *love* (😍) to contribute on this issue, I will submit a pull request this afternoon!

This is my (almost) first contribution to Rails as I opened my first pull request in the `rails` main repo a few days ago so I hope I made things right. Please tell me if my message above is not clear enough!

**Comment by dhh** [comment]
Closing as the work is continuing in the PR.
