### ISSUE TITLE
Error: Form responses must redirect to another location

### ISSUE THREAD

**Issue by nyrf** [hotwired/turbo-rails#12]
After use turbo, got error message `Error: Form responses must redirect to another location`  if submit form fail

`post.rb`

```ruby
class Post < ApplicationRecord
  validates :title, presence: true, uniqueness: { case_sensitive: false }
end
```

```ruby
  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end
```

```erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>
```
<img width="1164" alt="WX20201223-014812@2x" src="https://user-images.githubusercontent.com/299532/102917900-f2a15100-44c0-11eb-8014-1c61cbe4df6f.png">

**Comment by adammiribyan** [comment]
Upgrading to rails 6.1 fixed this.

**Comment by adammiribyan** [comment]
Also, make sure you're using at least ruby 2.6.

**Comment by nyrf** [comment]
@adammiribyan I'm using ruby 2.7.2.

**Comment by nyrf** [comment]
It works if  use `turbo_frame_tag` to wrap the form, but normal form still got the error.

```erb
<%= turbo_frame_tag "post" do %>
  <%= render 'form', post: @post %>
<% end %>
```

**Comment by adammiribyan** [comment]
@nyrf what's your controller code for that form?

**Comment by nyrf** [comment]
@adammiribyan I used default scaffold command, `rails g scaffold post title body:text`

**Comment by dhh** [comment]
Yeah, Turbo currently requires a redirect. Not compatible with responding with HTML to a POST for error handling. We're looking into ways to support this.

**Comment by pbougie** [comment]
How do I do a complete form with validation, populated form fields on validation failure, redirect on success with Turbo? I can't find a single complete example that works. What about a mechanism to turn it off so my current forms can continue working until I find a workable solution/have time to migrate?

**Comment by dylanjha** [comment]
@pbougie if you found an easy way to have forms opt-out of Turbo behavior that would be 💯 . The "default" rails way to do things that I usually see is:

- submit a form
- redirect on success
- render html on error

As such, since Turbo currently *requires* redirects on all forms, it's a major blocker to prevent folks switching over.

Thanks all. Other than that small snag, this Turbo thing is pretty neat, I was able to drop it into an existing rails app pretty easily!  🙌

**Comment by mhfs** [comment]
> Yeah, Turbo currently requires a redirect. Not compatible with responding with HTML to a POST for error handling. We're looking into ways to support this.

Curious on how you're dealing with forms and validations in Hey/Basecamp. Client side validations and being certain the submit will succeed and result in a redirect?

**Comment by dhh** [comment]
Fixed in 0.5.3. Render your form error response with unprocessable entity (422) and Turbo will display it.

**Comment by charlietag** [comment]
Hi @nyrf ,

I'm trying Rails 6.1 + gem hotwire-rails (latest version).

And I think it works this way
No turbo_stream.erb files needed.
It works like traditional form submission usage

```diff
  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
-        format.json { render :show, status: :created, location: @post }
      else
-        format.html { render :new }
+        format.html { render :new, status: :unprocessable_entity}
-        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end
```

**Comment by jakemumu** [comment]
Sorry to bring this up from the dead, but when I use this trick of `status: :unprocessable_entity` it kills javascript running in the application. -- does anyone else have this issue?

**Comment by charlietag** [comment]
> I dont think the scafold generators know to add the status: :unprocessable_entity in rails 7.01

I think it does.

![image](https://user-images.githubusercontent.com/6238917/149351649-ef6900aa-7a23-400c-9bad-a5cd28c21e11.png)

**Comment by lapser** [comment]
> Yeah, Turbo currently requires a redirect. Not compatible with responding with HTML to a POST for error handling. We're looking into ways to support this.

@dhh Any news on supporting TURBO_STREAM responses like `render(html: "Support HTML", ...)`?

**Comment by marcoroth** [comment]
> dhh Any news on supporting TURBO_STREAM responses like `render(html: "Support HTML", ...)`?

@lapser you can already do this today, just add the `turbo_stream` format to your `respond_to` block and add the `status: :unprocessable_entity`:

```ruby
format.turbo_stream { render turbo_stream: turbo_stream.append_all(body, "Form submission failed"), status: :unprocessable_entity }
```

**Comment by topherfangio** [comment]
> Sorry to bring this up from the dead, but when I use this trick of `status: :unprocessable_entity` it kills javascript running in the application. -- does anyone else have this issue?

I just ran into this today and realized it wasn't a Turbo error, but rather the 3rd party library I was using.

It only initializes on page load, but we're replacing parts of the dom. So I had to wrap it with a Stimulus controller and manually run the code (a Datepicker in this instance).

I imagine you are likely hitting the same issue.

**Comment by lpknv** [comment]
> How do I do a complete form with validation, populated form fields on validation failure, redirect on success with Turbo? I can't find a single complete example that works. What about a mechanism to turn it off so my current forms can continue working until I find a workable solution/have time to migrate?

This is true. Currently having not the most pleasant time working with forms in rails, but I think it is only due to not 100% beginner friendly documentation and guides. (Once I get it to work, I definitely will write some guides on how to work with that...)
