### ISSUE TITLE
turbo streams & forms with method="get"

### ISSUE THREAD

**Issue by tomasc** [hotwired/turbo-rails#120]
I am no longer seeing the Accept header enhanced with the `text/vnd.turbo-stream.html` content type on get requests (using for example `button_to` in Rails). Is that intentional?

**Comment by seanpdoyle** [comment]
That is intentional. For background, there are discussions in both https://github.com/hotwired/turbo/pull/52 and https://github.com/hotwired/turbo-site/pull/40.

**Comment by tomasc** [comment]
@seanpdoyle thanks!
Would you have an advice how to implement this back in my app? I'd like to have `button_to` trigger get requests with Turbo Streams.

**Comment by seanpdoyle** [comment]
There is a discussion of alternatives here: https://github.com/hotwired/turbo-site/pull/40#discussion_r570471371

**Comment by tomasc** [comment]
I see …

BTW just to document this in case someone else find this issue. It is almost impossible to downgrade both `turbo-rails` and `turbo` at the same time using webpack (to revert back the above mentioned changes). Since `turbo-rails` specifies `turbo` version as a minimum (ie `^7.0.0-beta.3`), the latest version actually always leaks in. Just spent hours on this …

**Comment by allengreer-latero** [comment]
@tomasc If you are using yarn you can set a `resolution` version for a package to lock it. [See docs](https://classic.yarnpkg.com/en/docs/selective-version-resolutions/). Not sure if you can with npm? 

```
{
  ...
  "dependencies": {
    "@hotwired/turbo-rails": "7.0.0-beta.4",
  },
  "resolutions": {
    "@hotwired/turbo": "7.0.0-beta.3"
  }
}
```

**Comment by tomasc** [comment]
Thanks @allengreer-latero , much appreciated!
