### ISSUE TITLE
Turbo is not looking for partials in the correct path

### ISSUE THREAD

**Issue by A7madXatab** [hotwired/turbo-rails#123]
So i have a `Comment` that has a polymorphic association to a `commentable` model.

In my routes file i have this 

```
  resources :todo_sets do
    resources :comments, module: :todo_sets
  end
```

and in my forum i have this 

```
<%= form_for [@commentable, @commentable.comments.new] do |f|%>
    <section class="bg-white p-2 w-full my-2 border border--body rounded-lg">
      <%= f.rich_text_area :content, placeholder: 'Type your comment here' %>
    </section>

    <button type="submit" class="text-sm button__green px-3 py-2 rounded-full">Add this comment</button>
  <% end %>
```

when i submit a post response it eventually goes through this controller method

```
  def create
    @comment = @commentable.comments.new comment_params
    @comment.creator = current_user
    @comment.save

    respond_to do |format|
      format.turbo_stream
    end
  end
```

and inside my `create.turbo_stream.erb` file i have this 

```
<%= turbo_stream.append "comments", @comment %>
```

however rails cannot seem to find the partial path of the comment for some reason and i get this error

```
ActionView::Template::Error (Missing partial todo_sets/comments/_comment with {:locale=>[:en], :formats=>[:html], :variants=>[], :handlers=>[:raw, :erb, :html, :builder, :ruby, :jbuilder]}. Searched in:
```

i have my comment `_comment` file in this path `app/views/comments/_comment.html.erb`. 

Any clues on why this happens? thank you

**Comment by A7madXatab** [comment]
**EDIT**

so as described by dhh  [here](https://github.com/hotwired/turbo-rails/issues/65#issuecomment-754610690)

i did this and solved it, still. can anyone elborate on why this happens? I know that Rails uses the controller namespace to search for.

```
<%= turbo_stream.append 'comments', partial: "comments/comment", locals: {comment: @comment} %>
```

**Comment by kaspth** [comment]
Which version are you using? We've fixed some things related to rendering in the latest version, potentially https://github.com/hotwired/turbo-rails/pull/109 could be helping here.

**Comment by MrHubble** [comment]
@A7madXatab is this still an issue with the latest version?

**Comment by A7madXatab** [comment]
The thing was, it was my fault. I notice that the file extension mattered when naming partials. I had my partial like so

```
_partial.html.erb
```

notice the **`.html`** part. Here it means that rails would render this partial only when the request type is `text/html`. Moreover, when the request is turbo_stream. Rails cannot find any file with `_partial.turbo_stream.erb` inside the view directory. So, one possible solution is to remove the format from the file if you know they will both render the same result on both html and turbo_stream requests. 

```
_partial.erb
```

would do the trick!

**Comment by nimmolo** [comment]
In my app, rendering a partial `posts/_form.html.erb` from a turbo_stream response with explicit `formats: [:html]` did not work.

```ruby
render partial: "posts/form", locals: form_locals, formats: [:html]
```
Rails could not find the partial even with the path prefix `posts/form`. The only thing that works is removing `.html` from the `.html.erb` so it's just `.erb`
