### ISSUE TITLE
turbo_frame_tag causing inline javascript to break in chartkick

### ISSUE THREAD

**Issue by donrestarone** [hotwired/turbo-rails#125]
Hello! First of all, hats off to everyone who has contributed to this project! It has been a pleasure to work with and has slimmed down the websocket related code in all of my rails applications. 

While I was migrating an app that used chartkick, I noticed that changing the frame with the same partial breaks the javascript (added inline with a script tag). Any advice on how to fix this would be greatly appreciated!

the broadcast from the model looks like this 
``` ruby
broadcast_replace_to "user-#{self.user.id}-domains", partial: 'users/domains/card', locals: {d: self}
```
The frame looks like this
``` ruby
  <%= turbo_stream_from "user-#{current_user.id}-domains" %>
  <%= turbo_frame_tag "user-domains" do %> 
    <% @domains.each do |d| %>
      <%= render partial: 'card', locals: {d: d} %>
    <% end %>
  <% end %>
```
The partial implements chart kick like this
``` ruby
<%= turbo_frame_tag dom_id(d) 
    <%= column_chart(latency_chart_data, id: "chart-#{d.id}", colors: ["#14213D", "#FCA311"])
<% end %>
```

Im not sure what exactly is going on here because I was server rendering this exact partial before (without the elegance of hotwire of course). And the javascript was working. 

Here are some screenshots of dev tools
Before the update broadcast: 
![Screenshot from 2021-02-13 15-09-59](https://user-images.githubusercontent.com/35935196/107861057-348bab00-6e11-11eb-9453-2c7159824c46.png)
after the update broadcast:
![Screenshot from 2021-02-13 15-10-25](https://user-images.githubusercontent.com/35935196/107861069-41a89a00-6e11-11eb-9919-548282ba7cdc.png)

**Comment by emiellohr** [comment]
Hi, I'm running into the same issue. Looks like it has something to do with the latest changes in turbo.

https://discuss.hotwire.dev/t/javascript-in-turbo-frame-response-not-executed-anymore/2533/2

- turbo-rails (0.5.7)
+ turbo-rails (0.5.9)

**Comment by dhh** [comment]
This is tracked in Turbo under this issue: https://github.com/hotwired/turbo/issues/186
