### ISSUE TITLE
data-turbo-preview never added to html element

### ISSUE THREAD

**Issue by SleeplessByte** [hotwired/turbo-rails#127]
Version: `.beta5`

```typescript
if (isPreview) {
  this.element.setAttribute("data-turbo-preview", "");
} else {
  this.element.removeAttribute("data-turbo-preview");
}
```

I've put a breakpoint at the first statement. When there is a page cached, I can see two renders:
1. when the page starts navigating, this would be the preview, but `isPreview` is false
2. when the page finishes navigating (after the progress bar + network request), and `isPreview` is false (as expected).

From the code, I think this is a bug, or I have missed additional instructions to enable the preview.
- No `no-preview` set (I would not expect the first render to begin with)
- No other options set via data-attributes. Just regular turbo-driven link to a cached page.

Is there anything I can provide to aid with determining what the issue is?

**Comment by SleeplessByte** [comment]
Tracked by https://github.com/hotwired/turbo/issues/159; should be fixed by https://github.com/hotwired/turbo/pull/162 and https://github.com/hotwired/turbo/pull/169.

This issue can be closed when released.

**Comment by dhh** [comment]
Closing as its tracked at the source.
