### ISSUE TITLE
broadcast_render_later_to not working after_destroy_commit

### ISSUE THREAD

**Issue by culov** [hotwired/turbo-rails#132]
Hi,

I prefer using `broadcast_render_later_to` to render a stream from a `turbo_stream` file rather than broadcasting each update individually from my model.

It works great `after_update_commit` or `after_create_commit`, but trying `broadcast_render_later_to` from `after_destroy_commit` produces an error because `broadcast_render_later_to` appears to invariably try to serialize the `self`  object, which in the case of `after_destroy_commit` no longer exists.

Is there a better way to render turbo_stream files following a `after_destroy_commit` event?

**Comment by dhh** [comment]
You can still use `broadcast_render_later_to`, you just can't refer to the record you just destroyed. Either way, please use the https://discuss.hotwire.dev site for usage questions ✌️
