### ISSUE TITLE
Allow turbo responses within frames to break out of the frame dependent on success/failure

### ISSUE THREAD

**Issue by simmerz** [hotwired/turbo-rails#133]
My use case:

I have a form in a modal (don't judge me). I would like to submit the form, but there are validation errors with the submission, so I want to replace the form in the modal with one containing error messages.

Now I submit again, but this time I've fixed my validation issues and the response should redirect the entire page to a new url.

I'm using a `<turbo-frame id="modal">` to contain the modal, and for the errors, `<form data-turbo-frame="modal">` works brilliantly, but it would be great if I could determine different outcomes depending on the success of the submit.

I had some thoughts around whether adding other data-* attributes would work as a potential solution here. Eg `data-turbo-frame-failure` and `data-turbo-frame-success` might be used to direct the response at different targets depending on the result of the request.

**Comment by jon-sully** [comment]
🤔 just a thought here, but have you tried setting the target on the _frame_ to `_top`? A successful form submit from within the frame should come back with a `30x` status and the frame having a `_top` target should force the redirect to be assessed on the full page rather than just the frame

**Comment by simmerz** [comment]
@jon-sully my experience has been that if I set the target on the frame to `_top`, then both 30x and 40x responses result in the page being replaced, not just the form frame. Perhaps I'm missing something critical though!

**Comment by jon-sully** [comment]
Well hello to my old self! Time flies. Can you read up on https://github.com/hotwired/turbo/pull/210 and https://github.com/hotwired/turbo/issues/138 to see if the latter encompasses your issue and indeed the former will fix it?

**Comment by dhh** [comment]
Being addressed on the turbo repo.
