### ISSUE TITLE
UJS double-click protection does not function when submitting a form that loads a turbo-frame

### ISSUE THREAD

**Issue by jthornhill** [hotwired/turbo-rails#135]
Hello, and thank you all for this excellent project!

I'm finding that if I create a form inside of a turbo-frame (or if I reference a turbo-frame using the data-turbo-frame attribute on a form element) I lose the data-disable functionality traditionally provided by UJS. I believe this is supposed to work (per https://github.com/hotwired/turbo/issues/55 and also per the [README](https://github.com/hotwired/turbo-rails#compatibility-with-rails-ujs)) but I'm having no luck with it.

I am using webpacker + turbo-rails + @hotwired/turbo-rails@^7.0.0-beta.5 (this is what you get following the documentation with a 'rails new'). I've created a demo project that demonstrates this behavior: https://github.com/jthornhill/data-disable-test

If you view the /demos index, and use the inline form, turbo submits the request and receives the response, replacing the content of "coolframe" as I'd expect. However, the submit button does not become disabled.

If I remove the turbo frame element, then button is disabled in the same way I expect from earlier versions of rails UJS.

If I've missed something in the docs that explains how to do this, I apologize. I'm new to Turbo but very excited to migrate to it!

**Comment by kirillplatonov** [comment]
Check out this PR: https://github.com/hotwired/turbo-rails/pull/93

I added the following code to `app/javascript/packs/application.js` and disable-with works inside turbo frames now.
```javascript
import Rails from "@rails/ujs"

Rails.start()

Rails.delegate(document, Rails.linkDisableSelector,   "turbo:before-cache", Rails.enableElement)
Rails.delegate(document, Rails.buttonDisableSelector, "turbo:before-cache", Rails.enableElement)
Rails.delegate(document, Rails.buttonDisableSelector, "turbo:submit-end", Rails.enableElement)

Rails.delegate(document, Rails.formSubmitSelector, "turbo:submit-start", Rails.disableElement)
Rails.delegate(document, Rails.formSubmitSelector, "turbo:submit-end", Rails.enableElement)
Rails.delegate(document, Rails.formSubmitSelector, "turbo:before-cache", Rails.enableElement)
```

**Comment by coorasse** [comment]
I still have an issue when the form is nested under a turbo-frame and has `method=get`. 
In this case the `turbo:submit-start` event is not triggered and the data-disable-with is not working.

**Comment by dhh** [comment]
Please open a new issue with a minimum reproduction case 🙏
