### ISSUE TITLE
Disable Turbo Drive by default

### ISSUE THREAD

**Issue by gregschmit** [hotwired/turbo-rails#139]
In my project, I import Turbo (via Webpacker) like this:

    import "@hotwired/turbo-rails";

For reasons (it breaks my existing Vue.js stuff), I want to disable Turbo Drive. So I added `data-turbo="false"` to my `<html>` tag in my layout. But for another project, that's kinda cumbersome (and in my scenario, there are customer-written layouts and I don't want them to have to worry about stuff like that).

Is there a way to disable Turbo Drive entirely? Either via a Rails initializer configuration, or by replacing the import with a set of import statements that import all the components separately? Or perhaps a variable I can set or a JS statement I can make before/after Turbo is imported?

**Comment by gregschmit** [comment]
I think I figured out how to disable this behavior by default:

```
Turbo.navigator.delegate.elementIsNavigable = function(element) {
  const container = element === null || element === void 0 ? void 0 : element.closest("[data-turbo]");
  if (container) {
    return container.getAttribute("data-turbo") == "true";
  } else {
    return false;
  }
}
```

I wonder if this could either be documented or perhaps added as a feature (not too sure how the user would set this behavior). Would you accept a PR to document this feature so users may opt-out of Drive?

**Comment by dhh** [comment]
Further discussions in PRs.
