### ISSUE TITLE
Best practices to create multiple models and not stream them all

### ISSUE THREAD

**Issue by igorkasyanchuk** [hotwired/turbo-rails#140]
Hello,

I have a question to know regarding best practices how to fix one strange behavior.
I'll make a very simple example

```ruby
class Post < AR
   broadcasts
end
```

I've an UI page where I'm showing 6 last topics.

```ruby
class PostController
   def index
      @posts = Post.limit(6)
   end

   def sync
     LoadPostsJob.perform_now
   end
end
```

```ruby
class LoadPostsJob
   def perform
      # IMPORTANT
      # this API will return 10 records
      #
      JSON.parse("SOME_POSTS_API").each do |raw|
         # basically create or update existing records
         Post.find_or_create_by_raw_data(raw)
      end
   end
end
```

And imaging I'm starting new job in background `LoadPostsJob.perform_now` and it will create/update 10 posts. But on page I'm showing only 6.

I've noticed that once Post created/updated in job it will try to broadcast rendered partial to **clients".

BUT I've opened page with only 6 records and I'm the only one visitor on the site.

So my question is - IS IT correct behavior? If we don't have a client who is subscribed for updates for Post which is created/updated in background job? For me it looks like not needed operation which consumes system resources. Maybe it's possible if there is a "connected" client(s)?

**Comment by dhh** [comment]
Please use https://discuss.hotwire.dev for help with usage.
