### ISSUE TITLE
turbo does not render properly css in form: selectizejs choicesjs

### ISSUE THREAD

**Issue by lf2foce** [hotwired/turbo-rails#144]
turbo_frame_tag does not render properly css in select multiple form: selectizejs choicesjs.
I find it works perfectly with turbolink when specify: document.addEventListener("turbolink:load", ....
But not the case in turbo:load
Please take a look at this problem, thank you.

**Comment by dhh** [comment]
Not enough here to follow up on. If you want to take a stab at fixing this, please open a PR.
