### ISSUE TITLE
using dom_id as a stream target

### ISSUE THREAD

**Issue by scottbarrow** [hotwired/turbo-rails#146]
given a frame target 
```ruby
<%= turbo_frame_tag dom_id(order, :some_prefix) do %>
...
<% end %>
```

```ruby
     broadcast_replace_to [order, :order_index_invoice_stream],
                          target: :order_index_invoice_frame,
                          target: dom_id(order, :some_prefix),
                           partial: 'orders/index/seller/shared/invoice_button',
                           locals: { order: order }
```

the target will stream back over ws with target: '#some_prefix_order_123' whereas it seems turbo expects the target to not have a prepended '#' and expects 'some_prefix_order_123' in order the match the frame id

**Comment by dhh** [comment]
`dom_id` returns a hash-prefixed dom id. You'll need to produce one without.

**Comment by scottbarrow** [comment]
`dom_id` is a particularly useful method to use as keys for frames as per above example, furthermore id's are hash-prefixed in the dom.
would you not feel it valuable to have turbo js expect targets to include hashes or at least check for the inclusion of one in the target value?
I'm happy to open a PR if so.

**Comment by dhh** [comment]
I'd take a patch in turbo-rails where we strip the # to make it easily compatible, if it doesn't muck things up too much 👍

**Comment by julianrubisch** [comment]
was this ever resolved? I just hit it and wondered whether it could be helped by making this method:

https://github.com/hotwired/turbo-rails/pull/230/files#diff-7ae30f9728dbc55c647e054123259e03a5128b7ec25c9161d11dec00f3257e60R25

public, or use it to patch `dom_id`?

**Comment by dhh** [comment]
Was not resolved. That commit is for `targets`. We need a fix for `target`, where the # is stripped if passed.

**Comment by julianrubisch** [comment]
thanks, will give it a try

**Comment by seanpdoyle** [comment]
I'm not sure what's the root cause here, [dom_id](https://edgeapi.rubyonrails.org/classes/ActionView/RecordIdentifier.html#method-i-dom_id) doesn't prefix its return value with `#`:

```ruby
    # The DOM id convention is to use the singular form of an object or class with the id following an underscore.
    # If no id is found, prefix with "new_" instead.
    #
    #   dom_id(Post.find(45))       # => "post_45"
    #   dom_id(Post.new)            # => "new_post"
    #
    # If you need to address multiple instances of the same class in the same view, you can prefix the dom_id:
    #
    #   dom_id(Post.find(45), :edit) # => "edit_post_45"
    #   dom_id(Post.new, :custom)    # => "custom_post"
    def dom_id(record, prefix = nil)
      if record_id = record_key_for_dom_id(record)
        "#{dom_class(record, prefix)}#{JOIN}#{record_id}"
      else
        dom_class(record, prefix || NEW)
      end
    end

  private
    # Returns a string representation of the key attribute(s) that is suitable for use in an HTML DOM id.
    # This can be overwritten to customize the default generated string representation if desired.
    # If you need to read back a key from a dom_id in order to query for the underlying database record,
    # you should write a helper like 'person_record_from_dom_id' that will extract the key either based
    # on the default implementation (which just joins all key attributes with '_') or on your own
    # overwritten version of the method. By default, this implementation passes the key string through a
    # method that replaces all characters that are invalid inside DOM ids, with valid ones. You need to
    # make sure yourself that your dom ids are valid, in case you overwrite this method.
    def record_key_for_dom_id(record) # :doc:
      key = convert_to_model(record).to_key
      key ? key.join(JOIN) : key
    end
```

**Comment by julianrubisch** [comment]
fwiw, if I actively call `ActionView::RecordIdentifier.dom_id` in my controller, it doesn't prefix it. If I just call `dom_id`, it does.

**Comment by seanpdoyle** [comment]
Thanks @julianrubisch! Could you call method(:dom_id).source_location from your controller and share it here? I'm curious where that version is defined?

**Comment by julianrubisch** [comment]
ah dammit... just this second I recognized how stupid I am 🙈... forget everything I said 😅

**Comment by julianrubisch** [comment]
for posterity, and @scottbarrow : It's CableReady that's at fault here.
