### ISSUE TITLE
Problem adding import statement to packs/application.js

### ISSUE THREAD

**Issue by arusa** [hotwired/turbo-rails#148]
Running `rails turbo:install` printed the error:
```
File unchanged! The supplied flag value not found!  app/javascript/packs/application.js
```

The following line wants to add the import statement before: /import.*ActiveStorage/

https://github.com/hotwired/turbo-rails/blob/fec33d9bc767aec612b283620d2a74e78c1f90ae/lib/install/turbo_with_webpacker.rb#L8

In my application.js, that should be default Rails 6, there is no `import.*ActiveStorage`, there is only  `require("@rails/activestorage").start()`

I'm not sure if the require statement for @rails/activestorage should be changed to some kind of import-statement?

Or maybe the turbo_with_webpacker.rb should be changed to also try finding the require*activestorage line?

**Comment by jasonfb** [comment]
try building a fresh new rails app 6.1.3 (like a playground), go into that brand new app's app/javascript/packs/application.js file, then copy & paste the entire file into your own file (same location), completely replacing all of the contents. 

Then re-run the `rails turbo:install` and see if it goes through cleanly. also try seeing what lines of code it adds (examine with git), revert back to your app code, and add those lines of code yourself.

**Comment by arusa** [comment]
I have already solved the problem. I just wanted to mention this issue and find out if it is really intended this way.

I followed your suggestion to find out how a rails 6.1.3 app writes the application.js file:

```
import * as ActiveStorage from "@rails/activestorage"
...
ActiveStorage.start()
```

but in Rails 6.0 it was:

```
require("@rails/activestorage").start()
```

But I think during the upgrade path from 6 to 6.1 this change doesn't get suggested anywhere. So maybe it would be nice to also support the older variant?

The only solution that comes to my mind right now is to write two `insert_into_file` lines, but that would mean that one of them will always fail, which will look like a problem to the user:

```
 insert_into_file "#{Webpacker.config.source_entry_path}/application.js", "import \"@hotwired/turbo-rails\"\n", before: /import.*ActiveStorage/ 
 insert_into_file "#{Webpacker.config.source_entry_path}/application.js", "import \"@hotwired/turbo-rails\"\n", before: /require.*activestorage/ 
```

You could grep application.js in a condition to find out which `insert_into_file` statement to use.

**Comment by dhh** [comment]
Feel free to explore a grep-based approach in a PR to alter between the two styles. It might still not catch it every time, since the user might have changed the file anyway. Another approach could be to simply catch any failure and tell the user to manually make the changes. Also open for a PR doing that.
