### ISSUE TITLE
[cable.js] getConsumer() may create multiple consumers during the initial page load

### ISSUE THREAD

**Issue by palkan** [hotwired/turbo-rails#149]
I noticed that every `turbo-cable-stream-source` (well, I have only 2) initiates its own `/cable` connection. It's reproducible in 100% cases.

It seems that there is a _race condition_ in `getConsumer()`: since `createConsumer`, it might be in the pending state when we call `getConsumer()` for the second time.

I think, memoizing the promise itself should resolve this.

**Comment by javan** [comment]
Thanks for the report! This was fixed in https://github.com/hotwired/turbo-rails/commit/69865446214605986149b1579b5f02e3d71cfd63, but hasn’t been published yet. I’ll cut a new release soon.

**Comment by palkan** [comment]
Yeah, that works! Thanks!
