### ISSUE TITLE
rails hotwire:install fails if views/application.html.erb doesn't exist

### ISSUE THREAD

**Issue by renevanpelt** [hotwired/turbo-rails#151]
Running 

`rails hotwire:install`

Gets me this error:

`Thor::Error: The file /Users/renevanpelt/rails/auction_saas/app/views/layouts/application.html.erb does not appear to exist
`

Some users use layouts with a different name, and some users don't use erb. So might be worth looking at!

Looking forward to trying hotwire!

**Comment by cpanderson** [comment]
Yes, had to put a dummy layout in so it could complete. Be nice to have it spit out the required changes like stimulus does.

**Comment by dhh** [comment]
Fixed in 750abe0aaf3b8ea84d78301647fcab2c1b6f0540.
