### ISSUE TITLE
hash key "channel" is not a Symbol

### ISSUE THREAD

**Issue by ryanwood** [hotwired/turbo-rails#154]
When running on `main` (fec33d9bc767aec612b283620d2a74e78c1f90ae) I get the error `hash key "channel" is not a Symbol` using this code in a view:

`<%= turbo_stream_from @package %>`

I think it's from https://github.com/hotwired/turbo-rails/commit/864a9b92cdc9c75d321a2eda369e6f79e71f4511 where the keys were changed from symbols to strings.

Happy to do a PR to change them back to symbols but want to check with @javan first to see if that was intentional.

**Comment by dhh** [comment]
What object is @package? If you're not passing a string, the object is meant to respond to to_gid_param or to_param. Both of which return strings. https://github.com/hotwired/turbo-rails/blob/main/app/channels/turbo/streams/stream_name.rb#L21
