### ISSUE TITLE
Turbo is not defined when trying to call `Turbo.visit`

### ISSUE THREAD

**Issue by brunofrank** [hotwired/turbo-rails#160]
Hey everyone,

I also using Turbo with `Assets pipeline` and facing the same error of issue #79.

Turbo is declared on `importmap` and I added it on the the template with

```
<%= javascript_include_tag "turbo", type: "module-shim" %>
``` 

In my controller I did
```
import { Controller } from 'stimulus'
import { Turbo } from 'turbo'

class ListController extends Controller {
  static targets = ['items', 'massActionsContainer', 'uniqueActions']

  connect() {
    this.hideMassActionsContainer()
  }

  edit(evt) {
    const editUrl = evt.target.dataset['editUrl']
    Turbo.visit(editUrl)
  }
```

When I import Turbo inside the controller it stops working because it loads turbo twice, because `javascript_include_tag` loads a different file.
![image](https://user-images.githubusercontent.com/40139/114306257-c5010780-9ab1-11eb-9922-abb19e357ee7.png)

My solution was to create another file `application_module.js` loading turbo

```
import { Turbo } from 'turbo'
window.Turbo = Turbo
```
and adding this file to my `application.html.erb` solve the problem.

```
    <%= javascript_include_tag 'application_module', type: 'module-shim' %>
```

**Comment by tiagogeraldi** [comment]
I couldn't reproduce it. I keep seeing `turbo is not defined`. Also trying with assets pipeline.
What other head entries do you have in your `application.html.erb` ?

**Comment by brunofrank** [comment]
Just application, did you fix that?

**Comment by dhh** [comment]
Latest Turbo now sets window.Turbo directly.
