### ISSUE TITLE
what makes turbo-rails silently fail on forms

### ISSUE THREAD

**Issue by jasonfb** [hotwired/turbo-rails#168]
---
unfortunately, after working on this a lot I was not able to create a reproduction app

strangely I can reproduce the issue in my own app but on my reproduction app the original symptom is not there. 

here is my reproduction app…

https://github.com/jasonfb/TR006
for testing this yourself
open rails console
```
10.times.do ; Abc.create; end
```

Then open up the app in your browser and go to `/abcs`

What is interesting is that I am intentionally trying to break it here : 

https://github.com/jasonfb/TR006/blob/main/app/controllers/abcs_controller.rb#L27

```
  
   respond_to do |format|
      format.turbo_stream
      format.html { redirect_to get_emails_imports_path }
    end
  
```

is this the expected behavior fr update actions? Here I've noticed that the TURBO_STREAM is what is requested and that the 200 OK response work fine

![TR006 — fsevent_watch ◂ localhost:3000)  TR006  NVM_INC=:Users:jason: nvm:versions:node:v12 8 0:include:node rvm_bin_path=:User… 2021-04-22 18-11-39](https://user-images.githubusercontent.com/59002/115791539-967b0a80-a396-11eb-9352-e899bab17b1a.png)

![TR006 — fsevent_watch ◂ localhost:3000)  TR006  NVM_INC=:Users:jason: nvm:versions:node:v12 8 0:include:node rvm_bin_path=:User… 2021-04-22 18-11-50](https://user-images.githubusercontent.com/59002/115791547-9b3fbe80-a396-11eb-9820-e1928d9f181b.png)

The only issue I can find is that the flash message isn't flushed out in this scenario

![Screen Shot 2021-04-22 at 6 15 22 PM](https://user-images.githubusercontent.com/59002/115791682-de9a2d00-a396-11eb-89e2-7deb72e01d73.png)

![TR006 2021-04-22 18-15-27](https://user-images.githubusercontent.com/59002/115791691-e0fc8700-a396-11eb-9530-dd43175cd511.png)

![TR006 2021-04-22 18-15-55](https://user-images.githubusercontent.com/59002/115791697-e3f77780-a396-11eb-9aed-238e4932993e.png)

**Comment by jasonfb** [comment]
this was from another issue....

@dmitry-rychkov  commented 9 hours ago

@jasonfb, my observation is that when server response doesn’t contain any turbo-frame, then it responds with empty response even if you generate full HTML page.

When there is a turbo-frame in response HTML then whole HTML page is returned and turbo works fine.

I couldn’t find a line in Rails code which prevents normal HTML response when there is no frame inside.

Still don’t see any reason for Turbo forms not to allow same logic as links (without any UJS)

**Comment by jasonfb** [comment]
and finally, what's really getting me is that the flash message appears to not get flushed out of Rails (like in the old days when flash messages stuck around until the next page load)

which is REALLY weird, because I can see the flash message (the correct one) it in the response from the TURBO_STREAM request— but when I reload the page, the flash message is spit out again like it never got properly flushed. 

I'm on Rails `6.1.0`.

Would love to know what I'm not seeing here. Thanks in advance.

**Comment by jasonfb** [comment]
OK so with this guy I think the problem is that Rails is returning the whole layout — why does Rails return the whole layout?

I made a test app but it works as expected (so it's got to be something in my app) 
in my test app the turbo_stream response is very small— only the turbo replace commands:

![DevTools - 127 0 0 1:3000: 2021-04-20 18-16-10](https://user-images.githubusercontent.com/59002/115470596-93501500-a204-11eb-9931-17f96adfd0e2.png)


But in my regular app, which I just added Turbo to under Rails 6.1 I think, something is wrong with this.

in the buggy app (the one I'm stuck on), the Turbo stream response contains all of the HTML, but it comes out with the whole Rails layout, and those turbo frames just kind of come out where the yield would be:

![DevTools - 127 0 0 1:3000:dashboard: 2021-04-20 18-19-12](https://user-images.githubusercontent.com/59002/115470916-170a0180-a205-11eb-87e1-7d1a3a7a1941.png)


so… I'm fairly sure this is the locus of the problem, I just can't quite seem to nail it. Something is making Rails spit out the whole layout — isn't the expected result with a turbo_stream response only the tiny little bit of turbo replacement?

**Comment by jasonfb** [comment]
I think this is the crux of the problem for me

@henrik

![Screen Shot 2021-04-20 at 6 41 26 PM](https://user-images.githubusercontent.com/59002/115472562-20489d80-a208-11eb-96dd-04a10fdf4485.png)

**Comment by jasonfb** [comment]
I changed my response to this
```
   respond_to do |format|
      format.turbo_stream {render "update", status: 303}
    end
```
but it's doing the same thing… the whole Rails layout is rendered and nothing happens on my page.

**Comment by jasonfb** [comment]
getting closer…

*1.* as @henrik said above, the experience with forms is really, really a headscracher

you want to use the redirect method described (https://turbo.hotwire.dev/handbook/drive#redirecting-after-a-form-submission)[in the docs] or else you will be very lost:

```
 respond_to do |format|
      format.turbo_stream {redirect_to dashboard_get_emails_imports_path, status: 303}
    end
```

*2.* do not accidentally have a template called update.turbo_stream or else that'll get rendered

*3.*  *you can't nest turbo frames easily here*— in particular, my FORM was nested inside of two turbo frames

is this not allowed?
```
= turbo_frame_tag "ge_imports-list" do
   - ge_imports.each do |ge_import|
      = turbo_frame_tag "ge_import__#{ge_import.id}" do
          = form_for :ge_import, url: dashboard_ge_import_path(ge_import), method: "put" do |f|
             = f.hidden_field "_action", value: "reject"
             = f.submit "Reject",  disable_with: "Loading...", class: " btn btn-danger pull-right btn-sm"
```

basically, the form interaction was looking for the "closest" parent turbo frame ancestor--- any turbo frame ancestor. 

but my *response* actually doesn't need to contain that record (the one created by `= turbo_frame_tag "ge_import__#{ge_import.id}" do`), what I was trying to do was replace the whole list itself (which, as I want, has my record removed after the interaction)

**if I have the intermediary turbo_frame_tag (the one with the id of the record) it works to replace the page, but it gives a red error in JS 

![DevTools - 127 0 0 1:3000:dashboard:get_emails_imports 2021-04-20 19-07-44](https://user-images.githubusercontent.com/59002/115474599-c649d700-a20b-11eb-8a81-73f7e1675ab1.png)
**

In my case, this turbo frame it is complaining about WAS on the page, but is no longer on the page

I thought I could replace the whole list but i guess not? I guess I have to explicitly use the turbo_stream.remove against the frame I want to remove?

**Comment by henrik** [comment]
This one might be closer to support request than issue, but I'll leave that determination for the repo owners – the frustration is certainly real :)

I didn't dig deeply but wrote some small findings in https://github.com/hotwired/turbo-rails/issues/152#issuecomment-819694640. My assumption was that the docs are misleading and you can't actually expect to just use form submission redirects with Turbo Drive without also rewriting your app to use Turbo Frames (which I haven't tried). I'm not in any rush in this app and Turbo is explicitly in beta, so I figured I'd wait and see what comes of #122 – curious if it will be acknowledged as a bug, or a known limitation, or if it turns out to be user error.

**Comment by gharmonjr** [comment]
> My assumption was that the docs are misleading and you can't actually expect to just use form submission redirects with Turbo Drive without also rewriting your app to use Turbo Frames (which I haven't tried).

@henrik I've found that I can either do:
  - `config.load_defaults 6.1`
  Or
  - `config.action_view.form_with_generates_remote_forms = false`
in my `application.rb` 

Assuming I understand the problem you're running into this resolved the issue for me so I didn't have to retouch all the forms in my app.

**Comment by henrik** [comment]
@gharmonjr Thank you. My problem is that even with `remote: true` and a 303 redirect, nothing appears to happen – the page does not actually redirect when a form is submitted. This is me just attempting to use Turbo Drive, without explicitly doing anything for Turbo Frames.

**Comment by jasonfb** [comment]
@henrik  -- unfortunately, after working on this a lot I was not able to create a reproduction app; strangely I _can_ reproduce the issue in my own app but on this test little app I threw together trying to recreate the issue I can't re-create it

here is my reproduction app...

https://github.com/jasonfb/TR006

hopefully someone finds this useful as a playground for fiddling with Turbo-rails, but for now I will close.

**Comment by gharmonjr** [comment]
@jasonfb is this line different in your own app vs this reproduction app? 

https://github.com/jasonfb/TR006/blob/20cca24a3048e61eb8d49629f7de5ae14beb4fc5/config/application.rb#L12

**Comment by ookam** [comment]
@jasonfb I had the same problem. But I don't know if my problem and yours are the same.
In my case, it was due to the following. When the file name is "show.html.erb", it works exactly. However, when the file name is "show.erb", it will not work correctly.
Don't forget the ".html" in the file name. That will make the response header "Content-Type: text/html" and it will work properly.

**Comment by Signum** [comment]
> Don't forget the ".html" in the file name. That will make the response header "Content-Type: text/html" and it will work properly.

Thanks so much for mentioning that. I have been debugging my Rails application for three days straight now because button_to tags just did nothing. I renamed "show.slim" to "show.html.slim" and suddenly everything works. You are my personal hero!
