### ISSUE TITLE
Using turbo_stream_from on each page causes issues

### ISSUE THREAD

**Issue by sergey-koba-mobidev** [hotwired/turbo-rails#170]
Hello there!

I placed `<%= turbo_stream_from 'tasks' %>` in `layouts/application.html.erb`.
When I navigate to any page in the website it causes turbo to regenerate turbo-stream-from tag. 
Sometimes it sends unsubscribe and subscribe too fast, so that unsubscribe goes after subscribe and the channel never returns confirmation.
After several navigation jumps it starts to double-tripple incoming messages when it finally manages to subscribe and get confirmation.

Is there a way to subscribe to channel with `turbo_stream_from` and keep the connection stable during page navigations using Turbo?

Ruby 3.0.1
Rails 6.1.3.1
Hotwire rails 0.1.3

PS: This very dirty hack solves the issue completely...
```js
import { connectStreamSource, disconnectStreamSource } from "@hotwired/turbo"
import { subscribeTo } from "./cable"

class TurboCableStreamSourceElement extends HTMLElement {
  async connectedCallback() {
    connectStreamSource(this)
    const ctx = this
    setTimeout(async function(){
      console.log('subsribeTo in connectedCallback')
      ctx.subscription = await subscribeTo(ctx.channel, { received: ctx.dispatchMessageEvent.bind(ctx) })
    }, 500);
  }
//...
}
```

Thx

**Comment by dhh** [comment]
This is a general problem in Action Cable. Here's the patch that'll fix it: https://github.com/rails/rails/pull/41581
