### ISSUE TITLE
request.turbo_frame? instead of turbo_frame_request?

### ISSUE THREAD

**Issue by nfedyashev** [hotwired/turbo-rails#175]
A question for the Turbo Rails team: what do you think about replacing `#turbo_frame_request?` condition check in favor of `request.turbo_frame?`?

Would this be more consistent with Rails convenient naming of similar methods e.g. `request.get?`, `request.post?` etc? Or would be rather be too much magic/patching and you want to keep it as is?

Thanks

**Comment by dhh** [comment]
Too much magic, imo, for no big gain in readability.
