### ISSUE TITLE
BroadcastJob queue name

### ISSUE THREAD

**Issue by DLawla** [hotwired/turbo-rails#176]
Hi team,
I'd like to send our broadcast jobs to a higher priority queue than `default'
Are there any plans on opening some configuration for the default queue that `Turbo::Streams::BroadcastJob` uses?
Would you be accepting a PR for this?
Thanks!

**Comment by dhh** [comment]
You can just set the queue name directly on the class:

```ruby
>> Turbo::Streams::BroadcastJob.queue_name = "high"
=> "high"
>> Turbo::Streams::BroadcastJob.queue_name
=> "high"
```

**Comment by kwent** [comment]
I tried this without success.

I put it in a initializer

```ruby
# config/initializers/turbo.rb
Turbo::Streams::BroadcastJob.queue_name = "critical"
```

Still seeing

`
[ActiveJob] Enqueued Turbo::Streams::ActionBroadcastJob (Job ID: f0e14b9a-ae5c-4186-bca6-4da171459be0) to Sidekiq(default) with arguments:  ...
`

Any idea ?

**Comment by DLawla** [comment]
@kwent 

If it helps, our initializer has slightly different syntax:

```
# config/initializers/turbo.rb
Turbo::Streams::ActionBroadcastJob.class_eval do
  queue_as :broadcast
end
```

```
Enqueued Turbo::Streams::ActionBroadcastJob (Job ID: 310386c2-c659-437e-b7fe-c756cd71612c) to Sidekiq(broadcast) with arguments: ...
```

**Comment by kwent** [comment]
@DLawla Thanks your solution worked for me!
