### ISSUE TITLE
NPM Package Version Bug?

### ISSUE THREAD

**Issue by tleish** [hotwired/turbo-rails#181]
Are the `@hotwire/turbo` and `@hotwire/turbo-rails` packages supposed to share the same version of code?  Both are listed as `v7.0.0-beta.5`, but they are not using the same turbo version.

While [@hotwired/turbo-rails npm package](https://www.npmjs.com/package/@hotwired/turbo-rails) shows it as the version as [Release v7.0.0-beta.5](https://github.com/hotwired/turbo/releases/tag/v7.0.0-beta.5) (released Apr 13), the turbo version is [Release v7.0.0-beta.4](https://github.com/hotwired/turbo/releases/tag/v7.0.0-beta.4) (released Jan 29).  It's missing all the bug fixes in the [v7.0.0-beta.5 release](https://github.com/hotwired/turbo/releases/tag/v7.0.0-beta.5)

**Comment by tleish** [comment]
[@hotwired/turbo-rails/package.json](https://npm.runkit.com/@hotwired/turbo-rails/package.json?t=1623359862451)

```json
{
  "name": "@hotwired/turbo-rails",
  "version": "7.0.0-beta.5", <==

  "dependencies": {
    "@hotwired/turbo": "^7.0.0-beta.4", <==
    "@rails/actioncable": "^6.1.0"
  }
}
```

**Comment by marcelolx** [comment]
@tleish With the latest release this is fixed https://npm.runkit.com/@hotwired/turbo-rails/package.json?t=1623531401439
