### ISSUE TITLE
Turbo breaks one specific page... how to ensure full page load, on a per-link or per-page basis?

### ISSUE THREAD

**Issue by jpwynn** [hotwired/turbo-rails#182]
For the most part Turbo is working out of the box. (Rails 6.1.3.1 with hotwire, stimulus, tailwind, devise)

At issue is one page where the page "breaks" 100% of the time if I GET it via a link, but "works" 100% of the time if I GET the page _manually_ by typing the url or _manually_ refreshing the page after click a link to it. 

So a "full page load" 100% works vs. a "turbo-powered load" 100% breaks.

This one page contains a vendor's jquery widget (Ziggeo) and also loads jquery via a cdn link. (Tried adding the jquery stuff both in head or in body, same result.)

By "breaks" I mean: If I click an app link to the page, the jquery widget on the page does not get initialized and sometimes jquery doesn't even load. (But works after a manual page load or reload.)

Is here any way - for a specific page - to ensure it always gets a _full_ page load? 

(Perhaps some change in a custom layout, or in the regular application layout, or in the link_to the page?)

**Comment by tleish** [comment]
There are several options.

1. Disable turbo on any links or forms which open the page you want a full page load. 
see [Disabling Turbo Drive on Specific Links or Forms](https://turbo.hotwire.dev/handbook/drive#disabling-turbo-drive-on-specific-links-or-forms)
2. If using webpacker, wrap jQuery and jQuery widget inside a stimulus controller.
see: [Dynamic module import  with Stimulus JS](https://dev.to/adrienpoly/dynamic-module-import-with-stimulus-js-297g)

**Comment by jpwynn** [comment]
Thank you, option 1 looks perfect, in particular being able to make a full page load _page specific_ by simply adding 

```
<meta name="turbo-visit-control" content="reload">
```

to the head for the page for this specific use case (" third-party JavaScript libraries that don’t interact well with Turbo Drive page changes")
