### ISSUE TITLE
Regression in setting local variables that are passed to partial

### ISSUE THREAD

**Issue by jcoyne** [hotwired/turbo-rails#186]
This commit introduced a regression where it removed the reverse_merge that added a entry to the locals hash with the model name as the key:

https://github.com/hotwired/turbo-rails/commit/1864ed36e43ba3ae7028a9bde104a4c59107def3

I had been using a partial that had been depending on a local variable with that name. 

This change causes the code path to change in: https://github.com/rails/rails/blob/main/actionview/lib/action_view/renderer/renderer.rb#L74-L82
And then the value that I explicitly set is overwritten here: https://github.com/rails/rails/blob/main/actionview/lib/action_view/renderer/object_renderer.rb#L30

The use case I have is a model called Collection invokes the following code:
```ruby
    broadcast_replace_to self, :details, partial: 'collection_versions/collection_version',
                                         locals: { collection_version: head, collection: self }
```

And the effect is that `locals[:collection_version]` is no longer set to `head`, but to `self`

I would say that it's surprising to the user that the context in which `broadcast_replace_to` is called governs which locals can be set.

**Comment by dhh** [comment]
Ah, I see. Thanks for digging into this further. Do you want to take a swing at a fix?

**Comment by kwent** [comment]
Adding my test failing here for more context:

```
ActionView::Template::Error: undefined local variable or method `article' for #<ActionView::Base:0x0000000004b8e8>
/home/my_app/app/views/account/articles/_article_row.html.erb:1:in `_app_views_account_articles__article_row_html_erb___6520840233687197_154720'
```

with `article_row.html.erb`

```erb
<tr id="<%= dom_id(article) %>">
  <td><span class="badge badge-warning"><%= article.title %></span></td>
</tr>
```

article.rb

```ruby

class Article < ApplicationRecord

  after_create_commit lambda { |article|
    broadcast_prepend_to broadcast_stream_keys(article)
  }

  after_update_commit lambda { |article|
    broadcast_replace_to broadcast_stream_keys(article)
  }

  after_destroy lambda { |article|
    broadcast_remove_to broadcast_stream_keys(article)
  }

protected

  def broadcast_stream_keys(article)
    [article.team, :articles]
  end

  def broadcast_target_default
    model_name.plural
  end

  def to_partial_path
    'account/articles/article_row'
  end

end
```

Hope this help!

**Comment by jcoyne** [comment]
@dhh My first suggestion would be to revert 1864ed3.   Is that tenable?

**Comment by dhh** [comment]
@jcoyne The original issue still needs fixing. So have to find a way to sort both.

**Comment by jcoyne** [comment]
Okay, I can take a look at that.

**Comment by jcoyne** [comment]
@dhh It looks to me that the model name conversion was working just fine. It was using `users_profile`:

```
@profile.model_name
#<ActiveModel::Name:0x00007fea3edb17a0 @name="Users::Profile", @klass=Users::Profile, @singular="users_profile", @plural="users_profiles", @element="profile", @human="Profile", @collection="users/profiles", @param_key="users_profile", @i18n_key=:"users/profile", @route_key="users_profiles", @singular_route_key="users_profile">
```

where as @ryanwood (author of #109) was expecting it to be `profile`.  It seems to me that the right thing to do would have @ryanwood modify his partial to use `users_profile` or to have explicitly passed: `locals: { profile: self }`

**Comment by dhh** [comment]
Hmm, now I just looked at all the original issues. I think what we have now is correct. It's definitely a change in behavior, but now that behavior matches what Action View normally does.

I think what you need to do here is to supply that object overwrite yourself, so it's:

```ruby
    broadcast_replace_to self, :details, partial: 'collection_versions/collection_version',
                                         object: head, locals: { collection: self }
```

**Comment by dhh** [comment]
OR we could look into not automatically setting object if partial is passed in manually.

**Comment by jcoyne** [comment]
@dhh let me know if you'd prefer #187 or if you would prefer we do a check for `partial` being passed in.

**Comment by dhh** [comment]
No that one was great. Thanks for finding and fixing this 🙏. Will do a release as soon as I have a new turbo ready to go.
