### ISSUE TITLE
Time.zone not working

### ISSUE THREAD

**Issue by alexroitman** [hotwired/turbo-rails#189]
Im currently working on a feature that broadcast a notification(a view) using `broadcast_replace_to`

In my model:
```ruby
    def broadcast_alert
        broadcast_replace_to user_id, :stream_id, target: :target_id
    end
```

and in my view i render some user information and more specific a schedule. So when type:
`time_to_format(schedule)`
NOTE: time to format is a helper that encapsulates `I18n.localize(time, options)` with styles and `schedule` is a `datetime` 

it returns me me in the schedule in UTC(thats correct), but even i set:
```ruby
  Time.use_zone(time_zone) do
    time_to_format(schedule)
  end
```

or in the debugger console:
```ruby
> Time.zone = time_zone
> time_to_format(schedule)
```

it returns the schedule in UTC.
The only way i make it work is setting `time_to_format(schedule.in_time_zone(time_zone))` each time i want to use a datetime.
Any solution?

**Comment by ghiculescu** [comment]
Where is the `time_zone` coming from in your views?
