### ISSUE TITLE
Missing a controller-like layer when using `Turbo::Broadcastable`

### ISSUE THREAD

**Issue by Alexey1100** [hotwired/turbo-rails#190]
Take this example:
```ruby
class Clearance < ApplicationRecord
  belongs_to :petitioner, class_name: "Contact"
  belongs_to :examiner,   class_name: "User"

  after_create_commit :broadcast_later

  private
  
    # Sends <turbo-stream action="replace" target="clearance_5"><template><div id="clearance_5">Other partial</div></template></turbo-stream>
    # to the stream named "identity:2:clearances"
    def broadcast_later
      broadcast_replace_later_to examiner.identity, :clearances, target: self, partial: "clearances/other_partial", locals: { clearance: self }
    end
end
```

We are scheduling a job to render the template and broadcast it later.
Overall it’s pretty similar to the way we send emails, right?
However for the emails we have an `ActionMailer` which acts as a controller layer and initialises the objects before passing to views.

Here we don’t have any intermittent layer, so the background job just loads the objects from database and passes them directly to views, leaving us without an option to modify or set up the objects before rendering, e.g. apply a decorator.

So I’m wondering if there were already any thoughts on implementing something like a Broadcaster layer, similar to Mailer?

**Comment by dhh** [comment]
The job enqueued by broadcast_replace_later_to is incredibly simple: https://github.com/hotwired/turbo-rails/blob/main/app/jobs/turbo/streams/broadcast_job.rb. It's very easy just to setup your own job with custom handling. Don't think we need a separate controller layer here on top.

**Comment by Alexey1100** [comment]
@dhh thanks for the reference :)
Sure, we can always customize the job.

I was just wondering if there any thoughts on more structured approach, given this is very early days of Hotwire itself and the rails integration in particular.
