### ISSUE TITLE
Turbo doesn't work with webpacker 6 pre2

### ISSUE THREAD

**Issue by mattszein** [hotwired/turbo-rails#191]
Hi. I follow the video example on hotwire page but only with webpack (without sprockets) and turbo doesn't load.
I install webpacker 6 version pre-2 and turbo-rails.

I upload an example:
https://github.com/mattszein/rails-example-webpacker/

I don't know what is the problem.

**Comment by t27duck** [comment]
Webpacker 6 pre2 is a really really old release. The more current one of 6 is beta7.

**Comment by mattszein** [comment]
> Webpacker 6 pre2 is a really really old release. The more current one of 6 is beta7.

Updated to beta7 and it's the same. Turbo doesn't load.

**Comment by mattszein** [comment]
> Webpacker 6 pre2 is a really really old release. The more current one of 6 is beta7.

yes, it works with beta7. I don't know why, when I was trying to update to beta7, gemfile.lock was not updated and I needed to fix it manually.
