### ISSUE TITLE
Website in the right column of this repo is wrong

### ISSUE THREAD

**Issue by pruzicka** [hotwired/turbo-rails#199]
![image](https://user-images.githubusercontent.com/225397/124439591-e3f1fb80-dd79-11eb-9b82-e7b6af3fe54a.png)

There is a typo, shouldn't it be "turbo.hotwire**d**.dev"?

**Comment by strobilomyces** [comment]
Worked yesterday. I don't think it's a coincidence that it's forwarding to the Anti-Defamation League.

**Comment by Nodalailama** [comment]
Popcorn, the political drama is on.
