### ISSUE TITLE
Why is there no `Turbo::StreamsChannel.broadcast_update_to`

### ISSUE THREAD

**Issue by efatsi** [hotwired/turbo-rails#204]
The `update` action is unavailable when broadcasting stream actions via websockets. It's possible to workaround by using `replace` instead (and configuring partials accordingly), but is it possible instead to add `broadcast_update_to` to this [`Turbo::Streams::Broadcasts`](https://github.com/hotwired/turbo-rails/blob/main/app/channels/turbo/streams/broadcasts.rb#L12-L14)?

**Comment by efatsi** [comment]
I've added this to an initializer in my project to kick the tires on using this method:
```rb
# config/initializers/monkey_patches.rb

module StreamsChannelExtensions
  def broadcast_update_to(*streamables, target:, **rendering)
    broadcast_action_to *streamables, action: :update, target: target, **rendering
  end
end

Turbo::StreamsChannel.extend(StreamsChannelExtensions)
```

**Comment by dhh** [comment]
Feel free to add a PR for this 👍
