### ISSUE TITLE
Upgrade UJS with RSpec

### ISSUE THREAD

**Issue by kwhandy** [hotwired/turbo-rails#207]
I just  generate new app but moved from default test(minitest) to RSpec, then I figure out that there is some folder needed if I want to implement [turbo_assertations_helper.rb](https://github.com/hotwired/turbo-rails/blob/main/UPGRADING.md) means I need to use the minitest instead RSpec. How to solve this?

**Comment by dhh** [comment]
Please use https://discuss.hotwired.dev for usage questions.
