### ISSUE TITLE
DoubleRenderError When returning turbo_stream from controller

### ISSUE THREAD

**Issue by acetinick** [hotwired/turbo-rails#208]
Hi,  

I am getting this error when trying to simply return the stream stream from controller. From the examples I read, it should work.  Is there something I am missing?

If I put the same code in its own create.turbo_stream.erb file, then it will work fine, but it won't from controller.

![rubymine64_UW2N5Im1tc](https://user-images.githubusercontent.com/571649/126879869-a7b117b3-29a0-478b-81e2-60dd02483fbc.png)

 `AbstractController::DoubleRenderError - Render and/or redirect were called multiple times in this action. Please note that you may only call render OR redirect, and at most once per action. Also note that neither redirect nor render terminate execution of the action, so if you want to exit an action after redirecting, you need to do something like "redirect_to(...) and return".:`

**Comment by tleish** [comment]
What does the rest of your controller look like?  Are there any before/after filters in this controller or a parent controller?  

What does the partial look like?

**Comment by acetinick** [comment]
Ahh you made me look deeper into my base ApplicationController and finally saw the issue!  Thanks!

In my ApplicationHelper I had the the following lines added,  and when I removed it worked again.  Not too sure how they got there, but after everything seems to be working 

![rubymine64_YSqhFl8UZ6](https://user-images.githubusercontent.com/571649/127025235-db56a480-c5e4-4d66-9e95-4ede9602576f.png)
