### ISSUE TITLE
Support additional attributes in Turbo::Streams::TagBuilder

### ISSUE THREAD

**Issue by defsdoor** [hotwired/turbo-rails#212]
Would be useful to support additional attributes to be specified and included in the Turbo::Streams::TagBuilder helper

Would be consistent with other tag helpers that allow similar abilities - 

<turbo-stream action="replace" targets="message_1" **effect="flash"**>

**Comment by dhh** [comment]
What would be picking up or reacting to these attributes?

**Comment by defsdoor** [comment]
Personally, I've added additional handlers in a turbo:before-stream-render event handler, which is why I originally thought this would be useful.

However, I've subsequently refactored what I was doing so that I have a additional turbo-steam/action instead (mostly because of the changes that allowed targetting non-frames and by class selectors).

I do still think that this helper method is at odds with most other tag helpers in not supporting additional attributes, but I guess that that is because its intended as a slim helper for non-rails use of turbo more than anything else, and I guess it's just as easy to use 
```
tag :turbo_stream, action: "whatever", another_option: "dance" do
```
if you want to do anything adventurous.

**Comment by dhh** [comment]
Yeah, I think it's better to discourage that pattern, while of course having it available as an option by hand.
