### ISSUE TITLE
Activate script tags from turbo frames

### ISSUE THREAD

**Issue by parvesh-hyperiq** [hotwired/turbo-rails#214]
Scripts are evaluated in turbo frame response, I have checked it is done in Turbo already with following PR when we can have this in turbo rails

https://github.com/hotwired/turbo/pull/192

**Comment by defsdoor** [comment]
It's already there.  

https://github.com/hotwired/turbo-rails/blob/1e5ce6683c842f747758992b70c059a339c4dd27/app/assets/javascripts/turbo.js#L1048-L1057

Are you getting your Gem from github ?

`gem 'turbo-rails', git: "https://github.com/hotwired/turbo-rails", branch: 'main'
`
