### ISSUE TITLE
turbo_stream_from is not broadcasting on Brave web browser.

### ISSUE THREAD

**Issue by sadiqmmm** [hotwired/turbo-rails#220]
I have opened **three web browsers** (Chrome, Firefox and Brave).
turbo_stream_from is not broadcasting on **Brave** web browser.

More importantly, the broadcasting message is not getting 
delivered to other web browsers as well, like (Chrome, Firefox).

After close the brave browser window, messages are getting delivered instantly to
Chrome and Firefox.

Without opening the Brave browser with the turbo_stream_from URL, 
messages are getting delivered instantly to Chrome and Firefox.

**Comment by dhh** [comment]
You sure you have Redis turned on in development?

**Comment by sadiqmmm** [comment]
I have set up the test project.
[https://chat.azadlabs.com/rooms/1](https://chat.azadlabs.com/rooms/1)
Open it in Chrome, Firefox, and Brave.
Brave is giving the trouble.

When the Brave browser is opened, Firefox and Chrome also not getting the Broadcasted message.
Once, I only close the Brave Browser. Chrome and Firefox getting the Broadcasted message instantly.

**Comment by dhh** [comment]
Not sure it's necessarily Brave. It might be that Redis is not configured, thus you're relying on in-memory message passing, which won't work across processes. Either way, we use standard web sockets. If it works in Chrome, it's not a Rails issue. Feel free to discuss usage at discuss.hotwired.dev 👍
