### ISSUE TITLE
Adding test assertions for turbo frame?

### ISSUE THREAD

**Issue by shouichi** [hotwired/turbo-rails#246]
This is a feature request of adding test assertions for turbo frame to `Turbo::TestAssertions`. It currently has assertions for turbo stream. It might be convenient if there are assertions for turbo frame too. For example,

```
def assert_turbo_frame_tag(id)
  assert_select "turbo-frame#{id}", count: 1
end
```

Thanks!

**Comment by dhh** [comment]
Not a big fan of assertions like this that don't solve a difficult assertion problem that can't be solved with the basic ones. We used to have dozens and dozens in Rails. It was a mess and harder to remember. Appreciate the proposal though. Thanks!
