### ISSUE TITLE
Add rendering options for `broadcasts`/`broadcasts_to`

### ISSUE THREAD

**Issue by boardfish** [hotwired/turbo-rails#270]
Over at [github/view_component](https://github.com/github/view_component), we're thinking about how best to integrate components with Turbo Streams. So far, the integration's already pretty strong - so long as you have (or make) a view context, you can render a component to a string and pass it to `Turbo::StreamsChannel`, e.g.:

```ruby
Turbo::StreamsChannel.broadcast_append_to(
  record_or_channel_name,
  target: dom_target_id,
  html: ExampleComponent.new.render_in(view_context)
)
```

Notice that we're passing the component, rendered to a string, as the `html` param. 

All public methods on `Broadcastable` besides [`broadcasts` and `broadcasts_to`](https://github.com/hotwired/turbo-rails/blob/main/app/models/concerns/turbo/broadcastable.rb#L68-L79) allow you to pass other options for rendering, including `html`. So it'd be good to be able to set those other options too.

I'm happy to implement this.

Here's the background discussion:

https://github.com/github/view_component/issues/1106#issuecomment-959373755

**Comment by dhh** [comment]
It's a little funky because those methods encompass several sub-calls, so having options that only apply to some is a bit odd. But happy to see what a PR could look like. Maybe it's fine.

**Comment by genezys** [comment]
I had a similar thinking about broadcasting a specific partial from my model:

```ruby
class Model
  broadcasts_to ->(model) { [model, :details] }, partial: "models/details"
end
```

I made modifications similar to PR #113 by overriding the `broadcasts_to` signature in a concern.

**Comment by genezys** [comment]
Here is the concern I added for those interested if PR #113 is not merged:
```ruby
module BroadcastableExtensions
  extend ActiveSupport::Concern

  class_methods do
    def broadcasts_to(stream, inserts_by: :append, target: broadcast_target_default, **rendering_options)
      after_create_commit  -> { broadcast_action_later_to stream.try(:call, self) || send(stream), action: inserts_by, target: target.try(:call, self) || target, **rendering_options }
      after_update_commit  -> { broadcast_replace_later_to stream.try(:call, self) || send(stream), **rendering_options }
      after_destroy_commit -> { broadcast_remove_to stream.try(:call, self) || send(stream), **rendering_options }
    end
  end
end
```

**Comment by dhh** [comment]
Done 👍
