### ISSUE TITLE
Yanked versions?

### ISSUE THREAD

**Issue by schneems** [hotwired/turbo-rails#273]
Hello. 

Today I see several versions of the gem were yanked. Which resulted in some build failures for the test fixtures I'm using on Heroku to ensure that Rails 7 continues to work. This added an extra ~20min of downtime to the outage we had yesterday as deploying a fix was blocked on diagnosing the test suite failures, skipping that test, and then re-running.

I'm curious to know more about why those versions are yanked. You can reach me through my email on GitHub if it's sensitive and you don't want to talk about it in public.

**Comment by dhh** [comment]
What @kylekeesling pointed to. These releases were made on the wrong version track, and we wouldn't have been able to follow a normal release path going forward without yanking them. It was my mistake, and unfortunately wasn't noticed for some time.

**Comment by schneems** [comment]
Thanks for the clarification
