### ISSUE TITLE
Videos not loading when navigating through Turbo

### ISSUE THREAD

**Issue by jakemumu** [hotwired/turbo-rails#276]
`gem 'rails', '6.1.4.1'`
`gem 'hotwire-rails'`

Turbo appears to be loading pages fine, however when I navigate to pages containing tags such as: 

```
      <video autoplay loop muted playsinline class="embed-responsive bg-g1">
        <source src="xyz">
      </video>
`````

The videos don't render on the page.  A full page reload loads no problem.

**Comment by jakemumu** [comment]
Side note -- solved this by changing all the video tags to be generated via `video_tag` but I'm confused what the issue with the original html was?

**Comment by dhh** [comment]
Not sure what this might be, but let's explore on hotwired/turbo, as it would be an issue with the JS library, not the Rails integration.
