### ISSUE TITLE
url generation for hash (without path) fails in broadcasts_to

### ISSUE THREAD

**Issue by ConfusedVorlon** [hotwired/turbo-rails#277]
link_to allows you to use only params to generate a link to the current url

`<%= link_to "Test params link", {foo: "bar"} %>`

this generates 

`<a href="/current_path?foo=bar">Test params link</a>`

this is super useful for adding search/filtering functionality (no doubt also in other cases)

unfortunately, if this fragment is used as a result of a broadcast callback in the model, then url generation fails

```
ActionView::Template::Error (No route matches {:foo=>"bar"}):
       <br/>
      <%= link_to "Test params link", {foo: "bar"} %>
     </div>
```

Presumably the issue here is that the serialised model doesn't 'know' about the current request. 
Perhaps there is no way around that...

**Comment by ConfusedVorlon** [comment]
example repo
https://github.com/ConfusedVorlon/hotwire-twitter-clone

**Comment by tenpaiyomi** [comment]
@ConfusedVorlon so, you're correct in that the broadcast callback from a model doesn't have any context of the current request.  At this point in time, I'm not aware of a way to resolve the issue you're experiencing, but thinking over it I would say that perhaps you could create a route that would work regardless of the scope of the current page, perhaps working in tandem with the model in question or so.

So, for example, say you wanted to do something for filtering on model A, `Tweet`, and model B, `User`.  You could create a couple routes like such:

```ruby
get '/filter/tweets', to: 'tweets#filter'
get '/filter/users', to: 'users#filter'
```

Of course, that in itself could be kind of verbose depending on how much you need to do, so you could do a little meta-programming as well

```ruby
scope ':type' do
  get 'filter', to: 'base#type_filter', as: 'base_filter'
end
```

```ruby
class BaseController < ApplicationController
  def type_filter
    dest_controller = "#{params[:type].camelize}Controller".constantize
    dest_controller.dispatch(:filter, request, response)
  end
end

class TweetsController < ApplicationController
  def filter
    # filter on Tweets
  end
end

class UsersController < ApplicationController
  def filter
    # filter on Users
  end
end
```

From there, a request to `/tweets/filter` would go to `base#type_filter`, where the `type` parameter would get converted into a constant, `TweetsController`, and the request would be fired off to the appropriate controller.  Your `link_to` then, knowing that it exists in the `_tweet.html.erb`, could simply be formatted as:

```ruby
<%= link_to "Test params link", base_filter_path(type: 'tweet', bar: 'baz') %>
```

Which would then work as such:

```ruby
[1] pry(main)> ApplicationController.render(inline: "<%= link_to 'Filter', base_filter_path(type: :tweet, bar: 'baz') %>")
  Rendering inline template
  Rendered inline template (Duration: 0.9ms | Allocations: 317)
=> "<a href=\"/tweet/filter?bar=baz\">foo</a>"
```

Of course, if you are always going to be passing a model to that same route, you could just make it a helper too and declare the type from the model itself (didn't test this code out, but it should work in theory)

```ruby
def link_to_filter(obj, params)
  link_to 'Filter', base_filter_path(params.merge(type: obj.class.to_s))
end

[1] pry(main)> ApplicationController.render(inline: "<%= link_to_filter(tweet, bar: 'baz') %>")
  Rendering inline template
  Rendered inline template (Duration: 0.9ms | Allocations: 317)
=> "<a href=\"/tweet/filter?bar=baz\">foo</a>"
```

**Comment by ConfusedVorlon** [comment]
Hi @tenpaiyomi 

Thanks for the detailed response. Interesting to see how you approached that.

I went for a different approach and just set things up so that the urls could be generated client side from some data attributes.

Stimulus does a great job of handling new snippets wherever they come from - and can obviously access the current url easily enough.
