### ISSUE TITLE
Broadcasted :html is escaped and thus unusable with sidekiq adapter

### ISSUE THREAD

**Issue by jbfeldis** [hotwired/turbo-rails#284]
Hi all :wave:

I have an issue with turbo-rails broadcasting streams via action_cable using sidekiq.

I am using `broadcast_render_later_to` from my controller feeding the result of render to the `:html` option ([added](https://github.com/hotwired/turbo-rails/pull/245) not so long ago):
```ruby
format.turbo_stream do
  @things = Thing.all
  @thing.broadcast_render_later_to(:things,
    target: "things",
    html: render
  )
end
```
In our real app, we want to keep our broadcasts in our controllers (the real-world scenario would need an access to the pagination ivars, the created record to be highlighted...).
This is a simple use case from the new rails app I set up to test this issue but the structure is the same. 

I have basically nailed it down to [this render](https://github.com/hotwired/turbo-rails/blob/3992b7e7530c8335cc60388a521bd72de8412879/app/channels/turbo/streams/broadcasts.rb#L86) giving different results when being called from sidekiq. 
```ruby
    def render_format(format, **rendering)
      ApplicationController.render(formats: [ format ], **rendering)
    end
```
When called directly or within the default adapter the SafeBuffer is kept and the broadcasted message is correct.
When called from sidekiq, `#perform` gets an unsafe string which then gets escaped and nothing can be done with it on the frontend.

What I get with sidekiq :
```
Turbo::StreamsChannel transmitting "&lt;turbo-stream action=&quot;replace&quot; target=&quot;things&quot;&gt;&lt;template&gt;\n  &lt;turbo-frame id=&quot;things&quot;&gt;\n  &lt;table&gt;\n    &lt;thead&gt;\n      &lt;tr&gt;\n        &lt;th&gt;On&lt;/th&gt;\n        &lt;th colspan=&quot;3&quot;&gt;&lt;/th&gt;\n      &lt;/tr&gt;\n ... (via streamed from things)
```

The expected result (which I get either sync or with the default active_job adapter:
```
Turbo::StreamsChannel transmitting "<turbo-stream action=\"replace\" target=\"things\"><template>\n  <turbo-frame id=\"things\">\n  <table>\n    <thead>\n      <tr>\n        <th>On</th>\n        <th colspan=\"3\"></th>\n      </tr>\n    </thead>\n\n    <tbody>\n        <tr>\n          <td>false</td>\n          <td><a href=\"/thing... (via streamed from things)
```

I can monkey patch the render method to unescape the result and welcome hackers to the party but it's probably not the way to go :wink:  :
```ruby
CGI.unescapeHTML(
  ApplicationController.render(formats: [ format ], **rendering)
)
```

Did anyone already encounter this, am I missing something awfully basic?

Here's the new rails app :
https://github.com/jbfeldis/turbo-rails-sidekiq-html_safe
Regular setup, launch a sidekiq process, open two browser windows and create a "thing" from the root page, you'll see it's not updating correctly on the page that did not submit the form.
If you comment [the sidekiq adapter ](https://github.com/jbfeldis/turbo-rails-sidekiq-html_safe/blob/master/config/application.rb#L14) and restart your processes it works as expected.

**Comment by jonknapp** [comment]
An alternative ~~horrible~~ hacky approach is to decode the encoded HTML when it arrives from the websocket. Something like:

```
function htmlDecode(input) {
  var e = document.createElement('div');
  e.innerHTML = input;
  return e.childNodes.length === 0 ? '' : e.childNodes[0].nodeValue;
}

document.addEventListener('turbo:before-stream-render', (event) => {
  console.log('before render stream', event);
  console.log(htmlDecode(event.target.children[0].innerHTML));
  event.target.children[0].innerHTML = htmlDecode(
    event.target.children[0].innerHTML
  );
});
```

**Comment by dhh** [comment]
Sounds like this is a problem that needs to be fixed in the sidekiq adapter?

**Comment by afcapel** [comment]
I also hit this issue using resque, but could workaround it using the `content` param in my `broadcast_` calls, instead of `html`.
