### ISSUE TITLE
turbo:load does not almost ever trigger on page load when using Firefox

### ISSUE THREAD

**Issue by jarmo** [hotwired/turbo-rails#286]
I tried to use Rails 7 and wrote code like this in one of my view template:
```html
<script>
document.addEventListener("turbo:load", () => alert("foo"))
</script>
```

It does work every time on Chrome/Edge on Windows when pressing refresh in the browser, however when I use Firefox then it does trigger only very rarely.

I found an issue https://github.com/guybedford/es-module-shims/issues/161 which seems to be the exact problem I'm having, but I would expect that this is long time ago fixed already since I'm using Rails 7.0.0.

Any ideas why it does not work?

**Comment by denschub** [comment]
I found this issue by looking into why a larger app breaks for me. Sadly, while trying to build an isolated test case, I failed, and it worked every time. @jarmo, did you succeed building a simple testcase for that?

**Comment by jarmo** [comment]
@denschub it was a pretty barebones Rails app at the time, which I still had on my disk, but when trying again it now then this problem does not occur anymore at all. Maybe it's also Firefox version related?

**Comment by denschub** [comment]
It's not related to any Firefox version, sadly. I'm starting to have a fairly good understanding (see the other bug I linked), but I have to dig a bit more into that... I have a hunch of what it might be, but I have to validate that first.

**Comment by jarmo** [comment]
I'm just confused as to why it does not happen anymore for me with the same codebase on the same PC using Firefox. Only thing I can think of is that some time has passed and things might have changed with Firefox. At the time of reporting this issue I almost never managed to get `turbo:load` to fire, but now it seems to fire every time. I did not update any gems or anything.

**Comment by jarmo** [comment]
Okay, refreshed my page like 50 times and managed to reproduce it only one time (which is also bad of course).

**Comment by dhh** [comment]
Solved in https://github.com/rails/importmap-rails/releases/tag/v1.1.0
