### ISSUE TITLE
Wrong Content-Type with HAML

### ISSUE THREAD

**Issue by jurta** [hotwired/turbo-rails#287]
When views templates are written in ERB and contain a turbo_frame_tag, then for a request with the turbo-streams type, the response correctly uses the HTML content-type `text/html`.

But when templates are in HAML, then for a turbo-streams request, the response incorrectly uses the turbo-stream content-type `text/vnd.turbo-stream.html`, and the JS side fails to update the turbo frame because it expects the HTML content-type `text/html`.

A temporary workaround that helps to fix this problem is to force the correct HTML content-type with e.g.:

```ruby
    respond_to do |format|
      format.turbo_stream { response.headers['Content-Type'] = 'text/html; charset=utf-8' } # for haml
    end
```

**Comment by mtomov** [comment]
Yeah! Can confirm the bug and the solution! Have you managed to find a more generic solution / patch to the issue?

**Comment by priit** [comment]
I know it's against current Rails defaults about file naiming rules what was caused by flexible .erb format but let's not forget that haml is always html. Therefore semantically it's rather redudant and noisy to declare html multilpe times that haml is html where it never can be anything else. I work with view files rather often where I inspect files in tree in command line and it's rather important they are short and clear without redudant html noise. 

Therefore I support any effort to keep semantically correct .haml format as well.

**Comment by Aesthetikx** [comment]
Just ran across this today during my work on a `turbolinks => turbo` upgrade, and we have tons of `.haml` files that I do not want to rename to `html.haml`, as that was not necessary in the past.

**Comment by Aesthetikx** [comment]
It seems that as a result of [e693f45e155a81b6c337b8766870b56716a05105](https://github.com/rails/rails/commit/e693f45e155a81b6c337b8766870b56716a05105) from 13 years ago which has made its way [here](https://github.com/rails/rails/blob/5c89dc3eb96fb3f534c47b03fcade43e9db2ee3b/actionview/lib/action_view/renderer/template_renderer.rb#L38), we can do the following as a 'fix' for omitting the `.html` in `.html.haml`

```ruby
module Haml # (or Hamlit)
  class RailsTemplate
    def default_format
      :html
    end
  end
end
```

**Comment by dhh** [comment]
Seems like this is a general Rails issue. Would be happy to take a doc change to turbo-rails explaining the naming convention needs, though.

**Comment by lazylester** [comment]
the monkey patch suggested by @Aesthetikx works great on haml 5.2.2, but it doesn't look as if it's going to work on haml 6.0, as there's no plugin class to hold the monkey-patch

**Comment by lazylester** [comment]
I made a pull request for haml6 to incorporate @Aesthetikx monkey patch, https://github.com/haml/haml/pull/1144
