### ISSUE TITLE
New Feature Request - Turbo Stream Action - Reload

### ISSUE THREAD

**Issue by tdak** [hotwired/turbo-rails#288]
All examples of broadcasting from a model have been related to sending a partial via a Redis channel.  The issue with this approach is that it is too simple. 

In many cases, after I update a model, sending a partial back won't work because other dependencies in the partial need to be loaded correctly. So I usually load them via the controller. 

For example, in a Project partial, I have a list of tasks and other related models, like category, sprint, etc. The controller loads these.  So the partial relies on the controller to supply the correct data.  

These other dependencies won't be loaded if I send a broadcasts_to "project" via the Project model. So this doesn't work well. 

I propose adding another action called "reload." 

<turbo-stream action="reload" target="project_1"></turbo-stream>

This action will trigger a reload of the turbo-frame with an src attribute.  

<turbo-frame id="project_1" src="/projects/1">...</turbo-frame>

Thoughts?

**Comment by seanpdoyle** [comment]
Is your use case strictly related to receiving `<turbo-stream>` element through broadcasts (as opposed to receiving `<turbo-stream>` elements in response to Form Submissions)?

Would dispatching an action with a `<turbo-frame>` element in its contents and `[action="replace"]` suit your needs?

```html
<turbo-stream action="replace" target="project_1234">
  <template>
    <turbo-frame src="/projects/1234"><!-- element intentional left empty --></turbo-frame>
  </template>
</turbo-stream>
```

Once it's mounted, the element would fetch its contents.

If that isn't sufficient, you might be interested in the strategy for custom Stream Actions outlined by https://github.com/hotwired/turbo/pull/479#issuecomment-999683061.

If that feels heavy handed, you could implement it with a more focused Stimulus controller:

```js
// app/javascript/controllers/reload_controller.js

import { Controller } from "@hotwired/stimulus"

export default class extends Controller {
  connect() {
    this.element.closest("turbo-frame")?.reload()
    this.element.remove()
  }
}
```

```html
<turbo-stream action="append" target="project_1234">
  <template><meta data-controller="reload"></template>
</turbo-stream>
```

**Comment by tdak** [comment]
I like the second approach for now.  But it feels like it's something that turbo should have by default.

**Comment by tdak** [comment]
I am wondering about triggering this from inside of a model.  i.e broadcast_to call to trigger an automatic reload

**Comment by seanpdoyle** [comment]
> I am wondering about triggering this from inside of a model. i.e broadcast_to call to trigger an automatic reload

If updates from a broadcast are a hard requirement, is there an opportunity to extract and re-use the controller's model-loading code so that it can be shared across the controller and the broadcasted partial.

As I understand it, the broadcast calls' support for `partial:` and `locals:` options opens the door to that kind of flexibility and re-use.

**Comment by tdak** [comment]
Yes, some sort of business object pattern would probably work.  It feels a bit heavy for the model to know about business rules, in my view.  I can see how the model is responsible for notifying an interested party that something has changed.  So that's why I think reload in the broadcast_to would be a good idea.

**Comment by tdak** [comment]
Followed your example and made this 
`module Turbo::Reloadable
  extend ActiveSupport::Concern

  module ClassMethods

    def broadcasts_reload_to(stream, target: broadcast_target_default)

      stream = stream.try(:call, self) || send(stream)
      target = target.try(:call, self) || target

      template = "<meta data-controller='turbo--reload'/>"

      after_create_commit  -> { Turbo::StreamsChannel.broadcast_append_to(stream, target: target, content: template) }
      after_update_commit  -> { Turbo::StreamsChannel.broadcast_append_to(stream, target: target, content: template) }
      after_destroy_commit  -> { Turbo::StreamsChannel.broadcast_append_to(stream, target: target, content: template) }

    end
    
  end
end 
`

Call it like this 
` 
broadcasts_reload_to ->(t) { [ t, :tasks ] }, target: "project_1" 
`

Still needs the stimulus controller above. 


It would be great to have this built in.

**Comment by feliperaul** [comment]
@seanpdoyle Sean, where could I read more about the `.reload()` method in `this.element.closest("turbo-frame")?.reload()` ?

**Comment by tonysm** [comment]
@feliperaul I believe that's part of the [Frame element API](https://github.com/hotwired/turbo/blob/main/src/elements/frame_element.ts#L60-L64). It works by unsetting and then resetting the `src` attribute in the Turbo Frame, as [mentioned in the docs](https://turbo.hotwired.dev/reference/frames#functions).
