### ISSUE TITLE
Including `turbo_stream_from` in a partial you're replacing duplicates the element

### ISSUE THREAD

**Issue by joshleblanc** [hotwired/turbo-rails#29]
Not sure how to word this.

If you have a partial:

```erb
# _foobar.html.erb
<%= turbo_stream_from model %>
```

and in a controller action, you're replacing that partial

```ruby
def do_something
  @model.broadcast_replace partial: "examples/foobar", locals: { model: @model }
end
```

The `turbo-cable-stream-source` element will get duplicated exponentially. 

![IhHIc4cm6v](https://user-images.githubusercontent.com/1729810/103093176-f243ab80-45cf-11eb-9cfe-dea541cde955.gif)

**Comment by javan** [comment]
This was fixed by https://github.com/hotwired/turbo-rails/pull/24. Generally, it's best not to replace the `<turbo-cable-stream-source>` element like this since it'll unsubscribe and then resubscribe to the same channel.
