### ISSUE TITLE
Script tag executed twice

### ISSUE THREAD

**Issue by netoff** [hotwired/turbo-rails#291]
If there is a `<script>` tag on a page it will be executed twice when navigated with turbo. On the initial page load, it works as expected, this happens only on turbo visits. For example, you can add `<script>console.log('inside turbo')</script>` and it will be printed twice on the console if you click on a turbo enabled link for that page. 

Is this turbo or a turbo-rails related issue? Can somebody point me in the direction where I can add spec for this?

**Comment by darkBuddha** [comment]
> Annotate `<script>` elements with `data-turbo-eval="false"` if you do not want Turbo to evaluate them after rendering. Note that this annotation will not prevent your browser from evaluating scripts on the initial page load.

https://turbo.hotwired.dev/handbook/building#working-with-script-elements

You maybe also want to check `data-turbo-cache="false"` (https://turbo.hotwired.dev/handbook/building#preparing-the-page-to-be-cached)

**Comment by netoff** [comment]
OK, I will investigate cashing, maybe that's the issue. This happens if there is an iframe on the page having a script. So in theory I can not control content within that iframe, thus adding `data-turbo-eval` does not work in my case. I will be closing this issue now.

**Comment by darkBuddha** [comment]
Good luck!
