### ISSUE TITLE
Why does bundler sometimes incorrectly install version 7.1.1 of this gem (which does not exist)?

### ISSUE THREAD

**Issue by jasonfb** [hotwired/turbo-rails#292]
can someone tell me why bundler *sometimes* installs version 7.1.1 of this gem which does not exist?

As I make lots of training material, I have have seen this happen on a few new Rails 7 apps. If I delete the Gemfile.lock and `bundle install`, the problem goes away. 

I will try to identify the steps to recreate here.

**Comment by DavidColby** [comment]
I had the same issue from having 7.1.1 in my local bundler cache for some of my installed ruby versions. Try `gem uninstall turbo-rails`, as described [here](https://github.com/rails/rails/issues/43962#issuecomment-999183698) and the discussion on where this incorrect version came from [here](https://github.com/rails/rails/issues/43962#issuecomment-999184116).

**Comment by jasonfb** [comment]
yes indeed thank you @DavidColby 

duplicate of https://github.com/rails/rails/issues/43962
