### ISSUE TITLE
Still using @rails/actioncable 6 in package.json

### ISSUE THREAD

**Issue by brunoprietog** [hotwired/turbo-rails#293]
Hi! In the package.json there is still `@rails/actioncable: ^6.0.0`, which means it only uses actioncable up to version 6.x.x. Is there any reason to keep this like this? Could we take advantage of the new actioncable features coming in rails 7?

Thanks!

**Comment by dhh** [comment]
Should update to 7 yeah.

**Comment by dhh** [comment]
Released as part of https://github.com/hotwired/turbo-rails/releases/tag/v1.0.1
