### ISSUE TITLE
Stream rendering issues when used with ViewComponent

### ISSUE THREAD

**Issue by boardfish** [hotwired/turbo-rails#294]
Hey folks! Anyone wanting to use Turbo Stream responses with ViewComponent at the moment may fall foul of github/view_component#1227. We'll be looking into the issue over there, so if you'd like to contribute or just need to know the latest, that's a good place to go.

**Comment by marcoroth** [comment]
Hey @boardfish, thanks for the heads-up!

Is there any way we could help to get this one over the finish-line?

**Comment by brunoprietog** [comment]
Closing since the discussion is in the other issue

**Comment by boardfish** [comment]
I figure this was closed as stale – the issue's [still present](https://github.com/ViewComponent/view_component/pull/1227) as far as I can see (I have a PR in the works to test against V2). `TagBuilder` works off the back of a view context it receives – that's potentially at the core of what needs to change here.

I've been able to fix this by including this code in a component, which directly calls the component's own `tag` and `capture` methods.

```rb
    def turbo_stream
      TurboStreamTagPatch.new(self)
    end

    # The `turbo_stream` helper provided by `turbo-rails` uses ActionView's `capture`
    # in a way that's incompatible with ViewComponent and leads to strange duplicated output.
    # These patches restore the behaviour without needing to change view code.
    # https://github.com/ViewComponent/view_component/issues/1137
    # https://viewcomponent.org/known_issues.html#turbo_frame_tag-double-rendering-or-scrambled-html-structure
    class TurboStreamTagPatch
      def initialize(component)
        @component = component
      end

      def replace(target, _content = nil, **_rendering, &block)
        content = @component.capture(&block)
        tag.turbo_stream(action: :replace, target:) { tag.template { content } }
      end

      def update(target, _content = nil, **_rendering, &block)
        content = @component.capture(&block)
        tag.turbo_stream(action: :update, target:) { tag.template { content } }
      end

      # ...

      delegate :tag, to: :@component
    end
```

I don't know enough about how `TagBuilder` works internally to have an immediate suggestion, but what I have here suggests that changing the scope within which we use `tag` and `capture` might help to resolve this.
