### ISSUE TITLE
Turbo-Rails tries to call `then` on object/string passed to the stream helpers

### ISSUE THREAD

**Issue by matsimitsu** [hotwired/turbo-rails#30]
Rails 6.1.0 installed with `rails new --skip-action-mailbox --skip-action-text --skip-active-storage --skip-spring --skip-sprockets`. Added `gem "turbo-rails", "~> 0.5.1"` to the Gemfile and Followed the webpack installation guide.

Any time I call a turbo-stream helper I get:

![Screenshot 2020-12-24 at 17 25 47](https://user-images.githubusercontent.com/28408/103099542-33a77b80-460f-11eb-9394-52403abc5e62.jpg)

Same happens in the models when calling:

```ruby
class Link < ApplicationRecord
  belongs_to :network

  broadcasts_to ->(link) { [ link.network, :links ] }, inserts_by: :prepend, target: "links"
end
```

It seems some part of the setup is missing, but I can't figure out what yet.

**Comment by dhh** [comment]
You must be running a Ruby older than 2.6 when this kernel method #then was added: https://nithinbekal.com/posts/ruby-2-6/#kernelthen

I'll put a minimum Ruby requirement of 2.6+ on the gem 👍
