### ISSUE TITLE
Add `:turbo_stream` to `ActionView::Base.default_formats`

### ISSUE THREAD

**Issue by HarrisonB** [hotwired/turbo-rails#303]
Let's say you have a view of the name `app/views/posts/edit.turbo_stream.erb`.

Right now, by default, unless you do one of the following:
1. Specify the `formats:` keyword param to `render` in `PostsController#edit`
2. Explicitly generate the `turbo_stream.whichever_action(...)` at the controller level and pass to the `turbo_stream:` keyword param
3. Use `respond_to` with `format.turbo_stream`

Rails will fail to find the view because `ActionView::Base.default_formats` doesn't contain `:turbo_stream`. It's unclear to me philosophically why you don't need to do the above for HTML or JSON but you do have to do it for Turbo Streams. I added `:turbo_stream` to `ActionView::Base.default_formats` in an initializer and it seems to address this asymmetry--apologies if this is an anti-pattern for some reason I'm just unaware.

**Comment by jaryl** [comment]
In my app, none of my controllers have to specify any turbo stream specific code, which I want to keep that way. As long as I have a `*.turbo_stream.*` template as the only matching template for a non-GET request, I can easily get it to render the turbo stream template.

I did not have to manually add an initializer like you mentioned, and it already includes `:turbo_stream`, perhaps it was added here:
https://github.com/hotwired/turbo-rails/blob/main/lib/turbo/engine.rb

**Comment by dhh** [comment]
The general idea is that turbo streams should be a progressive enhancement over a default path that works with something like redirects: https://turbo.hotwired.dev/handbook/streams#progressively-enhance-when-necessary. But we should at least document how to run with scissors and add to the default_formats. Feel free to open a doc PR for that.
