### ISSUE TITLE
`turbo_frame_tag` in between `<ul>` and `<li>`?

### ISSUE THREAD

**Issue by radiantshaw** [hotwired/turbo-rails#305]
I have the following HTML on a page:

```erb
<ul>
  <%= turbo_frame_tag "list" do %>
    <li>First item</li>
    <li>Second item</li>
  <% end %>
</ul>
```

for which the server sends a Turbo Stream response as:

```erb
<%= turbo_stream.prepend "list" do %>
  <li><%= params[:new_list_item_data] %></li>
<% end %>
```

upon submission of a form somewhere on the page.

I suppose this isn't valid since there's a `<turbo-frame>` between the `<ul>` and `<li>`. So is there a different solution that should be followed for this specific use case? Like re-rendering the entire list again? But what if the list items are complex objects that need to be fetched from the database? Wouldn't that be inefficient to fetch the whole list every time a new item is added?

So I'm looking out for a solution that is efficient and also doesn't break HTML semantics.

**Comment by DavidColby** [comment]
In the scenario you outlined, you do not need a `<turbo-frame>`. This will work fine:

```erb
<ul id="list">
  <li>First item</li>
  <li>Second item</li>
</ul>

<%= turbo_stream.prepend "list" do %>
  <li><%= params[:new_list_item_data] %></li>
<% end %>
```

If you need a Turbo Frame wrapping the entire list (lazy loading, for example), you can move the `<turbo-frame>` up to wrap the `<ul>` while continuing to target the `<ul>` by id in your Turbo Stream action to insert new items into the list.

```erb
<%= turbo_frame_tag "list-frame" do %>
  <ul id="list">
    <li>First item</li>
    <li>Second item</li>
  </ul>
<% end %>

<%= turbo_stream.prepend "list" do %>
  <li><%= params[:new_list_item_data] %></li>
<% end %>
```

**Comment by radiantshaw** [comment]
@DavidColby Wait, so the ID passed to the `turbo_stream` methods also target HTML `id` attribute? 🤔

**Comment by DavidColby** [comment]
@radiantshaw Right. You do not have to target a `<turbo-frame>` element, you can target any element you like.

**Comment by radiantshaw** [comment]
@DavidColby I now understand how Turbo Streams work, having read the documentation. Thanks for pointing me in the right direction. I really appreciate the quick response. ✌️
