### ISSUE TITLE
initial location.hash causes navigating to that anchor to result in turbo XHR fetch requests

### ISSUE THREAD

**Issue by 2called-chaos** [hotwired/turbo-rails#306]
First of all, I surely could just data-turbo=false this but I think it's still a bug one way or the other.

Example App: https://github.com/2called-chaos/turbo-anchor-test

# Steps to reproduce

1. Start server, visit root path and open browser console
3. Click on a number (e.g. 50), page jumps, no request
4. Reload page with that anchor (e.g #ctn_50)
5. All further navigations to that anchor (at the top or in the h1) result in a turbo XHR fetch
5.1. Clicking a different anchor results in no fetch
5.2. Clicking the anchor that was present on page load again WILL result in fetches

# Expectation

Either turbo should kick in on anchor links to the same url all the time or never. Now it only kicks in if the anchor or rather full location is the same as on document load which makes no sense to me

**Comment by dhh** [comment]
This is a Turbo issue, not related to the integration with Rails. I remember a ticket there discussing this, and a deliberate choice to go with the reload. But don't remember the particulars. You'll be able to find it on the issue tracker there.
