### ISSUE TITLE
Initializer crashes when using classic autoloader without ActionCable

### ISSUE THREAD

**Issue by ExMember** [hotwired/turbo-rails#307]
Error:

```
turbo-rails-1.0.1/lib/turbo/engine.rb:20:in `block in <class:Engine>': undefined method `do_not_eager_load' for nil:NilClass (NoMethodError)
```
If Action Cable is not enabled, turbo-tries to use `Rails::Autoloaders.once` to [prevent eager loading of ActionCable files.](https://github.com/hotwired/turbo-rails/blob/v1.0.1/lib/turbo/engine.rb#L20)

But if Zeitwerk is not enabled, [`Rails::Autoloaders.once`](https://github.com/rails/rails/blob/v6.1.4.4/railties/lib/rails/autoloaders.rb#L19-L26) returns nil.

**Comment by codealchemy** [comment]
Proposed fix in https://github.com/hotwired/turbo-rails/pull/304
