### ISSUE TITLE
Turbo can't be disabled for button_to helper

### ISSUE THREAD

**Issue by jdno** [hotwired/turbo-rails#31]
Hello,

I have a button that POSTs to a route in my app:

```erb
<%= button_to "/auth/github", data: { turbo: false } do %>
  Sign in with GitHub
<% end %>
```

I added `data-turbo="false"` to the button to make sure users are properly redirected to GitHub. But when I click the button, an XHR request is fired off to the endpoint with `turbo` being shown as the initiator.

I tried adding `data-turbo="false"` to the button's parent element to see if that would fix it, but that's not the case either.

When I remove ` <%= turbo_include_tags %>` from my layout, everything works as expected.

Maybe I am missing something obvious, but not being able to disable Turbo for the button feels like a bug to me.

Tested with:
- Rails 6.1.0
- turbo-rails 0.5.1

Happy to provide more information or context if that would be helpful.

Thanks!

**Comment by seanpdoyle** [comment]
Would this be addressed by https://github.com/hotwired/turbo/pull/3?

**Comment by jdno** [comment]
Yes! `button_to` creates a form with a single button under the hood, and if forms respect `data-turbo="false"` this issue here will be resolved as well.
