### ISSUE TITLE
Form submissions cancel each other

### ISSUE THREAD

**Issue by krisdigital** [hotwired/turbo-rails#310]
With UJS I was using forms to easily make xhr requests without having to pass values to javascript. When switching to turbo I noticed that only the last form submission succeeds and found this code:

https://github.com/hotwired/turbo/blob/main/src/core/drive/navigator.ts#L45

Question: Is it really necessary to stop all form submissions when starting a new one?

Before I would do in UJS

```js
  for (var i = 0; i < rows.length; i++) {
    Rails.fire(rows[i].querySelector('form'), 'submit')
  }
```
(worked)

Now I would do in Turbo
```js
  for (var i = 0; i < rows.length; i++) {
    rows[i].querySelector('form').requestSubmit()
  }
```
(does not work, submits all forms but cancels all but the last one)

Curious to know! ☺️

**Comment by dhh** [comment]
Yeah, we had a bunch of side effects re: navigation when processing multiple responses at once. Don't see this changing. You can look into https://github.com/rails/request.js instead.

**Comment by pedroaugustofsilva** [comment]
@krisdigital 

Turbo prevents concurrent form submissions within the same frame to avoid conflicts, but allows simultaneous submissions when forms are in different frames.

This will do concurrent form submissions:
```html+erb
<% @users.each do |user| %>
  <%= turbo_frame_tag dom_id(user) do %>
    <%= form_with model: user do %>
       form here
    <% end %>
  <% end %>
<% end %>
