### ISSUE TITLE
replace Turbo Frame with partial on select change

### ISSUE THREAD

**Issue by itsyoshio** [hotwired/turbo-rails#311]
Hi there, this might be an unusual one and it might classify as a dumb question.

What i'd like to do is to specialize a part of my Form based on a select input.
To Clarify : 

```
...
[Kind Select] -> {A,B,C}
<TURBO FRAME>
  (only one at a time)
  - Special Form A 
  - Special Form B
  - Special Form C
</TURBO FRAME>
```

Depending on the Kind you select, i'd like to populate the Turbo Frame with the respective Content.
The Special Forms (A,B,C) are partials each.

For now i have a Stimulus Controller that can act on the SelectBox Change.
It could then take the Value. Then i thought of setting the Turbo Frame's Source.

However i can't set partials as src without routing through a custom controller method.

------------

> How to dynamically append / replace a specific form part (partial) with turbo frame?

Many thanks.

**Comment by itsyoshio** [comment]
Wrong repo, sorry

**Comment by dhh** [comment]
We don't have such an option. You gotta replace the whole thing or further decompose with specific frames.
