### ISSUE TITLE
Restricting user from access edit view directly without turbo-frame

### ISSUE THREAD

**Issue by kwhandy** [hotwired/turbo-rails#315]
Hi guys, anyone know how to prevent user from accessing the view directly? I am using turbo frame and edit action in my controller is just like this:

```ruby

def edit; end

```

I've spend much time to figure out how to prevent user to access **example.com/posts/1/edit** directly, when I already provided the edit capability via normal `turbo-frame` but I still stuck. Can anyone share how to achieve this?

**Comment by pinzonjulian** [comment]
Hey! This seems more like an implementation question rather than a library issue. 

I suggest you ask in the official hotwire discuss http://discuss.hotwired.dev  or in this discord server https://discord.gg/stimulus-reflex

**Comment by kwhandy** [comment]
@pinzonjulian are you facing the same problem btw? I've been there, that's why I'm here. If you know some clue about this pleaseeee let me know.

**Comment by pinzonjulian** [comment]
Tag me in any of those forums and I can give you a hand:)

**Comment by kwhandy** [comment]
@pinzonjulian then please give your hand [**here**](https://stackoverflow.com/questions/70476005/rails-turbo-hotwire-prevent-user-from-accessing-the-view-directly)
