### ISSUE TITLE
javascript not trigger after navigate through links

### ISSUE THREAD

**Issue by helmutrs** [hotwired/turbo-rails#317]
I have at the end of my application.html.erb:

jQuery:
<script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
Bootstrap:
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-fQybjgWLrvvRgtW6bFlB7jaZrFsaBXjsOMm/tB9LTS58ONXgqbR9W8oWht/amnpF" crossorigin="anonymous"></script>
Custom vendor js file
<%= javascript_include_tag 'ace.js' %>

After navigating with any of the links, Bootstrap and the vendor file stops working. 

I understand that we can reload our custom js files with document.addEventListener("turbo:load", function() {}, but shouldn't vendor files on the javascript_include_tags reload as well automatically without the help of stimulus? Thanks.

**Comment by PedroAugustoRamalhoDuarte** [comment]
Hello, Turbo tracks your js files inside head tag (https://turbo.hotwired.dev/handbook/building#loading-your-application%E2%80%99s-javascript-bundle), If you just move your cdn scripts files to head tag it will works.

**Comment by r3tr0sp3c** [comment]
That is also my question.
I've switched to `document.addEventListener("turbo:load", function() {} );`
But i feel it's a counter-measure and shouldn't be like that.

**Comment by dhh** [comment]
JS includes will not automatically reload. That's half the point with Turbo 😄. It's a permanent process. You have to use the lifecycle hooks.
