### ISSUE TITLE
304 after redirect doesn't work

### ISSUE THREAD

**Issue by ClayShentrup** [hotwired/turbo-rails#322]
If I redirect to a path that returns 200, (after a form post in my case), it loads just fine. But if it's a 304 Not Modified, the new page isn't loaded.

**Comment by dhh** [comment]
See https://turbo.hotwired.dev/handbook/drive#redirecting-after-a-form-submission

**Comment by dhh** [comment]
Ah, I see. That sounds like a Turbo bug. Please open one over there with a test case if possible or minimal reproduction steps. Thanks!
