### ISSUE TITLE
Security: signed_stream_verifier_key initializer forces KeyGenerator to SHA1 rather than respecting Rail's actual defaults

### ISSUE THREAD

**Issue by aaronjensen** [hotwired/turbo-rails#325]
This is a nasty one that took some debugging, but essentially we discovered that when we added `turbo-rails` it signed everyone out. 

The reason is that `turbo-rails` inadvertently forces `Rails.application.key_generator` to use `SHA1`, rather than whatever is specified in `config.active_support.key_generator_hash_digest_class`. 

This happens because of [this initializer](https://github.com/hotwired/turbo-rails/blob/66ca1d7758ab271f3747a79a3a9be8a159357782/lib/turbo/engine.rb#L63-L66), which invokes `Rails.application.key_generator.generate_key`. 

That will create an `ActiveSupport::KeyGenerator` and that will use whatever is set in `ActiveSupport::KeyGenerator.hash_digest_class`, which defaults to `SHA1`. 

In Rails 7, the default for `hash_digest_class` was changed to `SHA256`, but this was done by setting `config.active_support.key_generator_hash_digest_class`, but that does not get copied over to `ActiveSupport::KeyGenerator.hash_digest_class` until [this initializer](https://github.com/rails/rails/blob/main/activesupport/lib/active_support/railtie.rb#L135-L141). Unfortunately, that initializer wraps the setting in an `after_initialize`, which means that it happens after `turbo-rails` has already instantiated the key generator with `SHA1`.

I believe that wrapping the `turbo.signed_stream_verifier_key` in an after initialize will fix it, though there will still be an order dependency. I don't know what the typical way of resolving that is, but I'm sure you all do.

In the interim, one can work around it by adding this to your `application.rb`:

```rb
ActiveSupport::KeyGenerator.hash_digest_class = OpenSSL::Digest::SHA256
```

In general the way it's done in Rails is probably too finicky, since it relies on multiple sources of truth there is temporal coupling. Likely that could be improved, but a fix in turbo rails is probably more direct and doable in the short term. It will probably invalidate all sessions though... 

Thanks!

**Comment by dhh** [comment]
cc @rafaelfranca, thoughts on this dependency situation?

**Comment by georgepalmer** [comment]
Great work @aaronjensen - just spent a few hours tracking down the same issue when upgrading to Rails 7 and struggling to work out why the cookies weren't changing given the change to SHA256.

Only thing to add is somebody upgrading to Rails 7 may add the cookie rotator as recommended by the upgrade guide, think its been live long enough and then remove it after a month (which was our plan).  If this gem is then updated to a version with a fix for this issue then everybody will then be logged out as the rotator will no longer be active.

**Comment by aaronjensen** [comment]
@dhh @rafaelfranca thoughts on this? Would a quick fix in turbo-rails make sense or does the whole thing need to be rethought?

**Comment by dhh** [comment]
Seems to me that wrapping `turbo.signed_stream_verifier_key` in an after_initializer should work and the timing should be OK because Rails' definitions will always run first. Please do pursue that. We can't do anything in Rails that would invalidate all sessions.

**Comment by aaronjensen** [comment]
@dhh thanks, that works for me: https://github.com/hotwired/turbo-rails/pull/335

**Comment by aaronjensen** [comment]
Thanks for the merge, @dhh. Looks like a release went out just before. Do you have an idea when you'll release again so I can remove my workaround? (I wish I could subscribe to releases...)
