### ISSUE TITLE
Links which specify a data-method have that method ignored

### ISSUE THREAD

**Issue by bhaibel** [hotwired/turbo-rails#33]
Let's say I have the following in a template:

```
<%= link_to "Sign out", signout_path, method: :delete %>
```

When I click on it, I'll get a routing error that seems to reflect the link having been visited with a `GET` rather than a `DELETE` request. I believe that this means that `turbo-rails` is not picking up on the `data-method` in the rendered link.

**Comment by dhh** [comment]
I thought we had already pulled this in from UJS, but guess not. @sstephenson thoughts on how to get this in?

Although an alternative would be to say that turning ahrefs into POSTs is a bit of an anti-pattern, especially for a11y reasons. Better to use button_to with a styling. I think that's why this didn't come up in HEY, since we've been removing links that mutate in part for a11y reasons.

But if that approach is followed, we clearly need to document it.

**Comment by dhh** [comment]
@seanpdoyle Any thoughts on the a11y aspect?

**Comment by bhaibel** [comment]
The a11y point is a really good one.

I think my preferred solution might be a two-part one:

**Comment by bhaibel** [comment]
The a11y point is a really good one.

I still think we should port the old rails-ujs behavior in, at least for now (maybe it gets a deprecation warning slapped on it?) -- my instinct is that `data-method` links suddenly Stopping Working is going to be a point of confusion & frustration for folks trying to transition from UJS to Turbo.

From a developer UX perspective, my long-term ideal might be something that *warns* the developer they are doing a stupid a11y thing, but that might not be worth the extra kb over the wire.

**Comment by seanpdoyle** [comment]
I agree, combining `link_to` and destructive HTTP Verbs is troublesome. From my perspective, the underlying mismatch between the semantics of a destructive action like an HTTP `DELETE` and an `<a>` element complicate the matter.

While the accessibility issues can be papered-over by declaring [role="link"](https://www.w3.org/TR/wai-aria-1.1/#link), it might still surprise users of assistive tech if clicking a link triggered anything but idempotent behavior.

> I still think we should port the old rails-ujs behavior in, at least for now (maybe it gets a deprecation warning slapped on it?) -- my instinct is that data-method links suddenly Stopping Working is going to be a point of confusion & frustration for folks trying to transition from UJS to Turbo.

I was reflecting on the same issue. I wonder if there is a bridge/polyfill of sorts that we could provide as part of `turbo-rails` that would map [Turbo events](https://turbo.hotwire.dev/reference/events) to [UJS events](https://guides.rubyonrails.org/v6.1/working_with_javascript_in_rails.html#rails-ujs-event-handlers). I think there's close overlap between:

* `turbo:before-visit` and `ajax:before`
* `turbo:before-fetch-request` and `
* `turbo:submit-start` and `ajax:send`
* `turbo:before-fetch-response` and `ajax:success` + `ajax:error` + `ajax:complete` (depending on the HTTP status in the response)

There isn't a total overlap, but I wonder if there is enough to provide our own [Form Submission lifecycle listeners](https://github.com/rails/rails/blob/master/actionview/app/assets/javascripts/rails-ujs/start.coffee#L34-L37) (plus [2 others](https://github.com/rails/rails/blob/master/actionview/app/assets/javascripts/rails-ujs/start.coffee#L62-L63)), while still re-using the majority of `Rails.start()`. I know that `Turbo.start()` is invoked during the `import` call, but maybe we can supplement applications with another module they can import and start as a polyfill of sorts.

> From a developer UX perspective, my long-term ideal might be something that warns the developer they are doing a stupid a11y thing, but that might not be worth the extra kb over the wire.

I've opened https://github.com/rails/rails/pull/40935 against rails/rails, and consider it a temporary bridge toward a long-term improvement. It doesn't warn the developer directly, but it tries to remedy the underlying issue.

**Comment by dhh** [comment]
[Documented the UJS compatibility](9d53529bedd4de19dea8521d415f40685dfe7749) and stopped removing it from a Webpack app by default.
