### ISSUE TITLE
Turbo Stream From and Browser Tabs

### ISSUE THREAD

**Issue by marcioniliolive** [hotwired/turbo-rails#338]
Hello to all turbo developers, first of all, thank you for having such an amazing tool.

But currently on my site, my users have reported something to me that I hadn't noticed yet. On my platform some data is transmitted via callback with the broadcast to the turbo-stream-from tag.

The problem is that the DOM update, and the insertion or updating of elements only happen when we are directly in the site's tab, if we go to another tab, for example, when we come back, all the items that should have been rendered there, all come from once!

**Comment by dhh** [comment]
That's unfortunately up to browsers. When they choose to suspend updates. I know Safari is more aggressive about this. Not aware of anything we can do as web developers about this.

**Comment by michelson** [comment]
@dhh I think this is a bug on Turbo. I have a chat an application that currently works on React. And we are porting all the stuff to hotwire. 

when the message is received and stimuls controller play a sound on initialize()

videos, please turn volume on.

**React version:**

https://github.com/hotwired/turbo-rails/assets/11976/bd259dc5-3d9e-43eb-8968-14f01e65d762

**Hotwire version**


https://github.com/hotwired/turbo-rails/assets/11976/cde88095-1065-4fbe-afba-0d1b86c4b528


ref: https://github.com/hotwired/stimulus/issues/731

**Comment by michelson** [comment]
now I'm trying to get a grasp on the code on Turbo. it seems that the issue could be in the stream_message_renderer which uses some sort of focusing 
https://github.com/hotwired/turbo/blob/main/src/core/streams/stream_message_renderer.js#L60
it seems like requestAnimationFrame is paused when the tab is inactive. I will keep investigating this.

**Comment by michelson** [comment]
@dhh note that I've replaced all the `nextRequestAnimation()` with `nextMicrotask()` and it works!

https://github.com/hotwired/turbo-rails/assets/11976/3f44324d-e303-4a09-9d50-3d104cc40b06

**Comment by michelson** [comment]
I have tried some things by replacing one by one and it seems that we should replace each call of nextAnimationFrame.

**Comment by enochtamulonis** [comment]
Nice! This seems like a great improvement to the library
