### ISSUE TITLE
Awkward behavior around redirects & error codes

### ISSUE THREAD

**Issue by bhaibel** [hotwired/turbo-rails#34]
I'm trying to Turboify an app which uses Devise.

When I try to sign out, I expect the following to happen.

1. Turbo sends an xhr request to the appropriate Devise controller.
2. Devise does its post-logout redirect.
3. Eventually, the redirect chain resolves to HTML containing the signin page.
4. That HTML gets returned in the xhr response.
5. Turbo renders the signin page.

Instead, the following happens:

1. Turbo sends an xhr request to the appropriate Devise controller.
2. Devise does its post-logout redirect.
3. Eventually, the redirect chain resolves to a bare 401, because *something* is autodetecting the XHR and deciding not to return HTML.
4. No content gets returned to the XHR response, just an error code.
5. Turbo doesn't render anything, because it got no HTML.
6. I click on literally any other link, or reload, or the like.
7. I am immediately redirected to the sign in page with an error.

For my use case, I can probably fix it by overriding the Devise redirect chain -- it's annoying, but not unsolvable.

However, I can see this kind of interaction being really confusing to a naive user. It doesn't really signal what the issue is, it's just a silent failure.

**Comment by dhh** [comment]
Would if Devise has something in place to detect all requests that come from fetch as XHR somehow, and then not do the HTML rendering if then? Maybe dive into that Devise chain and lets see if its something we have to fix there or if there's anything we can do on the turbo side.

**Comment by woto** [comment]
I remember that old [turbolinks/turbolinks-classic](https://github.com/turbolinks/turbolinks-classic) had special code for Devise:

> By default, Turbolinks includes itself in ActionController::Base. To opt out of the Turbolinks features in certain controllers (redirect_to behavior, request_method cookie, X-XHR-Referer referrer check, etc.), set config.turbolinks.auto_include to false in application.rb and include Turbolinks::Controller in the controllers where you use Turbolinks.

[And Devise even has some hint here on how to use it ](https://github.com/heartcombo/devise/blob/45b831c4ea5a35914037bd27fe88b76d7b3683a4/lib/generators/templates/devise.rb#L299)

Also temporary stucked with Devise redirects :)

**Comment by dhh** [comment]
You can now render on POST using either 4xx or 5xx status codes. In Rails, you'd do:

```ruby
    respond_to do |format|
      if @room.save
        format.html { redirect_to @room, notice: 'Room was successfully created.' }
        format.json { render :show, status: :created, location: @room }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
```

Part of 0.5.3.

**Comment by dhh** [comment]
Wups, posted on the wrong issue. But you can now opt out of Turbo processing using the data-turbo=false attribute. I believe that should probably solve this? Might want to add a doc note about it.

**Comment by miharekar** [comment]
In case someone lands here trying to get Devise working with Turbo - there's been several workarounds/improvements suggested on [Hotwire Discussion](https://discuss.hotwire.dev/t/forms-without-redirect/1606).

There's even a [GoRails video](https://gorails.com/episodes/devise-hotwire-turbo) with instructions.

**Comment by davegudge** [comment]
The responders used by Devise have been updated https://github.com/heartcombo/responders/pull/223 (pending a new release). Once released, the open PR for Devise can be finalised https://github.com/heartcombo/devise/pull/5340
