### ISSUE TITLE
`render` with non-200 status causing no layout and double loading of JS

### ISSUE THREAD

**Issue by kleinjm** [hotwired/turbo-rails#348]
## Context

Rails 7.0.2.4
Ruby 3.1.2
turbo-rails 1.1.1

I have a `forbidden` controller action that renders a page with a 403 response code.

```rb
  def forbidden(exception)
    @error_presenter = ErrorPresenter.new(status_code: :forbidden)

    # ...

    respond_to do |format|
      format.html { render(:base_error, status: :forbidden) } # this is the line in question
      format.all { head(:forbidden) }
    end
  end
```

## Issue

When navigating from another page in my app to this forbidden page, the page renders without a layout and there are a series of JS errors related to double loading.

![image](https://user-images.githubusercontent.com/2565158/173907433-358723f9-eb12-4373-8428-029b2a59a135.png)
(no formatting or layout)

![image](https://user-images.githubusercontent.com/2565158/173907068-26c25305-8b6d-47b3-a6dc-cb22e75c5e1a.png)

## Workarounds

There is no issue when,

1. Removing `import "@hotwired/turbo-rails";` in my JS pack file
2. Removing `status: :forbidden` from the `render` call

Neither of these workarounds are acceptable long term.

**Comment by dhh** [comment]
Fixed in Turbo head via https://github.com/hotwired/turbo/pull/483.
