### ISSUE TITLE
turbo_frame_tag produces <turbo-frame> tag only starting from the second declaration

### ISSUE THREAD

**Issue by OleksaRiabukha** [hotwired/turbo-rails#349]
Hi all, I’ve encountered a strange behaviour of `turbo_frame_tag` in Rails – it only adds `<turbo-frame>` tag starting from the second declaration in the .erb.html file.

I have a very basic .erb.html file for the new action:

```
<div>
  <h2>Add spending</h2
</div>
```

I’m trying to add turbo frame, for example,:
```
<div>
  <h2>Add spending</h2
  <%= turbo_frame_tag "new" do %>
    <div><h2>Hi for the first time</h2></div>
  <% end %>
</div>
```

The <turbo-frame> tag is not being added after above mentioned declaration. Produced html:

```
<div>
  <h2>Add spending</h2
  <div>
    <h2>Hi for the first time</h2>
  </div>
</div>
```

But if I’ll add another turbo_frame_tag, like:

```
<div>
  <h2>Add spending</h2
  <%= turbo_frame_tag "new" do %>
    <div><h2>Hi for the first time</h2></div>
  <% end %>
  <%= turbo_frame_tag "new2" do %>
    <div><h2>Hi for the second time</h2></div>
  <% end %>
</div>
```

The second <turbo-frame> tag will be produced correctly:

```
<div>
  <h2>Add spending</h2
  <div>
    <h2>Hi for the first time</h2>
  </div>
  <turbo-frame id=”new2”>
    <div>
      <h2>Hi for the second time </h2>
    </div>
  </turbo-frame>
</div>
```

All consecutive turbo_frame_tags will be added properly as well.

I’ve encountered such behaviour only on one page so far – the new.erb.html. For example, on index.erb.html the turbo_frame_tag is being produced starting from the first declaration.

Is it expected behaviour?

Rails 7.0.3, turbo-rails 1.1.1

**Comment by rayhanw** [comment]
@OleksaRiabukha Hi, I tested this in a fresh new small app. I noticed when I copied any of your examples that your `h2` tag (on line 2) is not closed properly. Which then causes the first turbo frame tag to not appear in the dom.
