### ISSUE TITLE
Combining turbo-streams with turbo-frames

### ISSUE THREAD

**Issue by diegomichel** [hotwired/turbo-rails#352]
Hello,

First, I love turbo-rails <3, thanks so much for this great work.

I wonder what are the best practices around `turbo-frame` and `turbo-stream` to prevent issues like an event arriving at the browser before a `turbo-frame` triggers a refresh on it.

So I have a page with a next and previous button that triggers a chart generator in our backend. The controls are inside of a `turbo-frame` along with a spinner. On the same action that serves this view, I also queue a background job that uses a `turbo-stream` to replace the spinner with the chart image.

The problem I have is that sometimes the background job sends the action cable event before the `turbo-frame` gets the new HTTP response, so the `turbo-frame` ends up replacing the div milliseconds after the `turbo-stream` event already did the same.

One solution I'm thinking of is to manage(controls, spinner) from `Stimulus` and remove the `turbo-frame`. But I wonder if there are other ideas.

Thanks,
Diego.

**Comment by pinzonjulian** [comment]
Hey Diego!
Have you tried posting your question in the official Hotwire Discuss https://discuss.hotwired.dev/ or in the StimulusReflex discord server https://discord.gg/stimulus-reflex (on the hotwire channel)?

Tag me in any of those and we can dig deeper into this and find a solution for you 🤘🏽

**Comment by diegomichel** [comment]
Awesome, thanks @pinzonjulian!
