### ISSUE TITLE
Style not being applied to tubo_frame_tag

### ISSUE THREAD

**Issue by spaquet** [hotwired/turbo-rails#354]
* Rails 7 (7.0.3) with esbuild and cssbuild
* Tailwind 3.1.4 with JIT
* Turbo Rails 7.1.3

When running in development mode part of the layout is not applied, while once the code is deployed to production the css styling is fully applied.
<img width="304" alt="Screenshot 2022-06-29 at 11 25 29 AM" src="https://user-images.githubusercontent.com/176050/176527094-d1028338-feac-42db-a5e2-829cf892f200.png">
vs
<img width="304" alt="Screenshot 2022-06-29 at 11 24 27 AM" src="https://user-images.githubusercontent.com/176050/176528074-7819fed8-c1fe-447e-838e-9673dd5aa491.png">

What is very disturbing is the fact that part of the layout is applied (background) and that most of the other elements are not styled at all when running the app in development mode.

**Comment by dhh** [comment]
Sounds like you're not running TW in watching mode. In any case, not a turbo consideration. Would be a TW one, if there is any issue.

**Comment by spaquet** [comment]
@dhh worse than that... While deploying to production I compiled the assets... and keep them compiled after for quite a bit.
That was the issue as compiled assets seem to be given the priority over JIT ;-)
Thx

**Comment by dhh** [comment]
That'll do it too! 😄✌️
