### ISSUE TITLE
How to access global `Turbo` object?

### ISSUE THREAD

**Issue by bborn** [hotwired/turbo-rails#36]
In installed by following the readme for an app using the asset pipeline (the install script adds `<%= turbo_include_tags %>` in my `head` element). 

But because that helper adds the turbo script as a module, the Turbo object isn't added to the global scope (and I can't do `Turbo.visit` programmatically). Am I missing something? What's the right way of accessing the `Turbo` object?

**Comment by dhh** [comment]
You have to use ESM style imports to get the class into your scope. There's no always-on global any more.
