### ISSUE TITLE
Using Hotwire turbo-rails with Alpine without StimulusJS 

### ISSUE THREAD

**Issue by iamonkara** [hotwired/turbo-rails#365]
Just starting with Rails7, I wonder is it possible to use turbo-rails with Alpine JS without

1. any StimulusJS or
2. any conflicts with StimulusJS

I have looked into [Alpine Turbo Drive Adapter 1](https://github.com/SimoTod/alpine-turbo-drive-adapter) issues that mentioned edge cases where component updates (using either turbo-frame or turbo-stream) may sometimes cause Alpine attributes (x-*) to not work.

Wondering if anyone here has successfully used Hotwire with AlpineJS either without needing StimulusJS or without having conflicts?

FYI, I have asked the same question in the discussion forum [here](https://discuss.hotwired.dev/t/using-hotwire-with-alpine-without-stimulusjs/4332) , so please feel free to answer in the forum if this is not a the right place.

**Comment by marcelolx** [comment]
@iamonkara I think we can close this issue, the appropriate place to discuss this is the forum, and from what I can see you already got a response there https://discuss.hotwired.dev/t/using-hotwire-with-alpine-without-stimulusjs/4332/2!

BTW, I think you should be able to use Turbo without needing StimulusJS

**Comment by marcoroth** [comment]
Hey @iamonkara, did you try to use Alpine with Stimulus and if so, were you successful?
