### ISSUE TITLE
Uncaught DOMException and TypeError when passing username:password in URL

### ISSUE THREAD

**Issue by evaneykelen** [hotwired/turbo-rails#366]
When passing HTTP Basic Authentication credentials e.g. `http://a:b@localhost:5000/` then two console errors are thrown.

The first is `Uncaught DOMException: Failed to execute 'replaceState' on 'History': A history state object with URL 'http://localhost:5000/' cannot be created in a document with origin 'http://localhost:5000' and URL 'http://a:b@localhost:5000/'.`

Notice the difference between *origin* and *URL* in the last part of the error message.

Likely as a result of the first error, a second error is thrown: `Uncaught TypeError: Cannot read properties of undefined (reading 'href').`

While using this Basic Authentication feature is discouraged, it is a valid URL construct that perhaps should be supported.

**Comment by marcoroth** [comment]
Possible duplicate of: https://github.com/hotwired/turbo/issues/536

**Comment by brunoprietog** [comment]
Closing as duplicate
