### ISSUE TITLE
data-disable-with

### ISSUE THREAD

**Issue by jakehockey10** [hotwired/turbo-rails#37]
Hello,

I thought I had read something about data-disable-with related to turbo-rails, but I can't find it in my history anywhere.  I notice that `data: { disable_with: '...' }` doesn't seem to work anymore when making the transition to turbo-rails from turbolinks and rails-ujs.

I wasn't quite sure what made data-disable-with work in the past, but I'm assuming it was rails-ujs since it doesn't seem to be related to turbolinks and the only other thing I removed to make way for turbo-rails was rails-ujs.

Are we planning on having data-disable-with functionality restored?  Or is this something we should implement ourselves from here on out?

I've really enjoyed learning about the new magic, thanks for all the efforts!

**Comment by jakehockey10** [comment]
I found where I had read something that mentioned data-disable-with and turbo in the same conversation.  I wasn't able to find anything beyond these mentionings:

https://discourse.stimulusjs.org/t/stimulus-and-rails-ujs/587/10
https://discuss.hotwire.dev/t/are-transitions-and-animations-on-hotwire-roadmap/1547/3

**Comment by dhh** [comment]
[Documented the compatibility with turbo-rails and UJS](9d53529bedd4de19dea8521d415f40685dfe7749). And we've also stopped taking UJS out when using the Webpack installer.

**Comment by jakehockey10** [comment]
The link above didn't work for me, but here is where I found the documentation you mention: https://github.com/hotwired/turbo-rails#compatibility-with-rails-ujs

**Comment by coorasse** [comment]
Also, seems duplicate of https://github.com/hotwired/turbo/issues/55
