### ISSUE TITLE
Problem when re-rendering forms

### ISSUE THREAD

**Issue by stephannv** [hotwired/turbo-rails#377]
I don't know if this is a problem with turbo or turbo rails. Turbo is showing the old page content when visiting the page again.

https://user-images.githubusercontent.com/3025661/186770118-562a82d1-ed24-4d2c-b25f-3d92798d25c4.mov

Steps to reproduce:
1. submit a form from page A
2. after a redirection, go back to page A
3. The old Page A will flash and disappear.

On video I'm using a form with error to make it clearer that it is showing old screen content. I created a repository to make it easier to reproduce the bug.
https://github.com/stephannv/turbobug

When I set `data: { turbo: false }` to "new post" link, the error doesn't happen.

Rails 7.0.3.1
Turbo-rails gem 1.1.1
@hotwired/turbo-rails 7.1.3
@hotwired/turbo 7.1.0

**Comment by seanpdoyle** [comment]
Thank you for opening this issue!

Have you tried to reproduce this behavior with builds that are part of the upcoming 7.2.0 release?

I tried to reproduce this locally and was unable to after making these changes:

```diff
diff --git a/package.json b/package.json
index a9eb0ae..a874679 100644
--- a/package.json
+++ b/package.json
@@ -3,7 +3,7 @@
   "private": "true",
   "dependencies": {
     "@hotwired/stimulus": "^3.1.0",
-    "@hotwired/turbo-rails": "^7.1.3",
+    "@hotwired/turbo-rails": "hotwired/turbo-rails.git#turbo-7-2-0",
     "esbuild": "^0.15.5"
   },
   "scripts": {
diff --git a/yarn.lock b/yarn.lock
index 2dc205d..a1d9958 100644
--- a/yarn.lock
+++ b/yarn.lock
@@ -12,18 +12,17 @@
   resolved "https://registry.yarnpkg.com/@hotwired/stimulus/-/stimulus-3.1.0.tgz#20215251e5afe6e0a3787285181ba1bfc9097df0"
   integrity sha512-iDMHUhiEJ1xFeicyHcZQQgBzhtk5mPR0QZO3L6wtqzMsJEk2TKECuCQTGKjm+KJTHVY0dKq1dOOAWvODjpd2Mg==
 
-"@hotwired/turbo-rails@^7.1.3":
-  version "7.1.3"
-  resolved "https://registry.yarnpkg.com/@hotwired/turbo-rails/-/turbo-rails-7.1.3.tgz#a4e04ecb800a06e7f9aa6e298170fa4580b74216"
-  integrity sha512-6qKgn75bMWKx0bJgmSfrdC73EJkGLoSWZPAssvcd3nE7ZpDZff6f67j5OQNjjpRgNB7OFruom6VWguGQGu1fQg==
+"@hotwired/turbo-rails@hotwired/turbo-rails.git#turbo-7-2-0":
+  version "7.2.0-beta.2"
+  resolved "https://codeload.github.com/hotwired/turbo-rails/tar.gz/717978b7bcc33a9566fc71d136858204ef3a3aeb"
   dependencies:
-    "@hotwired/turbo" "^7.1.0"
+    "@hotwired/turbo" "^7.2.0-beta.2"
     "@rails/actioncable" "^7.0"
 
-"@hotwired/turbo@^7.1.0":
-  version "7.1.0"
-  resolved "https://registry.yarnpkg.com/@hotwired/turbo/-/turbo-7.1.0.tgz#27e44e0e3dc5bd1d4bda0766d579cf5a14091cd7"
-  integrity sha512-Q8kGjqwPqER+CtpQudbH+3Zgs2X4zb6pBAlr6NsKTXadg45pAOvxI9i4QpuHbwSzR2+x87HUm+rot9F/Pe8rxA==
+"@hotwired/turbo@^7.2.0-beta.2":
+  version "7.2.0-beta.2"
+  resolved "https://registry.yarnpkg.com/@hotwired/turbo/-/turbo-7.2.0-beta.2.tgz#b05364e34078bef511dcddf11f8058ffe560ae26"
+  integrity sha512-fXkSOAOupGpP8wqD21JGCyBWjE1kKgOcpC3U0mVN7mbxBT8TjsLslTCguPZFPB7aZdi3YKbIwjulGggeAXsdHg==
 
 "@rails/actioncable@^7.0":
   version "7.0.3"

```

**Comment by stephannv** [comment]
Thank you very much @seanpdoyle. I upgraded with `yarn add hotwired/turbo-rails.git#turbo-7-2-0` and the problem is gone.

**Comment by stephannv** [comment]
@seanpdoyle the upgrade to `turbo-7-2-0` solved partially the problem. Now, if I don't submit the form with valid data, just go back to list, and acess again posts, the error will flash and disappear.
I upgraded my [repo](https://github.com/stephannv/turbobug) to use turbo-7-2-0, updated the "Steps to reproduce"
<img width="1876" alt="Screen Shot 2022-08-30 at 11 05 41" src="https://user-images.githubusercontent.com/3025661/187458481-f53540f1-5c55-4397-b455-fa0586236486.png">

This video shows the bug:

https://user-images.githubusercontent.com/3025661/187459400-a44df7fa-4248-426b-9a67-51c67e181c38.mov

**Comment by seanpdoyle** [comment]
@stephannv thank for you providing more information.

As I understand the behavior you're describing, it's working as intended.

From the Rails server's perspective, the flash message is ephemeral. However, once it's present in the document, Turbo has no way of distinguishing it from other cache-ready content.

When Turbo handles a destructive form submission (one that isn't a `GET`), Turbo disposes of the cache. In the video you shared, there aren't any destructive form submissions, only `GET`-driven navigations.

If you don't want the flash message to persist in the cache, you can set [`[data-turbo-cache="false"]` on the element](https://turbo.hotwired.dev/reference/attributes) to exclude it.

**Comment by stephannv** [comment]
Understood, @seanpdoyle. Thanks for explaning. I set `<form data-turbo-cache="false">` and solved the problem. I'm closing this issue as this is not a bug.
