### ISSUE TITLE
NoMethodError: undefined method `eager_load!' for Hotwire:Module error

### ISSUE THREAD

**Issue by timmyd87** [hotwired/turbo-rails#38]
Only getting the above error when I try and deploy to production, and works fine in development. It may be something that's conflicting, i've disabled the old turbolinks and UJS import and start, using turbo in the asset pipeline...any clues on where i should start to look to fix this? - turning off eager loading allows the app to launch

**Comment by dhh** [comment]
Been fixed in latest hotwire release 👍
