### ISSUE TITLE
Passing local variable in turbo stream for partial

### ISSUE THREAD

**Issue by gabrielboeker** [hotwired/turbo-rails#381]
Right now something like this:

```
<%= turbo_stream.replace "task_checkbox" do %>
<%= render partial: "projects/partials/task_checkbox", locals: { form: form, task: task } %>
<% end %>
```

results in an no method error because the local variables `form` and `task` (both are coming from a form and iteration which is wrapped around the original partial) are not being passed. Do i miss something or is it not possible to pass local variables in and to turbo streams?

**Comment by marcoroth** [comment]
Hey @gabrielboeker, thanks for opening this issue!

As long as the `form` and `task` locals are available in this scope you should also be able to pass them along to another render call, there shouldn't be anything about it.

Though, there is even a way to further improve your snippet. This should also work:

```erb
<%= turbo_stream.replace "task_checkbox", partial: "projects/partials/task_checkbox", locals: { form: form, task: task } %>
```

**Comment by gabrielboeker** [comment]
Hey @marcoroth, thanks for your response!
Indeed, I thought so, but yet it does not work weirdly.

> Though, there is even a way to further improve your snippet. This should also work:
>` <%= turbo_stream.replace "task_checkbox", partial: "projects/partials/task_checkbox", locals: { form: form, task: task } %>`

And yes, thats another way to do it; I actually have it done like this before but found it not as readable :)

**Comment by marcoroth** [comment]
Hmm, so the snippet you shared is a partial itself? Where and how are you calling that partial then?

**Comment by gabrielboeker** [comment]
In my app I have projects which have many tasks. The tasks are iterated through on the projects show page:

```
### Project#show 

 <% @tasks.each do |task| %>
    <tr class="cursor-pointer">
       <td class="px-6 pr-3 py-4 w-12">

         <%= form_with(...) do |form| %>
           <div id="task_checkbox_<%= task.id %>">
              <%= render partial: "projects/partials/task_checkbox", locals: { form: form, task: task } %>
           </div>
         <% end %>

       </td>
   </tr>
<% end %>
```

And the partial thats called is:
```
### Partial: projects/partials/_task_checkbox.html.erb

<%= form.label :done, value: false, class:"block whitespace-nowrap" do %>
<%= form.radio_button(:done, false, class:"hidden", onchange: "this.form.requestSubmit()") %>
  <p>Radio Button Label</p>
<% end %>
```

**Comment by marcoroth** [comment]
I assume this is your `tasks/update.turbo_stream.erb` then?
```erb
<%= turbo_stream.replace "task_checkbox" do %>
  <%= render partial: "projects/partials/task_checkbox", locals: { form: form, task: task } %>
<% end %>
```

In that case you would either need to build another `form` object around it in that view so you can pass it to the partial call or you need to restructure your view/partials to need duplicate that code.

It would probably make sense to have a partial for the table row itself, in `projects/partials/_task_row.html.erb`:
```erb
<tr class="cursor-pointer" id="<%= dom_id(task, :task_row) %>">
  <td class="px-6 pr-3 py-4 w-12">
    <%= form_with(...) do |form| %>
      <div id="<%= dom_id(task, :task_checkbox) %>">
        <%= render partial: "projects/partials/task_checkbox", locals: { form: form, task: task } %>
      </div>
    <% end %>
  </td>
</tr>
```

which then allows you to restructure your `projects/show.html.erb` as:
```erb
<%= render partial: 'projects/partials/task_row', collection: @tasks %>
```

And in your `tasks/update.turbo_stream.erb` you can then just do (where `@task` would be still be set from your controller action):
```erb
<%= turbo_stream.replace dom_id(@task, :task_row) do %>
  <%= render partial: "projects/partials/task_row", locals: { task: @task } %>
<% end %>
```

I hope this helps!

**Comment by gabrielboeker** [comment]
Thanks for your help! weirdly your solution did not work as expected but with a little tweaking it did! Here is my code:

```
#### The Projects#show iteration

<% @tasks.each do |task| %>
    <%= render "projects/partials/task_row",  task: task %>
<% end %>
```
Here I removed the collection since it lead to an error ... to be honest i have no idea why since it would only make sense that it works with your syntax, but it does with mine now.

The rest is the same as you did.. I have no idea why it did not work in the first place.

Weirdly something different happens now, even if it is not related to the initial problem (which is solved thanks to you!). Now I have got multiple rows of tasks I can check, but if I check row no 2 (with ID `task_row_task_2`) it is checking row no 1 :D what is happening ?

**Comment by marcoroth** [comment]
It's kinda hard to tell without seeing the whole thing, but it's shouldn't be related to an instance variable vs local variable. Your view gets rendered out to HTML and your browser doesn't know anything about how you generated that HTML.

But my guess is that you are submitting the form every time you change the value of the radio button, with this attribute: `onchange: "this.form.requestSubmit()"`

**Comment by gabrielboeker** [comment]
Indeed. And yes that is how i simulate some kind of ajax behavior. it usually does work well for single records (eg changing the project status on the project show page). Since there are multiple forms (one for every row) I think its weird, that id behaves like that. Will investigate a bit further.
