### ISSUE TITLE
Broadcasting doesnt update the status 

### ISSUE THREAD

**Issue by a14guguliye** [hotwired/turbo-rails#385]
Hello All,
I created a mobile app that sends the POST request to the server in order to save the record and the record is being saved successfully. No issues for now.
However, I want the record to be updated on the screen as soon as it gets saved, so I decided to use the Turbo Streams technology, Ruby on Rails. 
In order to achieve the purpose, I created the below broadcast:

    class PatientHistory < ApplicationRecord after_create_commit - >{
        broadcast_prepend_to "patienthistories",
        partial: "partials/patienthistory",
        locals: {
            ph: self
        }
    }
    end

Moving ahead, in the partials path which is located under app/views/partials/_paienthistory.html.erb, I have the below code:

        <turbo-stream action="prepend" target="patienthistories">
       <template>
          <%=turbo_frame_tag "patienthistory_#{ph.id}" do %>
             <tr>
                <td>
                   some data
                </td>
                <td>
                   some data
                </td>
                <td>
                   some data
                </td>
                <td>
                   some data
                </td>
                <td>
                   some data
                </td>
                <td>
                   some data
                </td>
             </tr>
             <% end %>
       </template>
    </turbo-stream>

and I want the new <tr> tag to be added by the table in located on the views/admin/patientloshistory.html.erb. And the view is as below:
<%=turbo_stream_from "patienthistories" %>
      <section class="main_container flex_display">
        <%=render "partials/adminsidenavbar" %>
          <section class="adminlog_container flex_display flex_direction_column">
            <section class="adminlog_header">
              <div class="adminlog_title_holder">
                <h1>
                  PATIENT LOG LIST
                </h1>
              </div>
              <div class="adminlog_title_info">
                <span>
                  Below admin will see patient log data
                </span>
              </div>
            </section>
            <section class="adminlog_table_container">
              <%=t urbo_frame_tag "patienthistories" do %>
                <table class="adminlog_table" id="patienthistories">
                  <thead>
                    <tr>
                      <th>
                        Name/Surname
                      </th>
                      <th>
                        Start Location
                      </th>
                      <th>
                        Stop Location
                      </th>
                      <th>
                        Start Time
                      </th>
                      <th>
                        Stop Time
                      </th>
                      <th>
                        UID
                      </th>
                      <th>
                        Doctor
                      </th>
                    </tr>
                  </thead>
                  <tbody>
                    <% @patientHistories.each do |ph| %>
                      <%=t urbo_frame_tag dom_id(ph) do %>
                        <tr>
                          <td>
                            data
                          </td>
                          <td>
                            data
                          </td>
                          <td>
                            data
                          </td>
                          <td>
                            data
                          </td>
                          <td>
                            data
                          </td>
                          <td>
                            data
                          </td>
                          <td>
                            data
                          </td>
                        </tr>
                        <% end %>
                          <% end %>
                  </tbody>
                </table>
            </section>
          </section>
      </section>

Although my web server shows that the data is being transmitted, it is not updated on the screen:

> [ActionCable] Broadcasting to patienthistories: "<turbo-stream action=\"prepend\"
> target=\"patient_histories\"><template><turbo-stream
> action=\"prepend\" target=\"patienthistories\">\n<template>\n\n   
> <turbo-frame id=\"patienthistory_20234\">\n<tr>\n\t\t\t\t\t<td>Qulu
> Quliyev</td>\n                                       
> <td>\n\t\t\t\t\t\n\t\... Completed 200 OK in 17ms (Views: 0.3ms |
> ActiveRecord: 2.5ms | Allocations: 6605)
> 
> 
> Turbo::StreamsChannel transmitting "<turbo-stream action=\"prepend\"
> target=\"patient_histories\"><template><turbo-stream
> action=\"prepend\" target=\"patienthistories\">\n<template>\n\n   
> <turbo-frame id=\"patienthistory_20234\">\n<tr>\n\t\t\t\t\t<td>Qulu
> Quliyev</td>\n                                       
> <td>\n\t\t\t\t\t\n\t\... (via streamed from patienthistories)
> Turbo::StreamsChannel transmitting "<turbo-stream action=\"prepend\"
> target=\"patient_histories\"><template><turbo-stream
> action=\"prepend\" target=\"patienthistories\">\n<template>\n\n   
> <turbo-frame id=\"patienthistory_20234\">\n<tr>\n\t\t\t\t\t<td>Qulu
> Quliyev</td>\n                                       
> <td>\n\t\t\t\t\t\n\t\... (via streamed from patienthistories)

can someone please help why that happens?

**Comment by airblade** [comment]
As a first step, I would remove the `<turbo-steam>` and `<template>` tags from your partial.  The `broadcast_prepend_to` method in your model will take care of the turbo stream part.

**Comment by a14guguliye** [comment]
Issue can be closed
