### ISSUE TITLE
Cannot `importmap pin` from several CDNs

### ISSUE THREAD

**Issue by zarqman** [hotwired/turbo-rails#397]
I'm noticing some unexpected behavior when trying to pin `@hotwired/turbo-rails` in a Rails 7 app:
```
$ bin/importmap pin @hotwired/turbo-rails --from jsdelivr
Couldn't find any packages in ["@hotwired/turbo-rails"] on jsdelivr

$ bin/importmap pin @hotwired/turbo-rails --from skypack
Couldn't find any packages in ["@hotwired/turbo-rails"] on skypack

$ bin/importmap pin @hotwired/turbo-rails --from unpkg
Couldn't find any packages in ["@hotwired/turbo-rails"] on unpkg

$ bin/importmap pin @hotwired/turbo-rails --from jspm
Pinning "@hotwired/turbo-rails" to https://ga.jspm.io/npm:@hotwired/turbo-rails@7.2.4/app/javascript/turbo/index.js
Pinning "@hotwired/turbo" to https://ga.jspm.io/npm:@hotwired/turbo@7.2.4/dist/turbo.es2017-esm.js
Pinning "@rails/actioncable/src" to https://ga.jspm.io/npm:@rails/actioncable@7.0.4/src/index.js
```

As can be seen, it works with JSPM, but not the other 3 CDNs. Other packages (like `@hotwired/stimulus`) work just fine.

I also tried pinning the individual dependencies. `@rails/actioncable` works fine. However, `@hotwired/turbo` has the same issue, so the problem might be in `turbo` instead of `turbo-rails`.

It also could be an `importmap-rails` issue, but since some packages work from all CDNs, I thought I'd start here.

Let me know if I've missed something or there's other information I can provide.

**Environment**
Ruby 3.0.4
Rails 7.0.4
importmap-rails 1.1.5

**Comment by dhh** [comment]
Why are you trying to pin turbo-rails? It's included in this gem, so you can reference it directly. These two lines from the installer do the work: https://github.com/hotwired/turbo-rails/blob/main/lib/install/turbo_with_importmap.rb#L4-L5
