### ISSUE TITLE
Feature request: Set a variable of @broadcasted? as a partial local by default for any broadcast_* method?

### ISSUE THREAD

**Issue by nickjj** [hotwired/turbo-rails#405]
It's really nice to be able to broadcast new updates, such as appending a new comment to the end of a list but there's a really popular use case of sometimes wanting to show that a resource has new content without disrupting the user's UI with a flurry of new items.

For example, Discourse (the forum) will show a `See 3 new or updated topics` message at the top of the list as new topics are created in between page loads and that sentence is clickable. When you click it the DOM is modified to show the new topics. Also as new topics get created which aren't shown that number increments. The page's `<title>` also gets updated with a `(3)`.

We can build all of this with Turbo.

I thought about how to create that feature with Turbo and arrived at having an instance variable of `@broadcasted?` which I set to `true` when I broadcast the message. Then the template has a condition that shows that message if it's true.

Implementing this is easy enough since it's just passing a boolean but is something like this a common enough request where having access to that variable by default is worth it? It would be true and available when broadcasted and it could also support being set manually in case you wanted to override it for a specific use case.

**Comment by dhh** [comment]
I like that UI pattern. Could you show the full code of what you have in mind? I'm having trouble seeing where this broadcasted? predicate is set and reset?

**Comment by nickjj** [comment]
Hi,

I'll admit this UI feature end to end isn't as easy as I thought when I originally posted it, I posted it using wishful thinking of how it might work but I did put together a working example, at least around the context of the `broadcasted` variable.

Here is working code taken from the app I'm building:

`app/models/answer.rb`:

```rb
class Answer < ApplicationRecord
  # I hard coded the target (it's a work in progress) because I'm still
  # new to Turbo and haven't figured out how to set the ID dynamically yet.
  broadcasts_to ->(answer) { [answer.question, :answers] }, target: "question_549_answers", partial: "courses/answers/answer", locals: { broadcasted: true }
end
```

`app/views/courses/questions/show.html.erb`:

```erb
<ul id="<%= "#{dom_id(@question)}_answers" %>">
  <%= render partial: "courses/answers/answer", collection: @answers, as: :answer %>
</ul>
```

`app/views/courses/answers/_answer.html.erb`:

```erb
<% if broadcasted ||= false %>
  <li>
    See 3 new or updated topics
  </li>
<% else %>
  <li id="<%= dom_id(answer) %>">
    The real partial's content that shows an answer (sort of like a GitHub issue comment)
  </li>
<% end %>
```

This is far from a fully working end to end solution for the UI feature but it does demonstrate the usage of the `broadcasted` variable.

The feature request idea would modify `turbo-rails` to auto-inject `locals: { broadcasted: true }` as a local for when you use a partial. This way your partial has access to it if you want. If you don't want to use it then you don't need to reference it in your template. Also if you didn't want this behavior by default you would be free to set `locals: { broadcasted: false }` to override it. It would also allow us to get rid of the `||= false` part of the condition since it would always be defined.

The minor quality of life improvement here is not having to set that local manually in your `broadcasts_*` methods. Maybe it's bordering on the line of too much magic tho? Although having a way to detect if a message was broadcast seems useful to have built into the library. A broadcasted message is different than rendering it in a `create.turbo_stream.erb` from a controller action.

**Comment by dhh** [comment]
Hmm, I get where this is coming from, but I think it's too magic. I think you're better off doing as you're doing when it's needed.
