### ISSUE TITLE
No way to link_to method: :patch within a form

### ISSUE THREAD

**Issue by creativetags** [hotwired/turbo-rails#406]
My layout requires a button that links to an action with PATCH method inside another form. I can't see a way to do this anymore with Turbo. button_to inside an existing form generates a 2nd CSRF token which breaks on submit "Can't verify CSRF token authenticity". link_to tries GET instead.

I've tried:

button_to 'Verify', verify_path, method: :patch
link_to 'Verify', verify_path, method: :patch
link_to 'Verify', verify_path, data: { turbo_method: :patch }

Prior discussion [1](https://github.com/hotwired/turbo-rails/issues/89), [2](https://github.com/hotwired/turbo-rails/issues/33), [3](https://github.com/hotwired/turbo-rails/issues/50)

**Comment by creativetags** [comment]
I found a workaround. In the form add `data: { turbo: false }` to disable Turbo 

then use `button_to 'Verify', verify_path, method: :patch` instead of `data: { turbo_method: :patch }`

I don't have @rails/ujs installed

**Comment by dhh** [comment]
You can't have nested forms. Turbo creates a form when you use a custom `method:` on a link/button.
