### ISSUE TITLE
Breaking change in 7.2, when frame response is 4xx, 5xx OR if frame is missing

### ISSUE THREAD

**Issue by cabgfx** [hotwired/turbo-rails#407]
On updating from Turbo 7.1.x to to 7.2.x, via turbo-rails, we were quite surprised to see frames suddenly doing full-page redirects on failures, ie. for a 4xx or 5xx response.

I'm aware of hotwired/turbo#445, and the reasoning behind the `turbo:frame-missing` event, quite useful!

However, the changes introduced in hotwired/turbo#693, where Turbo now transforms 4xx and 5xx responses to full-page `Visit`s, feel like a breaking change. The minor version bump from 7.1 to 7.2 certainly broke our app 😅

I've read up on the discussion in hotwired/turbo#670, and noticed this sentiment by @seanpdoyle :

> Scenarios like this make me nervous about breaking the https://github.com/hotwired/turbo/issues/94#issuecomment-756968205 that a navigation within a frame will stay within a frame.

I believe the changes introduced in 7.2 specifically break that “promise”: _a navigation within a frame will stay within a frame_

**Are hotwired Rails apps now required to add additional/custom JS to handle this scenario by default?**

And, if so, should this repo add the necessary JS to handle this, upon doing `./bin/rails turbo:install` ?
Or am I simply misunderstanding something? (quite possible!)

I'm raising the issue here, instead of hotwired/turbo, as I'm mostly trying to find out how to fix this going forward, and perhaps help other newbies like myself.

---

Related:

- Issue #404 
- A minimal test app that reproduces my issue: https://github.com/cabgfx/turbo72-repro

**Comment by brunoprietog** [comment]
I agree, this drastically changes behavior. Even if a Turbo frame takes a while to load, Turbo also does a page redirect. I had to add event listeners to handle these cases, which is not desirable.

**Comment by dhh** [comment]
We have some thoughts on how to improve this behavior going forward, but in any case, we can't do anything from this repo. Discussion needs to happen on the turbo repo.
