### ISSUE TITLE
Turbo form request is showing plain HTML

### ISSUE THREAD

**Issue by OfficialVreesie** [hotwired/turbo-rails#414]
Hi all, I am having a problem with the turbo-rails gem. First I installed the latest version in my Rails 7 application. On my site, I have a select input which is wrapped in a form, with a partial below that form that shows the data. Now I want to apply a filter using the select and dynamically update the data using this turbo-rails package. My form html looks like this:
```
<div class="users">
    <div class="filters">
        <%= form_with(url: '/users/load', method: :get) do |form| %>
            <%= render partial: "shared/select", locals: {
                placeholder: 'Gender', 
                width: '90px', 
                options: @genders,
                classes: 'filter',
                name: 'gender',
            } %>
            <%= form.submit %>
        <% end %>
    </div>

    <div id="user-data-list">
        <%= render partial: "users/user_list", locals: {
            users: @users
        } %>
    </div>
</div>
```

In my routes, I created this get request which is forwared to a `load` method in my controller like this:
```
get '/users' => "users#index"
get '/users/load' => "users#load"
```

And then in my controller I have the 2 methods written like this:
```
class UsersController < ApplicationController

    before_action :require_user

    USERS_PER_PAGE = 15

    def index
        @genders = ["Male", "Female"]
        @users = User
                            .limit(USERS_PER_PAGE)
                            .order(:creation_date).reverse_order
    end

    def load
        @users = User
                            .limit(USERS_PER_PAGE)
                            .order(:creation_date).reverse_order
                            
        if params[:gender]
            @users = @users.where(gender: params[:gender])
        end

        render turbo_stream: turbo_stream.replace(
            "user-data-list",
            partial: 'users/user_list',
            locals: { users: @users }
        )
    end
end
```

The problem is that when I go to this page, select a gender and hit the submit button, I get plain HTML on my screen. This is the output:
```
<turbo-stream action="replace" target="user-data-list"><template>

<!-- LIST WITH ALL USERS BASED ON SELECTED GENDER --!>

</template></turbo-stream>
```

I want to use the turbo-streams instead of the turbo frames, and the request seems okay, because the content is correct, but why is it not rendering the content in the page, instead of showing the plain HTML. I don't know if this is relevant, but I upgraded from Rails 6 to Rails 7, so it wasn't a clean install, but I did follow the steps to install this package.

Can someone help me fix this?

**Comment by dhh** [comment]
Turbo does not currently support parsing turbo streams in response to GET. You need to use POST.
