### ISSUE TITLE
turbo_frame_tag update affecting Chartkick outside the frame

### ISSUE THREAD

**Issue by philsmy** [hotwired/turbo-rails#416]
Sorry, not quite sure how to word the title. But essentially:

A Rails 7.0.4 demp app (using the latest turbo-rails) with a very simple model and index page that contains the list of objects inside the `turbo_frame_tag`. There is a `Chartkick` chart _outside_ the frame in another part of the page. 
Refreshing doing a form-driven update of the turbo frame causes the Chart to lose its content.

It is exactly the same as described in issue #125 (which was closed almost 2 years ago).

I have a repository here that shows the error: https://github.com/philsmy/hotwire_demo

**Comment by BroiSatse** [comment]
@philsmy Just encounter very similar issue. After some digging in, it seems that chartkick is listening to `turbo:before-render` hook and calling `Chartkick.destroyAll()`. This will affect all the charts, even the ones outside of the frame.

What's more, recent changes caused inline script tags to execute before `turbo:before-render`, meaning that graphs inside the frame are destroyed as soon as they're created - I will raise another issue for this one.

Anyway, there's an option to disable autoDestroy with `Chartkick.config.autoDestroy = false`, but you'd need to handle destroying deleted graphs by yourself.

**Comment by brunoprietog** [comment]
Closing this since it's a Chartkick issue.
