### ISSUE TITLE
Installation instructions should include data-turbo-track

### ISSUE THREAD

**Issue by justinko** [hotwired/turbo-rails#43]
Should the installation instructions include changing:

```
<%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
```

to

```
<%= javascript_pack_tag 'application', 'data-turbo-track': 'reload' %>
```

?

**Comment by justinko** [comment]
Ah, I'm seeing this in the handbook. Closing.

<img width="927" alt="image" src="https://user-images.githubusercontent.com/14007/103161926-794a7c80-47a6-11eb-8e0d-c63e89afd9ce.png">

**Comment by richjdsmith** [comment]
I had to google this to find this specific thread. I think it might be useful thinking about adding this to turbo-rails.
