### ISSUE TITLE
How to detect when Turbo Stream broadcast is established?

### ISSUE THREAD

**Issue by evgenyneu** [hotwired/turbo-rails#434]
In my Rails view I call `turbo_stream_from` view helper to establish turbo stream web socket connection:

```
<%= turbo_stream_from :my_broadcast %>
```

Is there a way for know when the web socket connection was established using JavaScript in the browser? Does @hotwired/turbo-rails JavaScript library allow to set a callback or subscribe to an event to detect the WebSocket initiation?

**Comment by marcoroth** [comment]
@kevinmcconnell recently just merged in https://github.com/hotwired/turbo-rails/pull/430 which should help in this regard!

**Comment by evgenyneu** [comment]
@marcoroth good timing, this is exactly what I wanted. In my case I don't even need to write the observer, because my Cypress UI will do it for me.

**Comment by marcoroth** [comment]
Even better! This is similar to how it's being done in the test suite itself:

https://github.com/hotwired/turbo-rails/blob/421884bc1e7808c7076a1703e422add5e4d8bfd6/test/system/broadcasts_test.rb#L42-L44
