### ISSUE TITLE
cannot import StreamActions from "@hotwired/turbo-rails"

### ISSUE THREAD

**Issue by koenhandekyn** [hotwired/turbo-rails#441]
we have an application that uses importmaps where we use "@hotwired/turbo-rails"

currently the turbo-rails package seems to export only Turbo and cable, so we don't seem to be able to import StreamActions from it.

this feels like a 'bug' and probably turbo-rails should export all exported items from turbo. 

our quick patch was this change in the index.js from turbo-rails

```
import * as Turbo from "@hotwired/turbo"
import { StreamActions } from "@hotwired/turbo"
export { Turbo, StreamActions }
```

**Comment by marcoroth** [comment]
Hey @koenhandekyn, `@hotwired/turbo-rails` exports everything from `@hotwired/turbo` already. This is what the `Turbo` export is. So if you want to access the `StreamActions` it would be:

```js
import { Turbo } from "@hotwired/turbo-rails"

// and then
Turbo.StreamActions

// or if you want to directly access the `StreamActions` object:
import { Turbo } from "@hotwired/turbo-rails"
const { StreamActions } = Turbo

StreamActions

**Comment by koenhandekyn** [comment]
Thanks !  From a documentation perspective this was hard to find (at least for me) but with this ticket, it will surely already help ;) 

Somehow I still feel that it would be ’simpler’ if one could import in the same way between turbo and turbo-rails, the average user would find that less of a surprise :) 

Thanks again
