### ISSUE TITLE
turbo does not works with seeders

### ISSUE THREAD

**Issue by matias-carpintini** [hotwired/turbo-rails#444]
Trying to run a seeder but gets random errors, since (i suppose) there's no subscribers yet.

seed.rb sample
```
Category.create!(
 name: 'Lorem ipsum',
 business_id: 1
)
```

category model:
```
after_create_commit do 
    broadcast_prepend_to "broadcast_to_business_#{business_id}", 
      target: :categories
  end
```
  
(when running rails db:seed) gets me:
 
<img width="845" alt="Screenshot 2023-03-23 at 10 31 17" src="https://user-images.githubusercontent.com/20630951/227219519-8ad81ff2-e747-4da9-af74-d1a5066bed8d.png">

**Comment by dhh** [comment]
You'll have to create your seeds in order, so the dependencies are satisfied.
