### ISSUE TITLE
turbo_stream_from "..." does not work with pace.js

### ISSUE THREAD

**Issue by nkokkos** [hotwired/turbo-rails#450]
Hi.

this is not really important. I am just including this here just in case someone else runs into the same problem.

I use esbuild to bundle the javascript files. 

Now, if I use this progress bar: https://github.com/CodeByZach/pace/

by including it with:

import 'pace-js';
 
then this:

<%= turbo_stream_from "your_id_here" %> stops working. It just stops transmitting.

I looked at the logs and the "DEBUG -- : Turbo::StreamsChannel transmitting.." is not present in the logs.

Once I remove pace-js, everything's back to normal.

**Comment by jjf21** [comment]
Thanks for this ! Had `pace.js` in my themes, could have searched for days ! 🙏

**Comment by nkokkos** [comment]
> Thanks for this ! Had `pace.js` in my theme vendors, could have searched for days ! 🙏

I guess we can use the build in progress bar of turbo-rails. :-)
