### ISSUE TITLE
link_to with Turbo.visit() won't invoke format: turbo stream in controller

### ISSUE THREAD

**Issue by blakeage** [hotwired/turbo-rails#460]
### My Environment:
turbo-rails: 1.4.0
rails: 7.0.4.3
stimulus-rails: 1.2.1

I'm trying to click a link to edit an item on my index view (/categories), but I want to update the url with /categories/1/edit, but my setup is not working.  The edit action of the controller is invoked with HTML format instead of the desired TURBO_STREAM.

My index view:
```
<div data-controller="categories">
  <%= turbo_frame_tag :categories do %>
    <!-- categories loop/list -->
    <%= link_to edit_btn("Edit"), edit_category_path( cat ), class: "btn btn-secondary btn-sm me-2", data: { turbo_stream: true, action: 'click->categories#loadEditFrame' } %>
  <% end %>
</div>
```

My 'categories' Stimulus controller:

```
import { Controller } from "@hotwired/stimulus"
export default class extends Controller {
  loadEditFrame(event) {
    event.preventDefault();
    const url = event.target.getAttribute('href');
    console.log(`turbo visiting ${url}`);
    Turbo.visit(url, { frame: 'categories', turbo: true });
  }
}
```

Rails categories Controller:
```
def edit
  respond_to do |format|
    format.turbo_stream {
      render turbo_stream: turbo_stream.update("categories", template: 'categories/edit')
    }
  end
end
```

This does update the url, but the format is HTML.  If I remove the data-action bit from the link, the edit method of the controller is correctly invoked with format TURBO_STREAM, but the url stays at /categories.

Is there a better way of doing this?  Or am I missing an attribute somewhere?

**Comment by blakeage** [comment]
I've been able to work around the issue.  I may be mis-understanding the nature of Turbo, and if I am, feel free to close this.  I don't know if this setup of frames (loading a turbo frame on the index view, and when a link is clicked, replacing that frame with the edit template via Turbo Stream), is the recommended way of doing this.

Nevertheless, this seems to do what I wanted:

Respond to html format in the controller, which is only there to handle page reloads when on /categories/1/edit.  I updated my Rails controller method to:
```
  def edit
    respond_to do |format|
      format.html{ render :edit }
      format.turbo_stream {
        render turbo_stream: turbo_stream.update("categories", template: 'categories/edit')
      }
    end
  end
```

Change the stimulus controller to use fetch() with a header instead of Turbo.visit():
```
  loadEditFrame(event) {
    event.preventDefault();
    const url = event.target.getAttribute('href');
    fetch(url, { headers: { Accept: "text/vnd.turbo-stream.html" }})
    .then(r => r.text())
    .then(html => Turbo.renderStreamMessage(html))
    .then(_ => history.replaceState(history.state, "", url));
  }
```

Stolen from this comment:
[https://github.com/hotwired/turbo/issues/34#issuecomment-821881266](https://github.com/hotwired/turbo/issues/34#issuecomment-821881266)

**Comment by seinwave** [comment]
Something to try, if you're still hunting for an alternative way to do this. 

Try adding an `acceptsStreamResponse` option to your `Turbo.visit()` call. Like so:

```ruby
import { Controller } from "@hotwired/stimulus"
export default class extends Controller {
  loadEditFrame(event) {
    ...
    Turbo.visit(url, { frame: 'categories', turbo: true, acceptsStreamResponse: true });
  }
}
```

This solved a similar problem I was having with programatically invoking `Turbo.visit()` in a Stimulus controller.

Hope this helps!

**Comment by tf-matak** [comment]
Works for me by adding `format=turbo_stream` to the GET url for Rails 

`this.visitUrl(url, frame )`


`Started GET "/tests/upload?id=143775&frame=setup_load_bulk_upload&partial=/bulk_upload&format=turbo_stream
`

```
respond_to do |format|
      format.html { render 'form' }
      format.turbo_stream do
        render turbo_stream: turbo_stream.replace(params[:frame], partial: params[:partial], locals: "some locals dagta")
      end
    end
```

**Comment by brunoprietog** [comment]
Yes, this is the expected behavior. `Turbo.visit` doesn't handle Turbo stream responses. You can use [request.js](https://github.com/rails/request.js) to send Turbo stream requests and handle them properly more easily with JavaScript.

**Comment by rangerscience** [comment]
As per @brunoprietog 's comment, looks like this Just Worked(tm):

```
import { get } from '@rails/request.js'
// ...
await get(url, {responseKind: "turbo-stream"})
```

The magic (both Rails and Turbo) handles the rest :)
