### ISSUE TITLE
Turbo Drive issue with Cloudflare

### ISSUE THREAD

**Issue by finist** [hotwired/turbo-rails#461]
Rails 7 application and login form with email/password pair:

```
<%= form_with model: @user, url: sessions_path do |f| %>
    <%= f.text_field :email, autofocus: true %>
    <%= f.password_field :password %>
    
    <%= @user.errors.messages[:password].first %>
    
    <%= f.submit 'Login' %>
<% end %>
```

Request processing by sessions controller:
```
def create
  email, password = sessions_params.values_at(:email, :password)
  @user = User.new(email: email)

  if login(email, password)
    redirect_to root_path
  else
    @user.errors.add(:password, t('.invalid_email_or_password'))
    render :index, status: :unprocessable_entity
  end
end
```

After submitting form with incorrect login/pass, page not update, it not show error message, and in browser console i see only standard 422 error, other forms behave the same. And it happens only for server with Cloudflare dns and https. On local environment it works well, on staging server also, on staging server with letsencrypt certificate well too, but with Cloudflare something is breaking.

**Comment by finist** [comment]
I made some experiments and found 2 strange things: 
1) Request returns with status 422 and unreadable body, in chrome web inspector on network tab request preview show message: "Failed to load response data...". After this immediately runs GET request to the same url. Correct result should return 422 response with readable body and without addition requests.
2) If i copy problem request as cURL and run it in console, i get correct result.

**Comment by finist** [comment]
Ok, i understand why response body is unreadable, it happens when you have 'Preserve log' checked and you are trying to view the response data of a previous request after you have navigated away. So i added some debugs to the turbo events for intercept response body and found it stops on `before-fetch-response`. Next event is not reachable and page self refreshing.  So i can't get body, but looks like it not needed anymore, the problem hidden in javascripts jungle

**Comment by finist** [comment]
Catch it! This problem has a name: "Rocket Loader" https://developers.cloudflare.com/fundamentals/speed/rocket-loader/. It change type attribute for script tag by adding uniq hash `type="3789c816c11d39c42c775236-text/javascript"`. But turbo has check for every response is script and link tags are changed. And if yes, turbo reload the page instead of rendering content. So fast decision just disable this feature for Cloudflare.

Another question should turbo ignore this attribute?

**Comment by dhh** [comment]
Don't really want to add company-specific code to Turbo to account for this. I suggest you turn off Rocket Loader instead when using Turbo.
