### ISSUE TITLE
Feature request: Make turbo_frame_request? available as a helper method so apps using this gem can access it

### ISSUE THREAD

**Issue by nickjj** [hotwired/turbo-rails#469]
Currently this method exists privately:

https://github.com/hotwired/turbo-rails/blob/ea00f3732e21af9c2156cf74dabe95524b17c361/app/controllers/turbo/frames/frame_request.rb#L29-L31

What do we think about adding `helper_method :turbo_frame_request?` so it's available in an app's controllers and views?

#### Happy case using frames

- You have a blog post and a list of comments on `/blog/3`
- When clicking the edit button of a comment, it loads the comment edit form in a frame
- At this point you're still on the post page and the comment's contents have been replaced with an edit form for the comment
- You edit the comment and everything "just works"
- To make this work you have `edit` and `update` routes available on the comment

#### Unhappy case not using frames

If someone manually visits `/blog/3/comments/2/edit` they can attempt to edit a comment outside of it being rendered within a post. Since all of this happens in a frame when they submit the edit, they'll still end up outside of the desired frame.

It creates for a weird user experience where someone can end up in an unintended state.

Now, you could be an exemplary citizen of the web and go all-in with progressive enhancements and make that edit page have a bunch of non-frame markup so it gets rendered correctly but for a large classification of apps, it's going to be expected Javascript is enabled.

There's also other related use cases where you wouldn't want to use `turbo_action: "advance"` and you could make a case where you don't want the `edit` page directly accessible.

### Solution

I don't know if this is a best practice but I found myself doing this in my `application_controller.rb` file:

```rb
  helper_method :turbo_frame_request?

  def raise_404_unless_turbo_frame_request
    raise ActionController::RoutingError.new("Not Found") unless turbo_frame_request?
  end

  private

  def turbo_frame_request?
    request.headers["Turbo-Frame"].present?
  end
```

Then in my `edit` action I drop in:

```rb
    def edit
      raise_404_unless_turbo_frame_request
    end
```

This blocks being able to access the edit page directly unless it's in a frame.

Having `turbo_frame_request?` available by this gem would avoid needing to duplicate this method in a number of apps.

You could make a case that the 404 method is also pretty interesting to have available but that's a separate issue.

#### Why `helper_method` is handy

It's handy to access in views too because I found myself doing this in my `course` layout:

```erb
<%= render "courses/toc", course: @course, sections: @sections, lesson_count: @lesson_count, lesson_completions: @lesson_completions unless turbo_frame_request? %>
```

That TOC is really heavy, it's potentially rendering up to 150 lessons with quite a few related models. I designed my app so that clicking a lesson link in the TOC updates a video player frame. This avoids having to re-render the entire TOC using turbo drive. I wasn't sure how else to solve that, but it's a use case where I wanted to detect if it's a frame request at the view layer and do something different if it is / isn't.

**Comment by brunoprietog** [comment]
Done in #564
