### ISSUE TITLE
Possible install instruction change needed for Webpacker 6

### ISSUE THREAD

**Issue by noelrappin** [hotwired/turbo-rails#48]
I was trying to run the install instructions against the Webpacker 6 beta.

Taking my example which already worked against Webpacker 5, and upgrading Webpacker, my Turbo install was no longer downloading. (The links that had been identified in the log as being processed `as TURBO_STREAM` no longer were, the behavior was no longer working, and Turbo was no longer in the sources tab).

Adding a `console.log(Turbo)` to the `application.js` file makes everything work again, so I guess I'd assume that the switch to Webpacker 6 and the `javascript_packs_with_chunks_tag` helper somehow doesn't realize that Turbo is being used and therefore doesn't download it with the pack?

Is there a preferred way of managing this? 

Thanks!

**Comment by dhh** [comment]
Sounds like Webpack is shaking its tree and not finding any usages of Turbo in the pack itself. @javan any idea how we might stop this from happening? Maybe with Webpack we shouldn't have the lib call start() itself.

**Comment by styrmis** [comment]
I'm experiencing the same with webpacker 5.1.1. To get around it I've added a `Turbo.start()` call after the import, as it looks like this [should have no effect](https://github.com/hotwired/turbo-rails/blob/fef7558015a1d7fa1a6cdf4456322f73fd677fec/app/assets/javascripts/turbo.js#L2408) beyond persuading Webpack to keep `Turbo` in the tree.

I'm only using `javascript_pack_tag`, not `javascript_packs_with_chunks_tag`.

**Comment by javan** [comment]
Does this "fix" it?
```diff
- import { Turbo, cable } from "@hotwired/turbo-rails"
+ import "@hotwired/turbo-rails"
```

**Comment by styrmis** [comment]
> Does this "fix" it?
> 
> ```diff
> - import { Turbo, cable } from "@hotwired/turbo-rails"
> + import "@hotwired/turbo-rails"
> ```

Yes, this works fine.

**Comment by noelrappin** [comment]
Yeah that worked for me under Webpacker 6 beta also.

**Comment by chmich** [comment]
Thanks, same for [vite](https://rubygems.org/gems/vite_rails)

```
import { Turbo, cable } from '@hotwired/turbo-rails'
Turbo.start()
```

For Turbo itself, this was not necessary, but ActionCable only worked in this way.
