### ISSUE TITLE
link_to is not disabled during the turbo request

### ISSUE THREAD

**Issue by unlimit** [hotwired/turbo-rails#482]
Hi.

I'm upgrading my app from Rails 6 to Rails 7. Replacing a lot of rails-ujs code with turbo.
For now I disabled turbo globally with:
`Turbo.session.drive = false`
And then I enable it for the forms and links I need. Here is an example:
`<%= link_to "Remove", todo_item_path(item.id), data: { turbo: true, turbo_method: :delete, turbo_submits_with: 'Removing...' } %>`
This link sends proper delete request and gets a turbo stream response from the server.
I expected that link will be disabled during the request, which prevent it from multiple clicks and it will also show 'Removing...' text, but it doesn't work this way.
In the same time if I use `button_to` instead of `link_to` everything works fine. The button becomes disabled and it changes the button text.

Is this expected behavior for a `link_to`?

**Comment by dhh** [comment]
Yes, expected behavior. There's no built-in link disabling in Turbo. You should strive to use buttons for mutating actions anyway for accessibility reasons.
