### ISSUE TITLE
Cant import Turbo on rails asset pipeline

### ISSUE THREAD

**Issue by humphreyja** [hotwired/turbo-rails#49]
Importing with ESM doesn't seem to work with the rails asset pipeline

The following throws an error about the package not being found
```js
import { Turbo } from 'turbo'
```
I set up a rails app with the `--skip-javascript` option and ran `rails turbo:install`

Importing stimulus works but I cant seem to import turbo.

I also tried this package name which also doesn't work
```js
import { Turbo, cable } from "@hotwired/turbo-rails"
```

Am I missing something?

**Comment by dhh** [comment]
You have to add turbo by yourself to the importmap for this to work. Otherwise you'd have to use absolute requires.

**Comment by dhh** [comment]
(I'd be happy to see an addition to the docs explaining this further).
