### ISSUE TITLE
`turbo:render` event is not dispatched after `Turbo.renderStreamMessage`

### ISSUE THREAD

**Issue by imanpalsingh** [hotwired/turbo-rails#497]
I'm using JavaScript to request and render a turbo stream

```js
const response = await fetch(url, {
      ...
      headers: {
        Accept: "text/vnd.turbo-stream.html",
      },
    });
    
const turboStream = await response.text();
Turbo.renderStreamMessage(turboStream);
```

and observed that `turbo:render` event is not raised on calling `Turbo.renderStreamMessage(turboStream)`. Is this intentional or we can add this ?

**Comment by seanpdoyle** [comment]
The `turbo:render` event will only be dispatched while [navigating during a Turbo Drive Visit](https://turbo.hotwired.dev/reference/events).

If you need to execute JavaScript when the Stream is rendered, you could [define that behavior with a Stimulus controller's `connect()` hook](https://turbo.hotwired.dev/handbook/streams#but-what-about-running-javascript%3F).
