### ISSUE TITLE
Console Syntax Error

### ISSUE THREAD

**Issue by Jake839** [hotwired/turbo-rails#509]
Hi, I'm getting the following error in my JS console: 
SyntaxError: Unexpected string literal "@hotwired/turbo-rails". import call expects one or two arguments.

Do you guys know how to fix the error? 
My Gemfile has: 
gem "turbo-rails"

And I have the following at the top of my application.js:
// Configure your import map in config/importmap.rb. Read more: https://github.com/rails/importmap-rails
import "@hotwired/turbo-rails"
import "controllers"

// For chartkick.com
import "chartkick"
import "Chart.bundle"

//Globally disable Turbo for forms 
Turbo.setFormMode("off")

//= require jquery3 Added per ChatGPT 11/4/23
```

My app where this error is occurring is at https://github.com/Jake839/POTUS-Forum

**Comment by marckohlbrugge** [comment]
Did you solve this? I have the same issue after switching from esbuild to importmap

**Comment by marckohlbrugge** [comment]
I solved it by removing the explicit inclusion of `application.js`.

**Before:**
```html+erb
<head>
  <%= javascript_importmap_tags %>
  <%= javascript_include_tag "application" %>
</head>
```

**After:**
```html+erb
<head>
  <%= javascript_importmap_tags %>
</head>
```

**Comment by atstockland** [comment]
I just encountered this when upgrading from 7.2 to 8-beta.  My app has never used importmaps.  I'll post back if I figure out what's causing it.
