### ISSUE TITLE
Link_to with method: :post redirects

### ISSUE THREAD

**Issue by arpansac** [hotwired/turbo-rails#52]
Just found these:

- If we use the `link_to` tag with `method: :post` it redirects instead of rendering inside the turbo_frame (get works fine)
whereas `button_to' displays usual behaviour by rendering it inside the turbo_frame

- `link_to...do` always redirects to a new page

Are these the usual behaviors, I'm totally new, watching a lot of tutorials here

**Comment by dhh** [comment]
The remote-powered `link_to` helpers do not currently trigger Turbo. I'll document this, and then we'll consider whether we'll want to support this in the future. Thanks for reporting!

**Comment by dhh** [comment]
Documented in 9d53529bedd4de19dea8521d415f40685dfe7749.
