### ISSUE TITLE
RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by psantos10** [hotwired/turbo-rails#526]
I just created a new app using the following command: 

```
rails new demo -a propshaft -T -j bun -c tailwind
```

Then run the following commands:

```
bin/rails g model User name

bin/rails db:migrate
```

Created a simple controller with a single `new` action with the related view:

```
<h1>Create new user</h1>


<%= form_with model: @user do |form| %>
  <div>
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

```

If I try to submit the form, the form is not submitted and I got the following error on browser's console:

> application-42fbe8c3175662614184a417572cdac9274ca809.js:3648 RangeError: Maximum call stack size exceeded
>     at application-42fbe8c3175662614184a417572cdac9274ca809.js:754:41
>     at Array.map (<anonymous>)
>     at uuid (application-42fbe8c3175662614184a417572cdac9274ca809.js:754:37)
>     at fetch (application-42fbe8c3175662614184a417572cdac9274ca809.js:858:22)
>     at fetch (application-42fbe8c3175662614184a417572cdac9274ca809.js:861:17)
>     at fetch (application-42fbe8c3175662614184a417572cdac9274ca809.js:861:17)
>     at fetch (application-42fbe8c3175662614184a417572cdac9274ca809.js:861:17)
>     at fetch (application-42fbe8c3175662614184a417572cdac9274ca809.js:861:17)
>     at fetch (application-42fbe8c3175662614184a417572cdac9274ca809.js:861:17)
>     at fetch (application-42fbe8c3175662614184a417572cdac9274ca809.js:861:17)
> formSubmissionErrored @ application-42fbe8c3175662614184a417572cdac9274ca809.js:3648
> requestErrored @ application-42fbe8c3175662614184a417572cdac9274ca809.js:2153
> perform @ application-42fbe8c3175662614184a417572cdac9274ca809.js:1937
> await in perform (async)
> start @ application-42fbe8c3175662614184a417572cdac9274ca809.js:2100
> submitForm @ application-42fbe8c3175662614184a417572cdac9274ca809.js:3584
> formSubmitted @ application-42fbe8c3175662614184a417572cdac9274ca809.js:4424
> submitBubbled @ application-42fbe8c3175662614184a417572cdac9274ca809.js:2268
> application-42fbe8c3175662614184a417572cdac9274ca809.js:754 Uncaught (in promise) RangeError: Maximum call stack size exceeded
>     at application-42fbe8c3175662614184a417572cdac9274ca809.js:754:41
>     at Array.map (<anonymous>)
>     at uuid (application-42fbe8c3175662614184a417572cdac9274ca809.js:754:37)
>     at fetch (application-42fbe8c3175662614184a417572cdac9274ca809.js:858:22)
>     at fetch (application-42fbe8c3175662614184a417572cdac9274ca809.js:861:17)
>     at fetch (application-42fbe8c3175662614184a417572cdac9274ca809.js:861:17)
>     at fetch (application-42fbe8c3175662614184a417572cdac9274ca809.js:861:17)
>     at fetch (application-42fbe8c3175662614184a417572cdac9274ca809.js:861:17)
>     at fetch (application-42fbe8c3175662614184a417572cdac9274ca809.js:861:17)
>     at fetch (application-42fbe8c3175662614184a417572cdac9274ca809.js:861:17)
> (anonymous) @ application-42fbe8c3175662614184a417572cdac9274ca809.js:754
> uuid @ application-42fbe8c3175662614184a417572cdac9274ca809.js:754
> fetch @ application-42fbe8c3175662614184a417572cdac9274ca809.js:858
> fetch @ application-42fbe8c3175662614184a417572cdac9274ca809.js:861
> ...

If I comment the following line in `app/javascript/application.js`: `import "@hotwired/turbo-rails"` The app runs fine.

**Comment by seanpdoyle** [comment]
@psantos10 Thank you for opening this issue!

I've opened https://github.com/hotwired/turbo/pull/1077 to try and resolve this issue.
