### ISSUE TITLE
1.x release with suppression logic? 

### ISSUE THREAD

**Issue by earnold** [hotwired/turbo-rails#540]
I was looking for a way to suppress a broadcast, and I came across https://github.com/hotwired/turbo-rails/pull/499. Fantastic! It introduced the exact method I was hoping to find. 

However, it looks like next commit into main started preparation for the 2.0 release. 

Do you know if a 1.x release will be cut with the features in that PR?

**Comment by dhh** [comment]
No plans for that, no. We are not going to maintain features across multiple versions. But you can just start using the Turbo 8 beta through main here 👍
