### ISSUE TITLE
Suppression logic on the front end for too often page refresh in Turbo 8

### ISSUE THREAD

**Issue by ArturT** [hotwired/turbo-rails#544]
I've been testing and using Turbo 8 with morphing. I noticed that when there are a lot of updates for the active record model in a short amount of time, then sometimes the page gets a few page refreshes per second via Turbo Streams. This causes the browser to cancel the previous http request and start a new one. This shows up as a 499 http status code in Heroku logs (H27 - Client Request Interrupted).

<img width="2541" alt="cancled requests 2" src="https://github.com/hotwired/turbo-rails/assets/662545/8f76e4d5-a770-4362-b530-6d5811af06fb">

I already suppressed broadcasting model updates on the Rails app backend by removing `touch: true` on associated models. But for high traffic applications, when the active record model is often updated by parallel requests, then regular suppression logic does not help https://github.com/hotwired/turbo-rails/pull/499

Is there a way to suppress page refresh logic on the front end? For example, tell Turbo to refresh the page at most once every 2 seconds.

Any recommendation on what could be done to suppress page refreshes? Thank you.

**Comment by brunoprietog** [comment]
I've oppened [hotwired/turbo#1099](https://github.com/hotwired/turbo/pull/1099) to address this
