### ISSUE TITLE
Suggestion: turbo_stream.clear

### ISSUE THREAD

**Issue by svoop** [hotwired/turbo-rails#554]
The following code – shamelessly borrowed from the [tutorial on Hotrails](https://www.hotrails.dev/turbo-rails/turbo-frames-and-turbo-streams) – is needed in order to empty a Turbo frame:

```ruby
<%= turbo_stream.update Quote.new, "" %>
```

Would you consider a PR which adds the following doing exactly the same?

```ruby
<%= turbo_stream.clear Quote.new %>
```

**Comment by seanpdoyle** [comment]
I've opened https://github.com/hotwired/turbo-rails/pull/555 to document how applications might extend the existing methods provided by the `turbo_stream` helper.

**Comment by svoop** [comment]
@seanpdoyle Thanks for the extra docs. I take, `.clear` is not as common a case as I initially thought (sort of as a companion to `.remove`) and therefore doesn't merit to be implemented in Turbo itself. You know this much better than me, so a custom helper it is then.

**Comment by seanpdoyle** [comment]
@svoop to clarify, #555 is more than a documentation change, it also adds support. In the meantime, you can call `turbo_stream.action`:

```ruby
turbo_stream.action :clear, Quote.new
```

**Comment by alexandreruban** [comment]
@svoop I proposed this change earlier in https://github.com/hotwired/turbo-rails/pull/356 but it wasn't accepted.

You can have a look at the code and implement it yourself in your project thanks to the PR @seanpdoyle mentioned.

**Comment by svoop** [comment]
@alexandreruban Ah, `.empty`, I searched for clear (Array-like) and clean, sorry for the dupe. It sure is great to have the option to add it on a project level now.

**Comment by link0ff** [comment]
But still please add `turbo_stream.refresh`.  Indeed, it's possible now to add it as a custom action.  And also it's possible to use `turbo_stream.turbo_stream_action_tag(:refresh)`. 

However, it's so useful to employ this action instead of doing redirect that doesn't do morphing, and moreover `refresh` already belongs to the set of default actions, so that it would be nice to have such a shorthand as just `turbo_stream.refresh`.

**Comment by marcoroth** [comment]
I've been building Turbo Power to account for more common stream actions, which also exposes a `turbo_frame_reload` action:

https://github.com/marcoroth/turbo_power

Feel free to use/copy out the specific stream actions you need for your project.
