### ISSUE TITLE
Turbo Frame events question

### ISSUE THREAD

**Issue by jonsgreen** [hotwired/turbo-rails#56]
First of all, thanks to all of the developers on this project for this lovely holiday surprise gift. 

I am part of a small team of developers and today we were playing with adding some javascript/css that would add some minimal styling of turbo-frames for debugging/learning purposes. This mostly worked well when hooking into a turbo:load event; however, when just a frame was being replaced we found that there was not an event we could handle in order to update an attribute on the frame being used for debugging. Is there a way to hook into the replace event? 

Also, I am very excited about the direction of hotwire and would like to contribute in some way that would be helpful while also giving me a better understanding of the internals of the code. What is the best way to get involved at this time?

**Comment by seanpdoyle** [comment]
Is this similar to https://github.com/hotwired/turbo/issues/54?

**Comment by dhh** [comment]
Yeah, I'd love to have a debug CSS mode that calls out both frame replacements and stream updates. This should go on hotwired/turbo, though. Please give it a go.
