### ISSUE TITLE
Promoting a Frame Navigation to a Page Visit

### ISSUE THREAD

**Issue by pioter** [hotwired/turbo-rails#560]
I have problem with that part. Can you help me? https://turbo.hotwired.dev/handbook/frames#promoting-a-frame-navigation-to-a-page-visit

`<turbo-frame data-turbo-action="advance">
  <a href="/articles?page=2" rel="next">Next page</a>
</turbo-frame>
Clicking the <a rel="next"> element will set both the <turbo-frame> element’s [src] attribute and the browser’s path to /articles?page=2.`

nothing happens

**Comment by afcapel** [comment]
Please use the [forum](https://discuss.hotwired.dev/) to ask usage question. GitHub issues are for reporting bugs.

**Comment by pioter** [comment]
but it doesn't work

**Comment by seanpdoyle** [comment]
The code sample mentioned in this issue is missing an `[id]` attribute. I've opened https://github.com/hotwired/turbo-site/pull/156 to resolve the issue in the documentation. Thank you @pioter.

**Comment by pioter** [comment]
@afcapel can you help me?
