### ISSUE TITLE
`refresh` action is missing from Turbo::Streams::TagBuilder

### ISSUE THREAD

**Issue by phil-6** [hotwired/turbo-rails#579]
Attempting to user `format.turbo_stream { render turbo_stream: turbo_stream.refresh('target') }`

Raises a `NoMethodError`: `undefined method `refresh' for an instance of Turbo::Streams::TagBuilder`

I think the new `refresh` action needs to be added into the [TagBuilder](https://github.com/hotwired/turbo-rails/blob/07d3488c12774b59c6c8eb94836019557d5e2160/app/models/turbo/streams/tag_builder.rb#L43) model

**Comment by seanpdoyle** [comment]
@jorgemanrubia is the `<turbo-stream action="refresh" request-id="...">` element meant for public consumption, or is it an implementation detail of `broadcasts_refreshes`?

**Comment by seanpdoyle** [comment]
@nikolaokonesh your question does not seem related to this issue, and might be better suited as an Issue of its own.

With that being said, are you confident that the `<meta>` elements are being rendered into the document's `<head>`? If you call `turbo_refreshes_with` **after** the `yield :head` call, does it behave as you'd expect?

**Comment by nikolaokonesh** [comment]
@seanpdoyle  I tried other options, it doesn't work.

**Comment by seanpdoyle** [comment]
I've opened https://github.com/hotwired/turbo-rails/pull/595 to implement this.
