### ISSUE TITLE
Websocket doesn't work on production

### ISSUE THREAD

**Issue by pioter** [hotwired/turbo-rails#585]
What it's not working?

Nginx as reverse proxy, passenger working with apache

location /cable {
proxy_pass http://127.0.0.1:3024;
proxy_http_version 1.1;
proxy_set_header Upgrade $http_upgrade;
proxy_set_header Connection "upgrade";

proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
proxy_set_header Host $host;
proxy_set_header X-Real-IP $remote_addr;
proxy_set_header X-Forwarded-Proto $scheme;
}

in console 'WebSocket connection to 'wss://domain.com/cable' failed: '

production.rb
config.action_cable.url = 'wss://[domain.com:3024/cable'
config.web_socket_server_url = "wss://[domain.com:3024/cable"
config.action_cable.mount_path = ":3024/cable"
  config.action_cable.allowed_request_origins = ['https://domain.com',
                                                 'http://domain.com']

**Comment by brunoprietog** [comment]
Hello @pioter, this is not a Turbo or Action Cable issue, it's more a matter of the proxy settings you are using.
