### ISSUE TITLE
Chrome reloads assets in the Link preload header

### ISSUE THREAD

**Issue by jdelStrother** [hotwired/turbo-rails#590]
When using stylesheet_link_tag in Rails, it also inserts a `Link: <my_stylesheet.css>; rel=preload; as=style` header in the response.

This is also sent in the responses to Turbo navigations. In Chrome, this seems to trigger re-fetching the stylesheet (albeit from local cache), which then complains a few seconds later to console:

```
The resource http://192.168.86.25:3000/packs/css/application.css was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.
```

I can avoid the issue if I change my stylesheet tags to something like

```ruby
stylesheet_link_tag(:application, preload_links_header: !request.headers["X-Turbo-Request-Id"])
```

to avoid the Link header on turbo navigation.

Think this is a dumb Chrome bug that we should just ignore? Or should turbo-rails be automatically suppressing Link headers to avoid the redundant asset load?

**Comment by afcapel** [comment]
@jdelStrother `stylesheet_link_tag` is part of actionview, not of turbo-rails and we can not fix the issue here.

Can you open the issue in the main rails repo instead? Thanks!
