### ISSUE TITLE
Defined controller layout always gets used

### ISSUE THREAD

**Issue by acetinick** [hotwired/turbo-rails#60]
Currently Turbo should be returning responses with layout: false , however I have seen that that if a controller has a defined layout method that the controller defined layout get used in the Turbo response.

eg.

```
class TestController < ActionController::Base
  def index
  end 
end
```

Everything will work fine and application.html.erb layout will NOT be used in Turbo response

```
class TestController < ActionController::Base
  layout "custom"

  def index
  end 
end
```

custom.html.erb layout will be used for Turbo response and seems to take precendence.

Expectation is that turbo should never use layout in its response

**Comment by stgm** [comment]
We discussed at https://discuss.hotwire.dev/t/turbo-response-always-using-layout-from-controller/1713/

Let me mention my use case, which does require the availability of layouts, so it doesn't get lost in the discussion.

In my application there are a lot of settings/administration screens that are presented in an easy-to-dismiss modal dialog. All of these screens have their own controllers and they are loaded on demand. To clean up the views, I have actually put all of the boilerplate into a **layout** and assigned this layout to each of the relevant controllers.

```
<turbo-frame id="modal">
<div class="modal-content">
    <% if content_for?(:title) %>
    <div id="modal-browser-header">
        <%= yield(:title) %>
    </div>
    <% end %>
    <div id="modal-browser-body">
        <%= yield %>
    </div>
    <% if content_for?(:footer) %>
    <div id="modal-browser-footer">
        <%= yield(:footer) %>
    </div>
    <% end %>
</div>
</turbo-frame>
```

**Comment by acetinick** [comment]
I have a workaround here that I ended up using for layout methods, 

```
class TestController < ApplicationController
  layout -> { turbo_frame_request? ? false : "custom" }
end
```

This similar logic exists in Turbo::Frames::FrameRequest
