### ISSUE TITLE
Turbo Stream Partial Error handling Question

### ISSUE THREAD

**Issue by humphreyja** [hotwired/turbo-rails#62]
This is a very specific edge case me and a coworker ran into.

What is the best practice for error handling when broadcasting a turbo stream partial that contains an error?

First off, the simple solution is just to remove errors from your partials. But in a controller, I can also use the following method to render a custom error template. (say maybe render a turbo-frame="_top" to replace the page with a 500 page).

```ruby
rescue_from ActionView::Template::Error, with: :render_template_error
```
But in a model that reuses those partials and broadcasts them, when trying to broadcast the partial, the partial throws an error and I now want the page to show the 500 page. Is there a `broadcast_to "mychannel", on_error: :render_template_error`? And if that is the case, does this start to mix controller logic with model logic? Part of me feels like we should be able to broadcast controller actions.

**Comment by dhh** [comment]
I don't see a path to adding something in the model to handle this. I'd say you gotta catch this in development and with automated testing. Otherwise you'll have to use full turbo stream templates. But I wouldn't advise that.
