### ISSUE TITLE
OT: Attackers might be trying to steal your information from discuss.hotwire.dev 

### ISSUE THREAD

**Issue by MtnBiker** [hotwired/turbo-rails#621]
Your connection is not private
Attackers might be trying to steal your information from discuss.hotwire.dev (for example, passwords, messages, or credit cards). [Learn more](chrome-error://chromewebdata/#)
NET::ERR_CERT_COMMON_NAME_INVALID

Similar in Chrome and Safari.

Not sure where to post this, but nothing new on X for years.

**Comment by jdelStrother** [comment]
Where have you seen a link to discuss.hotwire.dev ? I think the regular page is [discuss.hotwire**d**.dev](https://discuss.hotwired.dev)
