### ISSUE TITLE
Using data-turbo-confirm on plain (non-form) buttons

### ISSUE THREAD

**Issue by fabian-as** [hotwired/turbo-rails#631]
Assume I have a button which simply triggers a Stimulus action:
```html
<button data-action="gallery#delete" data-turbo-confirm="Are you sure?" type="button">
  Delete image
</button>
```
With good old rails-ujs a similar `data-confirm="Are you sure?"` would work on such buttons as expected.
But with Turbo I can't get it to work. Is this a bug? Or intended behaviour?

**Comment by faizananwardeveloper** [comment]
@fabian-as `data-turbo-confirm` does not work with button tag. There is the way to run the confirmation:

Html code should be
```
<button data-action="gallery#delete" data-turbo-confirm="Are you sure?" type="button">
    Delete image
</button>
```
And you also need to add js controller
```
import {Controller} from "@hotwired/stimulus"

export default class extends Controller {
    delete(event) {
        confirm(
            event.currentTarget.getAttribute('data-turbo-confirm')
        )
    }
}
```

This will execute the confirmation elert.

**Comment by fabian-as** [comment]
Thank you @faizananwardeveloper for your proposal. But that's the way I'm doing it right now anyway 😆 I hoped that I could do it "the old way" and save me a few lines of code.

**Comment by brunoprietog** [comment]
Hey @fabian-as, you must use the `data-turbo-confirm` attribute on the form element. This is the expected behavior.
