### ISSUE TITLE
Add morph to StreamActions

### ISSUE THREAD

**Issue by cavenk** [hotwired/turbo-rails#639]
Hi, 

Is it possible to update the javascript assets 'turbo.js' to have the morph action into StreamActions? 
The turbo library already have the code but the assets file 'turbo.js' doesn't have the morph action.

Thanks

**Comment by stevschmid** [comment]
I'm a bit confused. According to the turbo [handbook](https://turbo.hotwired.dev/handbook/streams#stream-messages-and-actions), morphing can be performed with the `replace` action:

```
<turbo-stream action="replace" method="morph" target="current_step">
  <template>
    <!-- The contents of this template will replace the element with ID "current_step" via morph. -->
    <li>New item</li>
  </template>
</turbo-stream>
```

However, `turbo-rails` on `2.0.6` currently ignores the `morph` argument altogether. This call

```
turbo_stream.replace "clearance_5", method: "morph"
```

results in

```
<turbo-stream action="replace" target="clearance_5">
```

However, `morph` support seems to be present in this gem, although as an `action`. This call

```
turbo_stream.morph "clearance_5"
```

results in

```
<turbo-stream action="morph" target="clearance_5">
```

which throws an JS exception on `turbo` `8.0.5`: `Error: <turbo-stream action="morph" target="clearance_5">: unknown action`

Is this an oversight and `turbo_stream.morph` should result in `action="replace" method="morph"` instead?

**Comment by claudiug** [comment]
I think is an issue here :)

**Comment by jorgemanrubia** [comment]
Instead of a `morph` action Turbo now supports a `method=morph` attribute in the existing actions. See https://turbo.hotwired.dev/reference/streams.

**Comment by AlexKovynev** [comment]
@jorgemanrubia 

However, turbo-rails on 2.0.6 currently ignores the morph argument altogether. This call

turbo_stream.replace "clearance_5", method: "morph"

results in

<turbo-stream action="replace" target="clearance_5">

**Comment by omarluq** [comment]
@AlexKovynev nice catch!
@jorgemanrubia it appears that the attributes arg is only passed from the broadcast tag builders, I updated the model tag builders for replace and update actions to pass the same arg
https://github.com/hotwired/turbo-rails/pull/658
