### ISSUE TITLE
Still need explicit format html when render partial in turbo stream

### ISSUE THREAD

**Issue by chloerei** [hotwired/turbo-rails#65]
rails 6.1.0
turbo-rails 0.5.2

I create a minimal example in https://github.com/chloerei/turbo-stream-partial-example

When respond with:

```erb
<%= turbo_stream.append 'messages' do %>
  <%= render partial: 'message', formats: [:html] %>
<% end %>
```

Everything is ok.

when respond with:

```erb
<%= turbo_stream.append 'messages' do %>
  <%= render partial: 'message' %>
<% end %>
```

Get error:

```
ActionView::Template::Error (Missing partial home/_message, application/_message with {:locale=>[:en], :formats=>[:turbo_stream], :variants=>[], :handlers=>[:raw, :erb, :html, :builder, :ruby, :jbuilder]}. Searched in:
  * "/app/turbo-stream-partial-example/app/views"
  * "/usr/local/bundle/gems/actiontext-6.1.0/app/views"
  * "/usr/local/bundle/gems/actionmailbox-6.1.0/app/views"
):
    1: <%= turbo_stream.append 'messages' do %>
    2:   <%= render partial: 'message' %>
    3: <% end %>
```

**Comment by dhh** [comment]
That is the correct behavior in the sense that the turbo stream template is assuming all partials will also be turbo stream templates, unless you change that. We have a helper when you do the inline call, though:

```erb
<%= turbo_stream.append 'messages', @message %>
```

It also work with the partial options:

```erb
<%= turbo_stream.append 'messages', partial: "messages/message" %>
```

But if you call your own render partial, you need to add the formats options.

Feel free to look at a doc change to make this clearer.

**Comment by chloerei** [comment]
But I found a document say that format is automatically switched:

code: 
https://github.com/hotwired/turbo-rails/blob/79b5ffdaa97afe0ca901bfa2c9c1bdbdfc2c8c00/app/models/turbo/streams/tag_builder.rb#L14-L17

commit: https://github.com/hotwired/turbo-rails/commit/969d8994f55367516b7997b92e042799fdddb7fc

Did I misunderstand?

**Comment by kylekeesling** [comment]
@chloerei you may have already figured this out but the docs you are referring to reference the call that DHH mentioned, meaning if you use the `turbo_stream.append` helper you get the format switching "automatically", but if you are using the standard `render` call you'll need to explicity define `formats: [:html]`

**Comment by joshmfrankel** [comment]
As @kylekeesling mentions above, a standard render call requires the format to be explicitly defined. For example, a failure case from form submission may look like:

```
render :show, status: :unprocessable_entity, formats: :html
```

Reason being the resulting error: ActionView::MissingTemplate indicates that it is trying to render `:formats=>[:turbo_stream]` which is if you only have the HTML template it isn't going to work. (what DHH said above) Hence the above explicit definition is necessary

**Comment by scomma** [comment]
I'd like to request a reopening of this issue.

Currently this results in an unintuitive behavior where if you have a controller action do implicit rendering to a Turbo Stream template, and that template renders (via a standard `render` method) an HTML partial, the format switching happens automatically.

Once you so much as add `respond_to` to the controller action, that format switching turns off, and you have to modify the `render` call _inside_ the first template to explicitly request the HTML partial.

Illustration below. Hope this makes sense.

### Works

`x_controller.rb`
```
  def new
  end
```

`new.turbo_stream.erb`
```
render 'form', x: ...
```

`_form.html.erb`
```
<form>...
```

### Breaks

`x_controller.rb`
```
  def new
    respond_to do |format|
      format.turbo_stream
      format.html { redirect_to ... }
    end
  end
```

`new.turbo_stream.erb`
```
render 'form'
```

`_form.html.erb`
```
<form>...
```

### Workaround

`x_controller.rb`
```
  def new
    respond_to do |format|
      format.turbo_stream
      format.html { redirect_to ... }
    end
  end
```

`new.turbo_stream.erb`
```
render partial: 'form', formats: :html, locals: { x: ... }
```

`_form.html.erb`
```
<form>...
```

**Comment by greenfork** [comment]
I will add another example. When working with turbo frames, this code is perfectly valid:

```ruby
# notes_controller.rb
def update
  @note.update!
  render :edit
end
```

```ruby
# views/notes/edit.html.erb
<%= turbo_frame_tag note do %>
  # ...
<% end %>
```

But when adding `respond_to` for progressive enhancement, `render` requires a `formats` option:

```ruby
# notes_controller.rb
def update
  @note.update!

  respond_to do |format|
    format.turbo_stream { render :edit, formats: %i[html] }
    format.html { redirect_to @note }
  end
end
