### ISSUE TITLE
Turbo is not backwards compatible with Turbolinks

### ISSUE THREAD

**Issue by jclusso** [hotwired/turbo-rails#67]
I think it's a bit misleading that there is no information about how Turbo is and isn't backwards compatible with Turbolinks since installing Turbo removes Turbolinks. I'm not sure if the final release version is planned to be backwards compatible, but if not, I think a list of things that are not compatible would be very helpful for people upgrading to Turbo.

**Comment by dhh** [comment]
There's no plan for backwards compatibility. Would be nice to have a section in the docs talking about upgrading from Turbolinks to Turbo, though. Mostly it's about renaming events. Please do look into that if you'd like ✌️

**Comment by hcurotta** [comment]
A section on upgrading would be a great addition 👍  

One thing to add to the known gotchas for upgrading is that some JS libs that have added extra code to be compatible with Turbolinks won't work with Turbo and it's not always obvious when this is the case. I got stung today with Intercom. The Intercom JS file is only available from their CDN and it has some checks in it for turbolinks events but not turbo so I'll have to wait for them to make a change before I can upgrade. 

https://js.intercomcdn.com/shim.latest.js

![image](https://user-images.githubusercontent.com/1894233/104285668-0f510780-5508-11eb-9421-a81bcea7853b.png)
