### ISSUE TITLE
missing partial error with 2.0.9

### ISSUE THREAD

**Issue by Skulli** [hotwired/turbo-rails#684]
Yesterday with version 2.0.8 and today with 2.0.9 i get the following error in my specs

    ActiveAdmin::Comment DELETE /destroy returns http success
     Failure/Error: @comment.broadcast_remove_to(@comment.resource)

     ActionView::MissingTemplate:
       Missing partial active_admin/comments/_comment with {:locale=>[:de], :formats=>[:html], :variants=>[], :handlers=>[:raw, :erb, :html, :builder, :ruby, :haml, :arb, :jbuilder, :axlsx]}.

       Searched in:
         * "/home/runner/work/xxx/app/views"
         * "/home/runner/work/xxx/vendor/bundle/ruby/3.3.0/gems/devise-4.9.4/app/views"
         * "/home/runner/work/xxx/vendor/bundle/ruby/3.3.0/gems/activeadmin-3.2.5/app/views"
         * "/home/runner/work/xxx/vendor/bundle/ruby/3.3.0/gems/turbo-rails-2.0.9/app/views"
         * "/home/runner/work/xxx/vendor/bundle/ruby/3.3.0/gems/kaminari-core-1.2.2/app/views"
         * "/home/runner/work/xxx/vendor/bundle/ruby/3.3.0/gems/view_component-3.14.0/app/views"
         * "/home/runner/work/xxx/vendor/bundle/ruby/3.3.0/gems/actiontext-7.1.4/app/views"
      ./app/controllers/util/comments_controller.rb:55:in `destroy'

with a rollback, spec works fine.
Seems to be, that the codes tries to load a partial for a remove operation.

Setup is ruby 3.3.5, rails 7.1.4

**Comment by iperks** [comment]
We also get this, looking at the diff I don't see why the renderables are needed in the `broadcast_remove_to`.

**Comment by Skulli** [comment]
looks like it, waiting for 2.0.10

**Comment by dhh** [comment]
2.0.10 has this fix: https://github.com/hotwired/turbo-rails/releases/tag/v2.0.10
