### ISSUE TITLE
ActiveJob and ActionCable optional loading

### ISSUE THREAD

**Issue by kzkn** [hotwired/turbo-rails#69]
I don't use ActionCable or ActiveJob in my application. Also, I don't need real-time updates via WebSocket with Turbo.
If I comment out `require "active_job/railtie"` and `require "action_cable/engine"` in my `application.rb`, I will get the following error when eager loading.

```
=> Booting Puma
=> Rails 6.1.0 application starting in development
=> Run `bin/rails server --help` for more startup options
Exiting
/home/kazuki/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/turbo-rails-0.5.3/app/channels/turbo/streams_channel.rb:7:in `<main>': uninitialized constant ActionCable (NameError)
Did you mean?  Rational
   from /home/kazuki/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
   from /home/kazuki/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
```

I would like ActiveJob and ActionCable to be loaded only when necessary.

Thanks!

**Comment by dhh** [comment]
I don't think this gem makes sense if you're not using Action Cable. All the meat of the functionality here is around cable broadcasts. You can just use the turbo javascript library directly without this gem.

**Comment by kzkn** [comment]
Thanks for reply and suggestion.
I find the helpers and mime-type handling provided by this gem to be valuable enough.

**Comment by equivalent** [comment]
:+1:  I have similar case. I'm experimenting with  turbo-rails on a project which will never have action_cable but the whole concept of turbo frames makes sense. I'll use the native JS turbo (not a problem ) but it would be nice to have same set of helpers for the Rails views

**Comment by dhh** [comment]
@kzkn The custom mime type is only used for streams.

@equivalent Adding a gem dependency just to get these two lines of code seems a bit much: https://github.com/hotwired/turbo-rails/blob/main/app/helpers/turbo/frames_helper.rb#L27

**Comment by equivalent** [comment]
@dhh agree. I wanted to update my comment that I'll just copy and paste it from [there](https://github.com/hotwired/turbo-rails/blob/main/app/helpers/turbo/frames_helper.rb#L23) :+1:

**Comment by kzkn** [comment]
> The custom mime type is only used for streams.

Yes. But streams can be used without ActionCable, right? And it's quite useful :smiley:

**Comment by dhh** [comment]
Actually, yes, fair point. If you want to do the work to automatically detect whether ActionCable is present or not, and turn off the bits that need turning off, go ahead!

**Comment by boardfish** [comment]
hotwired/hotwire-rails#36 is linked to this issue. A good use case might be if you're spinning up a lightweight Rails app with `rails new --minimal; bundle add hotwire-rails` to test something out.

**Comment by boardfish** [comment]
As mentioned over there, `touch config/cable.yml` for an acceptable workaround, but I might open a PR here to see if we can avoid that step at all.
