### ISSUE TITLE
render_to_string raises error because request is not present

### ISSUE THREAD

**Issue by coorasse** [hotwired/turbo-rails#70]
In our application, we use an explicit call to `ActionController::Base.new.render_to_string('partial_name')` to render a partial into a string and do stuff with it.

This now causes a call to [`turbo_frame_request?`](https://github.com/hotwired/turbo-rails/blob/main/app/controllers/turbo/frames/frame_request.rb#L21) but since there is no `request`. boom.

My proposal would be to change it to `request&.headers.try(:[], "Turbo-Frame").present?`

**Comment by jonathanhefner** [comment]
@coorasse I think [`ActionController::Renderer`](https://api.rubyonrails.org/classes/ActionController/Renderer.html) is intended for your use case.  So, instead, you would write `ApplicationController.renderer.render(partial: "partial_name")`.
