### ISSUE TITLE
Helper for No-Preview

### ISSUE THREAD

**Issue by tleish** [hotwired/turbo-rails#72]
Any specific reason [turbo-rails/app/helpers/turbo/drive_helper.rb](https://github.com/hotwired/turbo-rails/blob/6ba6e005990682a61d82067dc141afdc98bd6c22/app/helpers/turbo/drive_helper.rb) only has a method to set `no-cache` but not `no-preview`?

**Comment by dhh** [comment]
no-cache is a superset of no-preview: https://turbo.hotwire.dev/handbook/building#opting-out-of-caching
