### ISSUE TITLE
undefined method `turbo_stream_from' for #<ActionView::Base:0x0000000001a798>

### ISSUE THREAD

**Issue by Nodalailama** [hotwired/turbo-rails#73]
Bonjour,

On my localhost, this error doesn't show up but on heroku, it's shows.
Is someone have any idea ?

Thanks for your time.

Cordialement,

**Comment by rguiscard** [comment]
Hi @Nodalailama, I have similar issue where turbo_stream_from is not defined in production environment. Did you solve it ?

**Comment by kwent** [comment]
Dup of https://github.com/hotwired/turbo-rails/issues/64

**Comment by Nodalailama** [comment]
Ok, thank you.
