### ISSUE TITLE
ActionCable required even when not using streams

### ISSUE THREAD

**Issue by stgm** [hotwired/turbo-rails#74]
After switching to production I was required to include Action Cable because this gem's `app/channels/turbo/streams_channel.rb` depends on it.

I am not using streams at all, so I'm wondering if this dependency is avoidable?

**Comment by dhh** [comment]
This gem is 90% wrapping for streams. So if you don't need streams, you can just use the JS library directly.

**Comment by stgm** [comment]
Oh that makes sense!
