### ISSUE TITLE
broadcasts_to does not read broadcast_target_default

### ISSUE THREAD

**Issue by kwent** [hotwired/turbo-rails#76]
Hi,

This works:

```ruby
class Post < ApplicationRecord
  belongs_to :room
  after_create_commit -> { broadcast_prepend_to :room }
  def broadcast_target_default
    "#{model_name.plural}_#{self.priority}"
  end
end
```

This doesn't:

```ruby
class Post < ApplicationRecord
  belongs_to :room
  broadcasts_to :room
  def broadcast_target_default
    "#{model_name.plural}_#{self.priority}"
  end
end
```

Probably cause https://github.com/hotwired/turbo-rails/blob/main/app/models/concerns/turbo/broadcastable.rb#L61 is init to `model_name.plural`.

I would expect same behavior and both methods to read `broadcast_target_default`. Hope this make sense !

Regards

**Comment by dhh** [comment]
Fixed in cf5f3cb4d61b50f4c19b0b55aebba00c6f428e1a. You have to override at the class level, though 👍
