### ISSUE TITLE
Syntax for returning multiple turbo streams

### ISSUE THREAD

**Issue by ghiculescu** [hotwired/turbo-rails#77]
Through trial and error I realised that a controller action can return multiple turbo streams. An example would be if you want to append an item to a list, and also show an alert that the item was created.

The syntax is a bit funky if you do it through a controller:

```ruby
respond_to do |format|
  format.turbo_stream do
    render turbo_stream: [
      turbo_stream.replace(:flash, partial: "layouts/flash", locals: { notice: "Message posted!" }),
      turbo_stream.append(:messages, partial: "messages/message", locals: { message: message })
    ]
  end
end
```

(you could also do it through a `.turbo_stream.erb` file, but I like having this in the controller)

Questions:

1) Should this be documented? If yes, I can make a PR to add it to https://github.com/hotwired/turbo-site/blob/main/docs/handbook/04_streams.md
2) Would you be open to a neater syntax? I would love to be able to chain turbo streams, like this:

```ruby
respond_to do |format|
  format.turbo_stream do
    render turbo_stream: turbo_stream
                              .replace(:flash, partial: "layouts/flash", locals: { notice: "Message posted!" })
                              .append(:messages, partial: "messages/message", locals: { message: message })
  end
end
```

**Comment by dhh** [comment]
While this is possible, it’s discouraged. I’d rather we don’t promote this. You can of course always do whatever you want, but in my style guide, this is much worse than using a template.

**Comment by miharekar** [comment]
@dhh One example where I find this useful is when I have a paginated table of items. And I delete one item. Now if I go to the next page, I'll miss one item, because the count is off by one - that one item is now on the previous page.

With multiple streams I can delete the desired item, and append one item that now belongs to this page.

**Comment by jeanmartin** [comment]
I'd like to point out that - unless I'm completely mistaken - @dhh's comment refers to multiple page updates from the **controller** as opposed to using a `.turbo_stream.erb` template. Of course, updating multiple sections in one response is reasonable, there are many valid use cases.
There seems to be quite a bit of confusion across the web linking to his comment here, claiming dhh is discouraging updating multiple sections.

**Comment by SylarRuby** [comment]
I do follow DHH's recommendations both with ruby and php but for this one, come on DHH, cant see no harm with this. Without this, i'd have to refresh the entire page.

**Comment by dhh** [comment]
What @jeanmartin said. By all means include multiple commands in your turbo stream response! It was designed for this. What I don't like is doing that inline in the controller rather than in a template. Just like rendering inline ERB templates in a controller file is discouraged.

**Comment by laptopmutia** [comment]
anyone know the syntax so that I could avoid write this ?
```
render turbo_stream: turbo_stream.prepend("flash", partial: "layouts/flash_messages"), status: :unprocessable_entity
```

I want to change this `turbo_stream.prepend("flash", partial: "layouts/flash_messages")` with my `*.turbo_stream.erb` files

**Comment by APysnack** [comment]
> While this is possible, it’s discouraged. I’d rather we don’t promote this. You can of course always do whatever you want, but in my style guide, this is much worse than using a template.

Can you link your style guide?

**Comment by koenhandekyn** [comment]
what we did - we use view components - but you can do same approach with partials ....

### add these helpers in our app controller (or app helper or ...)

```
  def turbo_stream_update(key, component)
    @turbo_stream_actions ||= []
    @turbo_stream_actions << turbo_stream.update(key, view_context.render(component))
  end

   # more if you want 

  def actions()
    @turbo_stream_actions
  end
```

###  and then you can use it like this

```

        turbo_stream_update("someid", SomeComponent.new(param1: somevalue) )
        turbo_stream_update("otherid", OtherComponent.new(other: othervalue) )
        render turbo_stream: actions
```

**Comment by richjdsmith** [comment]
A couple years later and I came across this thread. In the documentation/codebase I found `Module: Turbo::Streams::TurboStreamsTagBuilder` which had the following description:

>Most turbo streams are rendered either asynchronously via Turbo::Broadcastable/Turbo::StreamsChannel or rendered in templates with the turbo_stream.erb extension. But it’s also possible to render updates inline in controllers, like so...


@dhh , have things changed? Or is creating multiple action.turbo_stream.erb files still the preferred method?

**Comment by davidalejandroaguilar** [comment]
I _think_ this syntax (`render turbo_stream: [...]`) is now broken on 7.1 in system tests (at least with `selenium-webdriver` 4.14.0).

I'm still digging, but so far, this returns a content type mismatch. When changed to a template or Phlex component, tests pass.

`render turbo_stream: [...], content_type: "text/vnd.turbo-stream.html"` also doesn't work.

**Comment by dchacke** [comment]
Following up on DHH’s comment about using turbo-stream templates rather than inline rendering, it’s pretty easy to do:

```erb
<%= turbo_stream.replace(:flash, partial: "layouts/flash", locals: { notice: "Message posted!" }) %>
<%= turbo_stream.append(:messages, partial: "messages/message", locals: { message: @message }) %>
```

Note the change from `message` to `@message`.

I’m new to turbo streams but I find turbo-stream templates more convenient and more Rails Way™ than inline turbo streams.

It’s also easier to access helper methods from a template.

**Comment by EhtuCom** [comment]
Sorry @dhh but if I can avoid one extra file I'll do it :D
Here is a summary for the different options that each one I test and they work:
The classic with one turbo_stream file: 
```
respond_to do |format|
  format.turbo_stream
end

```
In case you want multiple formats apart of Turbo Streams:
```
 respond_to do |format|
   format.turbo_stream do
     render turbo_stream:[
       turbo_stream.replace("favorite_button_ad_#{@ad.id}", partial: "users/favorites/favorites_button", locals: {ad: @ad}),
       turbo_stream.replace("favorites_count", partial: "users/favorites/favorites_count")
     ]
   end
 end
```

**And the shortest and the one I love because I can see exactly what will happen from the controller:**
```
render turbo_stream:[
  turbo_stream.replace("favorite_button_ad_#{@ad.id}", partial: "users/favorites/favorites_button", locals: {ad: @ad}),
  turbo_stream.replace("favorites_count", partial: "users/favorites/favorites_count")
]
```
