### ISSUE TITLE
What to do with "data-turbolinks-track": "reload" ?

### ISSUE THREAD

**Issue by olimart** [hotwired/turbo-rails#84]
Hi,
Can you advise of the annotation `"data-turbolinks-track": "reload"` in `javascript_pack_tag/stylesheet_link_tag` tag?

Should we remove? rename to `data-turbo-track` ?

Thanks for sharing the library.

**Comment by dixpac** [comment]
Just rename `turbolinks` to `turbo`
`'data-turbo-track': 'reload'`

**Comment by olimart** [comment]
Thanks @dixpac
