### ISSUE TITLE
yarn package 7.0.0-beta.4 not available

### ISSUE THREAD

**Issue by thebluber** [hotwired/turbo-rails#85]
Hi,
Is there a version missmatch of turbo and turbo-rails?
I've updated the gem to v0.5.7 however running `./bin/rails turbo:install` is not installing the latest version(7.0.0-beta.4) of "@hotwired/turbo-rails" because it is not available yet. https://yarnpkg.com/package/@hotwired/turbo-rails shows that the latest version is 7.0.0-beta.3.
turbo-rails 7.0.0-beta.3. is dependent on "@hotwired/turbo": "^7.0.0-beta.2". With yarn install however @hotwired/turbo": "^7.0.0-beta.3" is installed.

**Comment by dhh** [comment]
Just pushed out the release. Forgot about that!
