### ISSUE TITLE
turbo_frame_tag does not properly wrap tables or elements within a table

### ISSUE THREAD

**Issue by crimson-knight** [hotwired/turbo-rails#88]
I use lots of tables and I've written some cool Stimulus controllers to handle a lot of the inline edit/update/destroy that I need, but I wanted to move to Hotwire instead of trying to maintain my own.

So I found out really quickly if you try:

```erb
<table>
  <thead>
    <tr>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <%= turbo_frame_tag "interesting_table" do %>
      <tr>
        <td>Something... something...</td>
        <td>...darkside</td>
      </tr>
    <% end %>
  </tbody>
</table>
```

The turbo frame will render OUTSIDE of and BEFORE the `<tbody>` tag, like this:

```erb
<turbo-frame id="interesting_table"></turbo-frame>
<table>
  <thead>
    <tr>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
      <tr>
        <td>Something... something...</td>
        <td>...darkside</td>
      </tr>
  </tbody>
</table>
```

You can re-create exactly this by running `rails new ...` and on a scaffolded index page try wrapping the table in the turbo_frame_tag around the basic table provided and it will NOT render the frame around the table body or within the `<table>` tag.

Nothing I do changes this. Is this on purpose? This seems like extremely odd behavior, but hey if I missed something please let me know! :) 

Otherwise I may dive into this and make a PR. I'd love a chance to contribute! Especially since I was already building something very similar on my own projects.

**Comment by seanpdoyle** [comment]
Is this a duplicate of https://github.com/hotwired/turbo/issues/48?

**Comment by crimson-knight** [comment]
Sure is! Thanks @seanpdoyle
