### ISSUE TITLE
Nested form with turbo-frames cannot use links with data-method="delete" 

### ISSUE THREAD

**Issue by allengreer-latero** [hotwired/turbo-rails#89]
Related discussion I found: #33, #50 

If I have the following in a partial `view`:
```
= form_with model: @parent do |form|
  = form.fields_for :users, user do |user_form|
    = turbo_frame_tag dom_id(user) do
      = user_form.label :first_name
      = user_form.text_field :first_name
      = link_to 'Delete', users_path(user), method: :delete  <!-- (1) -->
                              <!-- OR -->
      = button_to "Delete", users_path(user), method: :delete <!-- (2) -->
```
& the following `model`
```
class Parent < ApplicationRecord
  has_many :users
  accepts_nested_attributes_for :users
end
```
& the following `controller`
```
class UsersController < ApplicationController
  def destroy
    respond_to do |format|
      format.turbo_stream do
        user = User.find(params[:id]).destroy
       # Must match the dom_id in the view
        render turbo_stream: turbo_stream.remove("users_#{user.id}")
      end
  end
```

When attempting to delete the nested user frame through the following:
1. `link_to` (1): 
  - This works with Rails UJs as the data-method="delete" is POSTed to the users#destroy
  - This is troublesome as we are using a `<a>` tag to perform a destructive action. As mentioned, this is a no-no for a11y compliance.
2. `button_to` (2):
  - Translated to an `<input>` tag, as there is already a parent `form` tag present
  - On submission: this sends a submit request to parents#destroy action
  - Is a11y compliant, but is incompatible with turbo.

Is there a way to do this natively in turbo, or will have to sprinkle in some Stimulus to wire this up correctly.
Or should I not be trying to use a nested form with a turbo tag in such a way?

**Comment by dhh** [comment]
You can't have nested forms, that's right. So that's a no go. It's an interesting conflict. If you're set on this particular UI, I'd probably hook up a button to a stimulus controller. Agree it's not graceful though.

**Comment by fffx** [comment]
How about?
```
button_tag "Delete" , formaction: users_path(user), formmethod: :delete
```

**Comment by andrespch** [comment]
@allengreer-latero how did you end up solving this? I was trying @dhh s suggestion, but I don't know how I can trigger a post request from my stimulus controller that will result in my turbo frame being refreshed. I'm relatively new to rails development, any pointers are massively appreciated!
