### ISSUE TITLE
Switching cable config to use redis during install?

### ISSUE THREAD

**Issue by fwilkens** [hotwired/turbo-rails#94]
During install, I noticed output from  the install script that it had added redis to the bundle and changed the action cable dev config to specify redis as the adapter. Will streams work with all of the existing cable adapters, or is redis preferred?

https://github.com/hotwired/turbo-rails/blob/main/lib/install/turbo_with_webpacker.rb#L20

**Comment by dhh** [comment]
It won't work with the default adapter that's an in-memory setup, which is thus per process. But could work with other persistent adapters. Feel free to do a PR where this replacement only happens against the default, in-memory adapter.

**Comment by fwilkens** [comment]
Understood -- thanks @dhh . I'll take a look at a PR for that, and maybe drop something in the README as well.
