### ISSUE TITLE
Does the Action Cable JS requirement need to be 6.1+?

### ISSUE THREAD

**Issue by agrobbin** [hotwired/turbo-rails#95]
We have yet to upgrade our application to 6.1, and I noticed that adding turbo-rails has also brought along `"@rails/actioncable@^6.1.0"` as a NPM dependency.

I'm wondering, is 6.1 required, or can this be loosened a bit, to allow for 6.x? I did a quick check of the Action Cable [6.1 CHANGELOG](https://github.com/rails/rails/blob/6-1-stable/actioncable/CHANGELOG.md) and didn't see anything that would indicate a substantial change in functionality *requiring* v6.1 here.

Thanks for any insight you can provide here, and for Turbo + the whole Hotwire suite, it's been great to work with!

**Comment by dhh** [comment]
Haven't tested with 6.x.0. Feel free to verify that it works, and if so, do a PR to loosen.
