### ISSUE TITLE
Explicitly rendering a different turbo stream view breaks format context

### ISSUE THREAD

**Issue by t27duck** [hotwired/turbo-rails#97]
I have a repo in "reproduction steps" below that have a simplified example of an issue I ran into with making a turbo stream POST request and explicitly rendering a turbo stream view that has an html partial in it.

I have a turbo frame, called "form-area". I have a link (let's say to a new post) that points to the frame. The new action explicitly renders a `new.turbo_stream.erb` view in it and replaces the frame as expected. That part works just fine.

```html
<!-- Main page -->
<a href="posts/new" data-turbo-frame="form-area">New Post</a>

<turbo-frame id="form-area"></turbo-frame>
```

```ruby
# new.turbo_stream.erb
<%= turbo_stream.update "form-area" do %>
  <div>Special markup I'd like wrapped around the form in a frame</div>
  <%= render 'form', post: @post %>
<% end %>
```

On the create action when I submit the form, a validation error is triggered. I choose in my respond_to block for format.turbo_stream to render :new  which means "render the new view for turbo streams. That part starts to work fine.

```ruby
# posts_controller.rb

  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: "Post was successfully created." }
        format.turbo_stream { render :new }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.turbo_stream { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end
```

HOWEVER, when the turbo stream view hits the partial (remember, I am explicitly telling the controller to render this view, I get an UnknownFormat error as turbo is not (I assume?) under the covers switching the view context to HTML to look for html partials instead of more turbo stream partials.

```
ActionView::Template::Error (Missing partial posts/_form, application/_form with {:locale=>[:en], :formats=>[:turbo_stream], :variants=>[], :handlers=>[:raw, :erb, :html, :builder, :ruby, :jbuilder]}. Searched in:
  * "/.../possible_turbo_issue/app/views"
  * "/.../.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/actiontext-6.1.1/app/views"
  * "/.../.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/actionmailbox-6.1.1/app/views"
):
    1: <%= turbo_stream.update "form-area" do %>
    2:   <div>Special markup I'd like wrapped around the form in a frame</div>
    3:   <%= render 'form', post: @post %>
    4: <% end %>

app/views/posts/new.turbo_stream.erb:3
app/views/posts/new.turbo_stream.erb:1
app/controllers/posts_controller.rb:32:in `block (2 levels) in create'
app/controllers/posts_controller.rb:26:in `create'
```

Reproduction Steps:
1. Clone repo: https://github.com/t27duck/possible_turbo_issue
2. Run `bundle install`
3. Run migrations
4. Start `rails s`
5. Go to localhost 3000
6. Click "New Post"
7. Don't fill out the form and click submit
8. See the exception in the Rails log

**Comment by excid3** [comment]
You'll need to force the partial type as `html` otherwise it will default to `turbo_stream`

That should be:
`<%= render 'form', post: @post, formats: :html %>`

**Comment by t27duck** [comment]
So after doing some further research... it is found that this does not cause the exception...

```ruby
# Create action in posts_controller.rb

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: "Post was successfully created." }
        format.turbo_stream { render :create }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.turbo_stream { render :new, formats: [:turbo_stream, :html] }
      end
    end
```

Also, when inspecting `formats` **(this is without the above workaround)**...

In the create action before calling render - `[:turbo_stream, :html]`
In the new view after calling `render` in the create action - `[:turbo_stream]`

So it seems calling `render` in the `respond_to` block messes up `formats` ?

**Comment by excid3** [comment]
It would definitely be nice if the `format.turbo_stream` automatically set the formats the same as it does normally.

**Comment by swanson** [comment]
It seems to me like the issue is in the `tag_builder`.

In the controller `respond_to` block, you want the format to only be `:turbo_stream` for `format.turbo_stream` because you want to find a matching `.turbostream.erb` view (not an `html.erb`).

In the view, when you use the `turbostream.update 'form-area'` helper, you're running through the tag builder which eventually hits this code: https://github.com/hotwired/turbo-rails/blob/main/app/models/turbo/streams/tag_builder.rb#L101-L108 -- the tag builder adds `:html` formats in all code-paths except for the `block_given` one (which you're using in this example).

So I think the issue lies in the `tag_builder`, not in the controller responder stuff.

**Comment by excid3** [comment]
Tag builder probably needs changing too, but respond_to changes it immediately as well:

```
  def create
    Rails.logger.debug("FORMATS: #{formats.inspect}")
    @post = Post.new(post_params)
    respond_to do |format|
      if @post.save
        # ...
      else
        format.html { render :new, status: :unprocessable_entity }
        format.turbo_stream { Rails.logger.debug("FORMATS: #{formats.inspect}"); render :new } 
```

```
Started POST "/posts" for ::1 at 2021-01-28 16:38:34 -0500
Processing by PostsController#create as TURBO_STREAM
  Parameters: {"authenticity_token"=>"[FILTERED]", "post"=>{"title"=>"", "content"=>""}, "commit"=>"Create Post"}
FORMATS: [:turbo_stream, :html]
FORMATS: [:turbo_stream]
```

**Comment by kaspth** [comment]
I had a branch going for this at one point, but never got to wrap it up — and that was on an older internal version of Turbo. PR welcome, if anybody wants to make this work 🙏

**Comment by excid3** [comment]
Have any thoughts on how to best solve this @kaspth? I wouldn't mind taking a stab at it, but wasn't sure the best route to go.

**Comment by kaspth** [comment]
Scrounged them up, looks like I was passing formats when rendering the template here:

```0980418 - (HEAD -> rendering-defaults) Trial out rendering defaults with fallbacks (6 months ago) <Kasper Timm Hansen>
diff --git a/app/models/turbo/updates/tag_builder.rb b/app/models/turbo/updates/tag_builder.rb
index e3ba120..0a0ce9a 100644
--- a/app/models/turbo/updates/tag_builder.rb
+++ b/app/models/turbo/updates/tag_builder.rb
@@ -24,7 +24,10 @@ class Turbo::Updates::TagBuilder
   end
 
   def command(name, element, content = nil, **rendering, &block)
-    content ||= @view_context.render(**rendering) if !block_given? && rendering.any?
+    if name != :remove && content.nil? && !block_given?
+      content = @view_context.render(rendering_with_defaults(element, **rendering))
+    end
+
     tag(name, convert_to_dom_id(element), content, &block)
   end
 
@@ -38,6 +41,17 @@ class Turbo::Updates::TagBuilder
       end
     end
 
+    def rendering_with_defaults(element, options)
+      options.to_h.tap do |o|
+        if element.respond_to?(:model_name)
+          (o[:locals]  ||= {})[element.model_name.singular.to_sym] = element
+          o[:partial]  ||= element.to_partial_path
+        end
+
+        o[:formats]  ||= %i[ page_update html ]
+      end
+    end
+
     def tag(command, dom_id, *args, **options, &block)
       options[:"data-page-update"] = [ command, dom_id ].join("#")
       @view_context.tag.template *args, **options, &block
```

But also don't think that covers the non-block case.

**Comment by swanson** [comment]
> Tag builder probably needs changing too, but respond_to changes it immediately as well:
> 
> ```
>   def create
>     Rails.logger.debug("FORMATS: #{formats.inspect}")
>     @post = Post.new(post_params)
>     respond_to do |format|
>       if @post.save
>         # ...
>       else
>         format.html { render :new, status: :unprocessable_entity }
>         format.turbo_stream { Rails.logger.debug("FORMATS: #{formats.inspect}"); render :new } 
> ```
> 
> ```
> Started POST "/posts" for ::1 at 2021-01-28 16:38:34 -0500
> Processing by PostsController#create as TURBO_STREAM
>   Parameters: {"authenticity_token"=>"[FILTERED]", "post"=>{"title"=>"", "content"=>""}, "commit"=>"Create Post"}
> FORMATS: [:turbo_stream, :html]
> FORMATS: [:turbo_stream]
> ```
> 
> So by the time it gets to render the partial, there's no `:html` format to fall back on.

This line: https://github.com/hotwired/turbo-rails/blob/main/app/models/turbo/streams/tag_builder.rb#L15 leads me to believe that it is intentional that the controller removes `:html` inside of `format.turbo_stream`. Maybe I'm reading into it too much!

If you change the controller to keep `:html` as the fallback, it could potentially respond with `new.html.erb` if you omitted `new.turbo_stream.erb` which would not work.

**Comment by swanson** [comment]
```diff
# new.turbo_stream.erb
<%= turbo_stream.update "form-area" do %>
  <div>Special markup I'd like wrapped around the form in a frame</div>
-  <%= render 'form', post: @post %>
+  <%= render partial: 'form', locals: { post: @post }, formats: :html %>
<% end %>
```

Just for clarification: this is a work-around for the issue until it can be resolved.

**Comment by t27duck** [comment]
Or, alternatively, `format.turbo_stream { render :new, formats: [:turbo_stream, :html] ` in the controller's `respond_to` block
